// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Photo;

[MessagePackObject(false)]
public partial class Album : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Level { get; set; }

    [Key(2)]
    public int PublishPageNumber { get; set; }

    [Key(3)]
    public int CurrentPresetOrder { get; set; }

}
