// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Photo;

[MessagePackObject(false)]
public partial class AlbumPage : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Page { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.EditTypes EditType { get; set; } = default!;

    [Key(3)]
    public bool Publishing { get; set; }

    [Key(4)]
    public byte[] Items { get; set; } = default!;

    [Key(5)]
    public long? AlbumThemeMasterId { get; set; }

}
