// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Photo;

[MessagePackObject(false)]
public partial class MusicVideo : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MusicVideoMasterId { get; set; }

}
