// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Photo;

[MessagePackObject(false)]
public partial class Photo : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string FileName { get; set; }

    [Key(2)]
    public string SasToken { get; set; }

    [Key(3)]
    public long? PhotoEffectMasterId { get; set; }

    [Key(4)]
    public bool Lock { get; set; }

    [Key(5)]
    public int? UseAlbumPage { get; set; }

    [Key(6)]
    public int Level { get; set; }

    [Key(7)]
    public global::Sirius.Protocol.Shared.PhotoRarities Rarity { get; set; } = default!;

    [Key(8)]
    public long? SignMasterId { get; set; }

    [Key(9)]
    public global::System.DateTime GeneratedAt { get; set; } = default!;

    [Key(10)]
    public string ThumbnailSasToken { get; set; }

    [Key(11)]
    public long[] AppearedCharacterBaseMasterIds { get; set; } = default!;

    [Key(12)]
    public long[] TaggedCharacterBaseMasterIds { get; set; } = default!;

    [Key(13)]
    public global::Sirius.Protocol.Shared.UseDecoPageFlag UseDecoPage { get; set; } = default!;

}
