// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Annotations;

public partial class InversePropertyAttribute
{
    public string MapsFromPropertyName { get; set; }

}
