// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lessons;

[MessagePackObject(false)]
public partial class CharacterLesson : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long CharacterBaseMasterId { get; set; }

    [Key(1)]
    public CharacterLessonSlot[] SetCharacters { get; set; } = default!;

    [Key(2)]
    public long BestScore { get; set; }

    [Key(3)]
    public int LeaderPosition { get; set; }

    [Key(4)]
    public long RewardReceivedHighScore { get; set; }

}
