// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lessons;

[MessagePackObject(false)]
public partial class CharacterLessonSlot : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public int Position { get; set; }

    [Key(1)]
    public long? SetCharacterId { get; set; }

}
