// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lessons;

[MessagePackObject(false)]
public partial class DailyLesson : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public int TimesLeft { get; set; }

}
