// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class CharacterPointEvent : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterPointEventMasterId { get; set; }

    [Key(2)]
    public long? CharacterBaseMasterId { get; set; }

    [Key(3)]
    public int TotalAcquiredPoint { get; set; }

    [Key(4)]
    public int LastRank { get; set; }

    [Key(5)]
    public bool ReadTips { get; set; }

}
