// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class CircleEventMission : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long CircleEventMissionMasterId { get; set; }

    [Key(1)]
    public long CurrentCount { get; set; }

    [Key(2)]
    public bool IsActive { get; set; }

}
