// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class DugongRun : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long[] ClearedCourseIds { get; set; } = default!;

    [Key(2)]
    public long[] NoMistakeCourseIds { get; set; } = default!;

    [Key(3)]
    public long DugongRunCourseGroupId { get; set; }

}
