// <auto-generated />
#nullable enable
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class EventCamp : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long EventMasterId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.CampTypes CampType { get; set; }

    [Key(3)]
    public int TotalSupportPoint { get; set; }
}
