// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class Event : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long EventMasterId { get; set; }

    [Key(2)]
    public int TotalAcquiredPoint { get; set; }

    [Key(3)]
    public global::System.DateTime AcquiredPointUpdatedDate { get; set; } = default!;

    [Key(4)]
    public int? LastRank { get; set; }

    [Key(5)]
    public bool ReadTips { get; set; }

    [Key(6)]
    public int LoginDays { get; set; }

}
