// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class SpecialEvent : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long SpecialEventMasterId { get; set; }

    [Key(2)]
    public bool ReadTips { get; set; }

}
