// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class StoryEventHighScoreBuffSetting : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long StoryEventHighScoreBuffSettingMasterId { get; set; }

    [Key(1)]
    public int CurrentLevel { get; set; }

}
