// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class StoryEventHighScorePartySlot : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryEventHighScoreClearPartyId { get; set; }

    [IgnoreMember]
    public StoryEventHighScoreParty StoryEventHighScoreParty { get; set; } = default!;

    [Key(2)]
    public int Position { get; set; }

    [Key(3)]
    public long CharacterMasterId { get; set; }

    [IgnoreMember]
    public global::Sirius.Protocol.Shared.Models.Master.CharacterMaster CharacterMaster { get; set; } = default!;

    [Key(4)]
    public int CharacterLevel { get; set; }

    [Key(5)]
    public int CharacterTalentStage { get; set; }

    [Key(6)]
    public int CharacterAwakeningPhase { get; set; }

    [Key(7)]
    public long? PosterMasterId { get; set; }

    [IgnoreMember]
    public global::Sirius.Protocol.Shared.Models.Master.PosterMaster PosterMaster { get; set; } = default!;

    [Key(8)]
    public int? PosterLevel { get; set; }

    [Key(9)]
    public int? PosterBreakthroughPhase { get; set; }

    [Key(10)]
    public long? AccessoryMasterId { get; set; }

    [IgnoreMember]
    public global::Sirius.Protocol.Shared.Models.Master.AccessoryMaster AccessoryMaster { get; set; } = default!;

    [Key(11)]
    public int? AccessoryLevel { get; set; }

    [Key(12)]
    public global::Sirius.Protocol.LiveEngine.Models.Status CurrentStatus { get; set; } = default!;

    [Key(13)]
    public bool CharacterDisplayAwakeningStatus { get; set; }

}
