// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class StoryEventHighScoreParty : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryEventMasterId { get; set; }

    [Key(3)]
    public long HighScore { get; set; }

    [Key(5)]
    public global::Sirius.Protocol.Shared.AchievementRateGrades RateGrade { get; set; } = default!;

    [Key(6)]
    public global::Sirius.Protocol.Shared.MusicDifficulties Difficulty { get; set; } = default!;

    [Key(8)]
    public global::Sirius.Protocol.Shared.HighScoreTypes HighScoreType { get; set; } = default!;

    [Key(9)]
    public long LiveSettingMasterId { get; set; }

    [Key(10)]
    public StoryEventHighScorePartySlot[] Slots { get; set; } = default!;

    [Key(11)]
    public int LeaderPosition { get; set; }

}
