// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class StoryEventHighScore : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryEventMasterId { get; set; }

    [Key(2)]
    public int CurrentEnhancementPoint { get; set; }

    [Key(3)]
    public int TotalAcquiredEnhancementPoint { get; set; }

}
