// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class TotalPointEvent : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long TotalPointEventMasterId { get; set; }

    [Key(2)]
    public long TotalAcquiredPoint { get; set; }

    [Key(3)]
    public int ReceivedRewardOrder { get; set; }

}
