// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class TournamentDetail : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long TournamentDetailMasterId { get; set; }

    [Key(2)]
    public long BestUniqueScore { get; set; }

    [Key(3)]
    public int PerfectStar { get; set; }

    [Key(4)]
    public int Perfect { get; set; }

    [Key(5)]
    public int Great { get; set; }

    [Key(6)]
    public int Good { get; set; }

    [Key(7)]
    public int Bad { get; set; }

    [Key(8)]
    public int Miss { get; set; }

    [Key(9)]
    public global::System.DateTime RecordedAt { get; set; } = default!;

}
