// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class TournamentQualifying : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long TournamentQualifyingMasterId { get; set; }

    [Key(2)]
    public long MusicCourseMasterId { get; set; }

    [Key(3)]
    public int CurrentChallengeCount { get; set; }

    [Key(4)]
    public int PerfectStar { get; set; }

    [Key(5)]
    public int Perfect { get; set; }

    [Key(6)]
    public int Great { get; set; }

    [Key(7)]
    public int Good { get; set; }

    [Key(8)]
    public int Bad { get; set; }

    [Key(9)]
    public int Miss { get; set; }

    [Key(10)]
    public decimal TotalAchievementRatePercentRecord { get; set; }

    [Key(11)]
    public int BestRecordChallengeCount { get; set; }

    [Key(12)]
    public global::System.DateTime? BestRecordDate { get; set; }

}
