// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class TrialPartyEvent : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long TrialPartyEventMasterId { get; set; }

    [Key(2)]
    public int CurrentStageOrder { get; set; }

    [Key(3)]
    public bool IsCompleted { get; set; }

}
