// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Events;

[MessagePackObject(false)]
public partial class TrialPartyEventStagePartySlot : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long TrialPartyEventStagePartyId { get; set; }

    [Key(2)]
    public int Position { get; set; }

    [Key(3)]
    public long TrialPartyCharacterMasterId { get; set; }

    [Key(4)]
    public long? TrialPartyPosterMasterId { get; set; }

    [Key(5)]
    public long? TrialPartyAccessoryMasterId { get; set; }

}
