// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lives;

[MessagePackObject(false)]
public partial class AuditionClear : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long AuditionMasterId { get; set; }

    [Key(2)]
    public byte ClearPhase { get; set; }

    [Obsolete]
    [Key(3)]
    public long AuditionClearPartyId { get; set; }

    [Key(4)]
    [Obsolete]
    public string UserId { get; set; }

    [Key(5)]
    public byte SkipClearPhase { get; set; }

}
