// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lives;

[MessagePackObject(false)]
public partial class BaseScoreBlock
{
    [Key(0)]
    public long Hash { get; set; }

    [Key(1)]
    public long Score { get; set; }

    [Key(2)]
    public int Life { get; set; }

    [Key(3)]
    public long NoteId { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.TimingTypes TimingType { get; set; } = default!;

    [Key(5)]
    public int Combo { get; set; }

}
