// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lives;

[MessagePackObject(false)]
public partial class Concert : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long ConcertMasterId { get; set; }

    [Key(1)]
    public int CurrentStageOrder { get; set; }

    [Key(2)]
    public bool ReadTips { get; set; }

}
