// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lives;

[MessagePackObject(false)]
public partial class DailyLimit : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int AutoPlayTimes { get; set; }

    [Key(2)]
    public int DailyLessonTimes { get; set; }

    [Key(3)]
    public global::System.DateTime? LastRefreshedAt { get; set; }

    [Key(4)]
    public int MusicCourseFreeChallengeTimes { get; set; }

}
