// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lives;

[MessagePackObject(false)]
public partial class LiveDropCelling : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MultiLiveScheduleMasterId { get; set; }

    [Key(2)]
    public int Count { get; set; }

    [Key(3)]
    public int TotalCellingCount { get; set; }

}
