// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lives;

[MessagePackObject(false)]
public partial class Live : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long LiveMasterId { get; set; }

    [Key(2)]
    public int TimesCompleted { get; set; }

    [Key(4)]
    public float AchievementRate { get; set; }

    [Key(5)]
    public float NotationRate { get; set; }

    [Key(6)]
    public global::Sirius.Protocol.Shared.ClearLamps ClearLamp { get; set; } = default!;

    [Key(7)]
    public global::Sirius.Protocol.Shared.LiveReleaseStatus Status { get; set; } = default!;

    [Key(8)]
    public global::Sirius.Protocol.Shared.AchievementRateGrades RateGrade { get; set; } = default!;

}
