// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lives;

[MessagePackObject(false)]
public partial class LiveDropLimit : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long MultiLiveScheduleMasterId { get; set; }

    [Key(1)]
    public int CurrentCount { get; set; }

    [Key(2)]
    public int CountLimit { get; set; }

}
