// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lives;

[MessagePackObject(false)]
public partial class MusicBookmark : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long MusicMasterId { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.MusicBookmarkFlags MusicBookmarkFlag { get; set; } = default!;

}
