// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lives;

[MessagePackObject(false)]
public partial class MusicCourse : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MusicCourseMasterId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.ClearLamps ClearLamp { get; set; } = default!;

    [Key(3)]
    public global::Sirius.Protocol.Shared.MusicCourseCertificationGrade CertificationGrade { get; set; } = default!;

    [Key(4)]
    public decimal TotalAchievementRatePercentRecord { get; set; }

}
