// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lives;

[MessagePackObject(false)]
public partial class Music : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(2)]
    public long MusicMasterId { get; set; }

    [Key(5)]
    public bool StellaReleased { get; set; }

    [Key(7)]
    public int VocalVersion { get; set; }

    [Key(8)]
    public global::Sirius.Protocol.Shared.OlivierReleaseStatuses OlivierReleaseStatus { get; set; } = default!;

    [Key(9)]
    public bool IsPossession { get; set; }

}
