// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lives;

[MessagePackObject(false)]
public partial class SenseScoreBlock
{
    [Key(0)]
    public long Hash { get; set; }

    [Key(1)]
    public long Score { get; set; }

    [Key(2)]
    public int Life { get; set; }

    [Key(3)]
    public int TimeEventSecond { get; set; }

    [Key(4)]
    public long SenseId { get; set; }

    [Key(5)]
    public int Combo { get; set; }

}
