// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Lives;

[MessagePackObject(false)]
public partial class SpRate : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long LiveMasterId { get; set; }

    [Key(2)]
    public int Point { get; set; }

}
