// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

public partial class AccessoryEffect
{
    public global::Sirius.Protocol.LiveEngine.BranchConditionTypes BranchCondition { get; set; } = default!;

    public EffectBranch[] EffectBranches { get; set; } = default!;

}
