// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class Actor
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [Key(2)]
    public long CharacterMasterId { get; set; }

    [Key(3)]
    public int AwakeningPhase { get; set; }

    [Key(4)]
    public int TalentStage { get; set; }

    [Key(5)]
    public int Position { get; set; }

    [Key(6)]
    public int SenseLevel { get; set; }

    [Key(7)]
    public Status BaseStatus { get; set; } = default!;

    [Key(8)]
    public Status CurrentStatus { get; set; } = default!;

    [Key(9)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(10)]
    public long? SecondaryCharacterBaseMasterId { get; set; }

    [Key(11)]
    public int SecondarySenseLevel { get; set; }

    [Key(12)]
    public global::Sirius.Protocol.Shared.CharacterSelectionTypes SelectionType { get; set; } = default!;

}
