// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class AdditionalScore
{
    [Key(0)]
    public long Score { get; set; }

    [Key(1)]
    public string UserId { get; set; }

    [Key(2)]
    public int TimingSeconds { get; set; }

}
