// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class EffectBranch
{
    [Key(0)]
    public long? ConditionValue { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.BranchJudgeTypes? JudgeTypes { get; set; }

    [Key(2)]
    public Effect[] SenseEffects { get; set; } = default!;

}
