// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class EffectTrigger
{
    [Key(0)]
    public global::Sirius.Protocol.LiveEngine.TriggerTypes Type { get; set; } = default!;

    [Key(1)]
    public long Value { get; set; }

}
