// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class Effect
{
    [Key(0)]
    public int Order { get; set; }

    [Key(1)]
    public long MasterId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.LiveEngine.EffectTypes EffectTypes { get; set; } = default!;

    [Key(3)]
    public EffectTrigger[] Triggers { get; set; } = default!;

    [Key(4)]
    public EffectTargetValue[] Targets { get; set; } = default!;

    [Key(5)]
    public int Duration { get; set; }

}
