// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class EffectTargetValue
{
    [Key(0)]
    public long? TargetActorId { get; set; }

    [Key(1)]
    public double Value { get; set; }

}
