// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class LiveTimeEvent
{
    [Key(0)]
    public SenseTimingEvent[] Timings { get; set; } = default!;

    [Key(1)]
    public SenseCoolTime[] CoolTimes { get; set; } = default!;

}
