// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class LiveUnit
{
    [Key(0)]
    public global::System.Collections.Generic.Dictionary<int, Actor> Actors { get; set; } = default!;

    [Key(1)]
    public global::System.Collections.Generic.Dictionary<int, TimingEvent> TimeEvents { get; set; } = default!;

    [Key(2)]
    public Sense[] PossibleSenses { get; set; } = default!;

    [Key(3)]
    public Effect[] StartEffects { get; set; } = default!;

    [Key(4)]
    public StarAct StarAct { get; set; } = default!;

    [Key(5)]
    public int TotalStatus { get; set; }

    [Key(6)]
    public int StarActSenseLightCount { get; set; }

    [Key(7)]
    public int MaxPrincipal { get; set; }

    [Key(8)]
    public bool IsFirstPlayOlivier { get; set; }

    [Key(9)]
    public int BaseScorePercentage { get; set; }

    [Key(10)]
    public double BaseScoreDifficultyAutoCoefficient { get; set; }

    [Key(11)]
    public long UActiveLiveId { get; set; }

}
