// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class LiveUnitWithOrder : LiveUnit
{
    [Key(12)]
    public int Order { get; set; }

}
