// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class SenseEffect
{
    [Key(0)]
    public int ScoreFactor { get; set; }

    [Key(1)]
    public int Principal { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.LiveEngine.BranchConditionTypes BranchCondition { get; set; } = default!;

    [Key(3)]
    public EffectBranch[] EffectBranches { get; set; } = default!;

}
