// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class Sense
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ActorId { get; set; }

    [Key(3)]
    public int CoolTime { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.SenseTypes SenseType { get; set; } = default!;

    [Key(5)]
    public global::Sirius.Protocol.LiveEngine.SenseLightTypes[] AcquirableLights { get; set; } = default!;

    [Key(6)]
    public Effect[] PreSenseEffect { get; set; } = default!;

    [Key(7)]
    public SenseEffect SenseEffect { get; set; } = default!;

    [Key(8)]
    public Effect[] PosterEffect { get; set; } = default!;

    [Key(9)]
    public Effect[] AccessoryEffect { get; set; } = default!;

    [Key(10)]
    public long[] CombinationSenseId { get; set; } = default!;

    [Key(11)]
    public long SenseMasterId { get; set; }

    [Key(12)]
    public long OriginalActorId { get; set; }

}
