// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class SenseTimingEvent
{
    [Key(0)]
    public int TimingSeconds { get; set; }

    [Key(1)]
    public int Position { get; set; }

    [Key(2)]
    public TimingEvent Event { get; set; } = default!;

}
