// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class SenseCoolTime
{
    [Key(0)]
    public int Position { get; set; }

    [Key(1)]
    public int CoolTime { get; set; }

}
