// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine.Models;

[MessagePackObject(false)]
public partial class TimingEvent
{
    [Key(0)]
    public global::Sirius.Protocol.LiveEngine.SenseLightTypes[] TotalSenseLights { get; set; } = default!;

    [Key(1)]
    public global::Sirius.Protocol.LiveEngine.SenseLightTypes[] GrantSenseLights { get; set; } = default!;

    [Key(2)]
    public bool IsStarAct { get; set; }

    [Key(3)]
    public bool LostLights { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.LiveEngine.SenseLightTypes[] AcquirableLights { get; set; } = default!;

    [Key(5)]
    public long[] SenseIds { get; set; } = default!;

    [Key(6)]
    public long[] SenseVoiceIds { get; set; } = default!;

    [Key(7)]
    public long SenseMasterId { get; set; }

}
