// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared;

public enum ActivityLogTypes
{
    None = 0,
    JoinCircle = 1,
    LeaveCircle = 2,
    ChangedPosition = 3,
    GachaAcquiredCharacter = 4,
    GachaAcquiredPoster = 5,
    PlayerRate = 6,
    FirstClearedAllPerfect = 7,
    FirstClearedFullCombo = 8,
}
