// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared;

public enum CircleJoinStatus
{
    None = 0,
    Success = 1,
    CircleIdNone = 2,
}
