// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared;

public enum CircleChatTypes
{
    Default = 0,
    JoinCircle = 1,
    LeaveCircle = 2,
    ChangedPosition = 3,
    RecuitingMultiLive = 4,
}
