// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared;

public enum MultiLiveUserStatus
{
    Joined = 0,
    SelectedMusic = 1,
    SelectedDifficulty = 2,
    ReadyGame = 3,
    BeforeGameCalculate = 4,
    PlayingGame = 5,
    ExitGame = 6,
    Disconnected = 7,
}
