// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared;

public enum MultiLiveHallStatus
{
    None = 0,
    Recruiting = 1,
    StandbyGame = 2,
    ReadyGame = 3,
    BeforeGameCalculate = 4,
    PlayingGame = 5,
}
