// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared;

public enum MultiLiveHallType
{
    None = 0,
    Sirius = 11,
    Eden = 12,
    Gingaza = 13,
    Denki = 14,
    DenkiReprint = 15,
    TeamChallenge = 21,
}
