// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared;

public enum MultiLiveJoinErrorCodes
{
    None = 0,
    ReachedMaxMember = 1,
    RoomClosed = 2,
    NotFoundHall = 3,
    NotSubscribeMatchMakingServer = 4,
    UserCanceled = 5,
    Restricting = 6,
}
