// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Parties;

[MessagePackObject(false)]
public partial class TripleCastParty : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Order { get; set; }

    [Key(2)]
    public string Name { get; set; }

    [Key(3)]
    public int LeaderPosition { get; set; }

    [IgnoreMember]
    public global::System.Collections.Generic.IReadOnlyCollection<TripleCastPartySlot> Slots { get; set; } = default!;

}
