// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Parties;

[MessagePackObject(false)]
public partial class TripleCastPartySlot : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long PartyId { get; set; }

    [Key(2)]
    public int Position { get; set; }

    [Key(3)]
    public long CharacterId { get; set; }

    [IgnoreMember]
    public global::Sirius.Protocol.Shared.Models.Characters.Character Character { get; set; } = default!;

    [Key(4)]
    public long? PosterId { get; set; }

    [IgnoreMember]
    public global::Sirius.Protocol.Shared.Models.Posters.Poster Poster { get; set; } = default!;

    [Key(5)]
    public long? AccessoryId { get; set; }

    [IgnoreMember]
    public global::Sirius.Protocol.Shared.Models.Accessories.Accessory Accessory { get; set; } = default!;

    [Key(6)]
    public global::Sirius.Protocol.Shared.BonusAbilityEnableFlags BonusAbilityEnableFlags { get; set; } = default!;

}
