// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Notifications;

[MessagePackObject(false)]
public partial class AcceptFriendRequest : global::Sirius.Protocol.Shared.INotificationObject
{
    [Key(0)]
    public string RequestUserId { get; set; }

    [Key(1)]
    public string ReceivedUserId { get; set; }

    [Key(2)]
    public string ReceivedUserName { get; set; }

}
