// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Notifications;

[MessagePackObject(false)]
public partial class MissionCleared : global::Sirius.Protocol.Shared.INotificationObject
{
    [Key(0)]
    public long MissionMasterId { get; set; }

    [Key(1)]
    public long MissionStageMasterId { get; set; }

}
