// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Notifications;

[MessagePackObject(false)]
public partial class MultiLiveRestriction : global::Sirius.Protocol.Shared.INotificationObject
{
    [Key(0)]
    public global::System.DateTime? RestrictionFinishedAt { get; set; }

}
