// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Roulettes;

[MessagePackObject(false)]
public partial class Roulette : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long RouletteMasterId { get; set; }

    [Key(2)]
    public int RollCount { get; set; }

}
