// <auto-generated />
#nullable enable
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Possession;

[MessagePackObject(false)]
public partial class FavoriteCostume : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)] public long Id { get; set; }
    [Key(1)] public long CharacterBaseMasterId { get; set; }
    [Key(2)] public long[] FavoriteCostumeMasterIds { get; set; } = [];
}
