// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Possession;

[MessagePackObject(false)]
public partial class Item : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ItemMasterId { get; set; }

    [Key(2)]
    public int Stock { get; set; }

}
