// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Possession;

[MessagePackObject(false)]
public partial class Stamp : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long[] StampMasterIds { get; set; } = default!;

    [Key(2)]
    public long[] FavoriteStampMasterIds { get; set; } = default!;

}
