// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Possession;

[MessagePackObject(false)]
public partial class Trophy : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long TrophyMasterId { get; set; }

    [Key(2)]
    public long TrophyGroupMasterId { get; set; }

    [Key(3)]
    public int CurrentOrder { get; set; }

}
