// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol;

[MessagePackObject(false)]
public partial class AccessoryEffect
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long EffectMasterId { get; set; }

    [Key(2)]
    public string Name { get; set; }

    [Key(3)]
    public string Description { get; set; }

}
