// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Comeback;

[MessagePackObject(false)]
public partial class ComebackCampaign : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long ComebackCampaignMasterId { get; set; }

    [Key(1)]
    public global::System.DateTime ActivatedAt { get; set; } = default!;

}
