// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.LiveEngine;

public enum BranchConditionTypes
{
    None = 0,
    StarActFireCount = 1,
    PartyPosition = 2,
    CompanyMemberCount = 3,
    CompanyCount = 4,
    AttributeMemberCount = 5,
    AttributeCount = 6,
    PosterAppearanceMemberCount = 7,
    LifeGuardCount = 8,
    PosterAppearanceCompanyCount = 9,
    StorageSenseLightCount = 10,
    CharacterBaseGroup = 11,
}
