// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.FriendInvitation;

[MessagePackObject(false)]
public partial class FriendInvitationMission : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long FriendInvitationMissionMasterId { get; set; }

    [Key(2)]
    public long FriendInvitationMissionStageMasterId { get; set; }

    [Key(3)]
    public int CurrentCount { get; set; }

    [Key(4)]
    public bool IsCleared { get; set; }

    [Key(5)]
    public bool IsRewardReceived { get; set; }

}
