// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Characters;

[MessagePackObject(false)]
public partial class Character : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterMasterId { get; set; }

    [IgnoreMember]
    public global::Sirius.Protocol.Shared.Models.Master.CharacterMaster CharacterMaster { get; set; } = default!;

    [Key(2)]
    public int Level { get; set; }

    [Key(3)]
    public int CurrentExperience { get; set; }

    [Key(4)]
    public int TalentStage { get; set; }

    [Key(5)]
    public int AwakeningPhase { get; set; }

    [Key(6)]
    public long CharacterBaseId { get; set; }

    [IgnoreMember]
    public CharacterBase CharacterBase { get; set; } = default!;

    [Key(7)]
    public int SenseLevel { get; set; }

    [Key(8)]
    public global::Sirius.Protocol.Shared.CharacterEpisodeOrder ReadEpisodeOrder { get; set; } = default!;

    [Key(9)]
    public global::Sirius.Protocol.Shared.CharacterEpisodeOrder ReleasedEpisodeOrder { get; set; } = default!;

    [Key(10)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(11)]
    public long? SecondaryCharacterBaseId { get; set; }

    [IgnoreMember]
    public CharacterBase SecondaryCharacterBase { get; set; } = default!;

    [Key(12)]
    public int SecondarySenseLevel { get; set; }

    [Key(13)]
    public global::Sirius.Protocol.Shared.CharacterSelectionTypes SelectionType { get; set; } = default!;

    [Key(14)]
    public bool IsFavorite { get; set; }

}
