// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Characters;

[MessagePackObject(false)]
public partial class CharacterMission : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [Key(2)]
    public long CharacterMissionMasterId { get; set; }

    [Key(3)]
    public long CurrentStageMasterId { get; set; }

    [Key(4)]
    public long CurrentCount { get; set; }

    [Key(5)]
    public int ClearedStageOrder { get; set; }

    [Key(6)]
    public int RewardReceivedStageOrder { get; set; }

    [Key(7)]
    public int CompletedLevel { get; set; }

}
