// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Characters;

[MessagePackObject(false)]
public partial class CharacterBase : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [IgnoreMember]
    public global::Sirius.Protocol.Shared.Models.Master.CharacterBaseMaster CharacterBaseMaster { get; set; } = default!;

    [Key(2)]
    public int StarRank { get; set; }

    [Key(3)]
    public int TotalStarPoint { get; set; }

    [Key(4)]
    public long? CostumeMasterId { get; set; }

    [Key(5)]
    public int KeyMissionLevel { get; set; }

    [Key(6)]
    public long PortalCharacterId { get; set; }

    [Key(7)]
    public bool PortalDisplayAwakeningStatus { get; set; }

}
