// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Characters;

[MessagePackObject(false)]
public partial class LinkCharacter : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [Key(2)]
    public long CompanyMasterId { get; set; }

    [Key(3)]
    public long? LinkedCharacterBaseMasterId { get; set; }

    [Key(4)]
    public int RewardReceivedMaxRank { get; set; }

}
