// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Comics;

[MessagePackObject(false)]
public partial class Comic : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long ComicEpisodeMasterId { get; set; }

}
