// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Missions;

[MessagePackObject(false)]
public partial class FlashSaleStage : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long FlashSaleStageMasterId { get; set; }

    [Key(2)]
    public global::System.DateTime? PurchaseLimitedAt { get; set; }

    [Key(3)]
    public bool IsDefault { get; set; }

    [Key(4)]
    public bool IsCompleted { get; set; }

}
