// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Missions;

[MessagePackObject(false)]
public partial class GradualMissionGroup : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long GradualMissionGroupMasterId { get; set; }

    [Key(2)]
    public global::System.DateTime StartAt { get; set; } = default!;

}
