// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Missions;

[MessagePackObject(false)]
public partial class Mission : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public bool IsCleared { get; set; }

    [Key(2)]
    public bool IsRewardReceived { get; set; }

    [Key(3)]
    public long MissionCurrentCount { get; set; }

    [Key(5)]
    public long MissionMasterId { get; set; }

    [Key(6)]
    public long CurrentMissionStageMasterId { get; set; }

}
