// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Missions;

[MessagePackObject(false)]
public partial class MissionPass : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long UserId { get; set; }

    [Key(2)]
    public long MissionPassMasterId { get; set; }

    [Key(3)]
    public bool Paid { get; set; }

    [Key(4)]
    public int? FreeRewardReceivedPhase { get; set; }

    [Key(5)]
    public int? SpRewardReceivedPhase { get; set; }

    [Key(6)]
    public bool Terminated { get; set; }

    [Key(7)]
    public int? FreeRewardLoopCount { get; set; }

    [Key(8)]
    public int? FreeRewardLoopReceivedPhase { get; set; }

    [Key(9)]
    public int? PaidRewardLoopCount { get; set; }

    [Key(10)]
    public int? PaidRewardLoopReceivedPhase { get; set; }

}
