// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Missions;

[MessagePackObject(false)]
public partial class PickupCharacterMission : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long PickupCharacterMissionMasterId { get; set; }

    [Key(1)]
    public long[] ReceivedDetailMasterIds { get; set; } = default!;

}
