// <auto-generated />
#nullable enable
using MessagePack;

namespace Sirius.Protocol.Shared.Models.MultiRoom;

[MessagePackObject(false)]
public partial class MultiRoomBasic : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string OwnerMultiRoomId { get; set; } = string.Empty;
}
