// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Player;

[MessagePackObject(false)]
public partial class Currency : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Coin { get; set; }

    [Key(2)]
    public int FreeJewel { get; set; }

    [Key(3)]
    public int PaidJewel { get; set; }

}
