// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Player;

[MessagePackObject(false)]
public partial class GameHint : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.PageCategories PageCategory { get; set; } = default!;

    [Key(2)]
    public bool HasAlreadyRead { get; set; }

}
