// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Player;

[MessagePackObject(false)]
public partial class HomeDisplayPreference : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long? HomeCharacterBaseMasterId { get; set; }

    [Key(3)]
    public long? MemberCharacterBaseMasterId { get; set; }

    [Key(4)]
    public long? StoryCharacterBaseMasterId { get; set; }

    [Key(5)]
    public long? ShopCharacterBaseMasterId { get; set; }

    [Key(6)]
    public long? HomeCostumeMasterId { get; set; }

    [Key(8)]
    public long? MemberCostumeMasterId { get; set; }

    [Key(9)]
    public long? StoryCostumeMasterId { get; set; }

    [Key(10)]
    public long? ShopCostumeMasterId { get; set; }

    [Key(11)]
    public long IllustCharacterMasterId { get; set; }

    [Key(12)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(13)]
    public global::Sirius.Protocol.Shared.HomeCharacterDisplayTypes HomeCharacterDisplayType { get; set; } = default!;

    [Key(14)]
    public long? LoginBonusCharacterBaseMasterId { get; set; }

    [Key(15)]
    public long? LoginBonusCostumeMasterId { get; set; }

}
