// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Player;

[MessagePackObject(false)]
public partial class Limit : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int AdditionalAcquirablePhotoLimit { get; set; }

    [Key(2)]
    public int AcquirablePhotoLimitIncreasedTimes { get; set; }

    [Key(3)]
    public int AdditionalAcquirableAccessoryLimit { get; set; }

    [Key(4)]
    public int AcquirableAccessoryLimitIncreasedTimes { get; set; }

}
