// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Player;

[MessagePackObject(false)]
public partial class UserPreference : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MultiPartyId { get; set; }

    [Key(2)]
    public global::System.DateTime? BirthDate { get; set; }

}
