// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Player;

[MessagePackObject(false)]
public partial class User : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int PlayerRank { get; set; }

    [Key(2)]
    public int CurrentRankPoint { get; set; }

    [Key(3)]
    public int CurrentStamina { get; set; }

    [Key(4)]
    public global::System.DateTime MaxStaminaRestoredAt { get; set; } = default!;

    [Key(5)]
    [Obsolete("Use Currency")]
    public int PaidJewel { get; set; }

    [Key(6)]
    [Obsolete("Use Currency")]
    public int FreeJewel { get; set; }

    [Key(7)]
    [Obsolete("Use Currency")]
    public int Coin { get; set; }

    [Key(8)]
    public int PlayerRankLimit { get; set; }

    [Key(9)]
    public int StaminaRecoverTimesWithJewel { get; set; }

    [Key(10)]
    public global::System.DateTime CircleUsageRestrictionsEndTime { get; set; } = default!;

    [Key(11)]
    public string CircleId { get; set; }

    [Key(12)]
    public global::System.DateTime GameStartAt { get; set; } = default!;

    [Key(13)]
    public string HashUserId { get; set; }

    [Key(14)]
    public global::Sirius.Protocol.Shared.BanLevels BanLevel { get; set; } = default!;

    [Key(15)]
    public global::Sirius.Protocol.Shared.TutorialStatus TutorialStatus { get; set; } = default!;

    [Key(16)]
    public int MonthlyPayment { get; set; }

    [Key(17)]
    public global::System.DateTime SplashLastDisplayedAt { get; set; } = default!;

    [Key(18)]
    public bool IsCapedPlayerRank { get; set; }

    [Key(19)]
    public bool RequireCapedPlayerRankAnnounce { get; set; }

}
