// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Player;

[MessagePackObject(false)]
public partial class UserProfile : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Introduction { get; set; }

    [Key(3)]
    [Obsolete("MainCharacterMasterId")]
    public long MainUCharacterId { get; set; }

    [Key(4)]
    public long? MNameplateId { get; set; }

    [Key(5)]
    public long MNameColorId { get; set; }

    [Key(6)]
    public long? MTrophyId1 { get; set; }

    [Key(7)]
    public long? MTrophyId2 { get; set; }

    [Key(8)]
    public long? MTrophyId3 { get; set; }

    [Key(9)]
    public double PlayerRate { get; set; }

    [Key(11)]
    public bool IsPublicPlayerRate { get; set; }

    [Key(12)]
    public global::Sirius.Protocol.Shared.LeagueClassTypes LeagueClass { get; set; } = default!;

    [Key(13)]
    public int TotalSpCount { get; set; }

    [Key(14)]
    public bool IsPublicAlbumMainPage { get; set; }

    [Key(15)]
    public long? MNameplateDetailId { get; set; }

    [Key(16)]
    public long MainCharacterMasterId { get; set; }

    [Key(17)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(18)]
    public bool IsPublicActivityLog { get; set; }

    [Key(19)]
    public long NameBaseColorMasterId { get; set; }

    [Key(20)]
    public long IconFrameMasterId { get; set; }

    [Key(21)]
    public long HomeSkinMasterId { get; set; }

}
