// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Accounts;

[MessagePackObject(false)]
public partial class ConnectWithAccount : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.AuthenticationProviders Provider { get; set; } = default!;

}
