// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Accounts;

[MessagePackObject(false)]
public partial class Restriction : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::System.DateTime? MultiLiveRestrictionFinishedAt { get; set; }

    [Key(2)]
    public bool? ReadMultiLiveRestrictionDialog { get; set; }

}
