// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Episodes;

[MessagePackObject(false)]
public partial class Episode : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long EpisodeMasterId { get; set; }

    [Key(1)]
    public bool HasReadAll { get; set; }

}
