// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Home;

[MessagePackObject(false)]
public partial class HomeBGM : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long HomeBGMMasterId { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.HomeBGMSelectionTypes SelectionType { get; set; } = default!;

    [Key(2)]
    public long? HomeBGMDetailMasterId { get; set; }

}
