// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Home;

[MessagePackObject(false)]
public partial class Lottery : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long LotteryMasterId { get; set; }

    [Key(1)]
    public LotteryPriseResult[] Results { get; set; } = default!;

}
