// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Home;

[MessagePackObject(false)]
public partial class Notification : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::System.DateTime ImportantReadAt { get; set; } = default!;

    [Key(2)]
    public global::System.DateTime UpdateReadAt { get; set; } = default!;

    [Key(3)]
    public global::System.DateTime BugReadAt { get; set; } = default!;

}
