// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Home;

[MessagePackObject(false)]
public partial class TimeLimitedControl : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long TimeLimitedControlMasterId { get; set; }

    [Key(2)]
    public global::System.DateTime ExpiredAt { get; set; } = default!;

}
