// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("AccessoryEffectFilterMaster")]
[MessagePackObject(false)]
public partial class AccessoryEffectFilterMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.LiveEngine.EffectTypes EffectType { get; set; } = default!;

    [Key(2)]
    public string Name { get; set; }

    [Key(3)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(4)]
    public int Order { get; set; }

}
