// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class AccessoryLevelPatternMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long AccessoryLevelPatternGroupMasterId { get; set; }

    [Key(2)]
    public int Level { get; set; }

    [Key(3)]
    public int RequiredCoin { get; set; }

    [Key(4)]
    public AccessoryLevelPatternItemMaster[] Items { get; set; } = default!;

}
