// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("AccessoryMaster")]
[MessagePackObject(false)]
public partial class AccessoryMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.PossessionRarities Rarity { get; set; } = default!;

    [Key(4)]
    public long AccessoryLevelPatternGroupId { get; set; }

    [Key(5)]
    public long[] FixedAccessoryEffects { get; set; } = default!;

    [Key(6)]
    public long[] RandomEffectGroups { get; set; } = default!;

    [Key(7)]
    public string PronounceName { get; set; }

    [Key(8)]
    public int Series { get; set; }

    [Key(9)]
    public int MaxLevel { get; set; }

}
