// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("ActivityLogMessageTemplateMaster")]
[MessagePackObject(false)]
public partial class ActivityLogMessageTemplateMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Realtime.Shared.ActivityLogTypes LogType { get; set; } = default!;

    [Key(2)]
    public string MessageTemplate { get; set; }

}
