// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("AdditionalRewardPackageMaster")]
[MessagePackObject(false)]
public partial class AdditionalRewardPackageMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Description { get; set; }

    [Key(2)]
    public long LiveSettingMasterId { get; set; }

    [Key(3)]
    public AdditionalRewardThingMaster[] Rewards { get; set; } = default!;

    [Key(4)]
    public bool Etcetera { get; set; }

    [Key(5)]
    public global::System.DateTime? StartDate { get; set; }

    [Key(6)]
    public global::System.DateTime? EndDate { get; set; }

    [Key(7)]
    public int Order { get; set; }

}
