// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("AlbumThemeMaster")]
[MessagePackObject(false)]
public partial class AlbumThemeMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Order { get; set; }

    [Key(2)]
    public string Name { get; set; }

    [Key(3)]
    public string Description { get; set; }

    [Key(4)]
    public bool IsHide { get; set; }

    [Key(5)]
    public bool IsDefault { get; set; }

    [Key(6)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(7)]
    public global::System.DateTime EndDate { get; set; } = default!;

}
