// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("AlbumEffectMaster")]
[MessagePackObject(false)]
public partial class AlbumEffectMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Level { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(3)]
    public long EffectMasterId { get; set; }

}
