// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("AuditionRewardPackageMaster")]
[MessagePackObject(false)]
public partial class AuditionRewardPackageMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public AuditionRewardThing[] Rewards { get; set; } = default!;

}
