// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("AuditionPhaseMaster")]
[MessagePackObject(false)]
public partial class AuditionPhaseMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long AuditionasterId { get; set; }

    [Key(2)]
    public byte Phase { get; set; }

    [Key(3)]
    public int RecommendedPlayerRank { get; set; }

    [Key(4)]
    public long ClearScore { get; set; }

    [Key(5)]
    public int? StarActCount { get; set; }

    [Key(6)]
    public long AuditionRewardPackageMasterId { get; set; }

}
