// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("BannerMaster")]
[MessagePackObject(false)]
public partial class BannerMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Order { get; set; }

    [Key(2)]
    public string Name { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.JumpTypes JumpType { get; set; } = default!;

    [Key(4)]
    public string JumpPageId { get; set; }

    [Key(5)]
    public global::Sirius.Protocol.Shared.WebLinkTypes? WebLinkType { get; set; }

    [Key(6)]
    public string LinkUrl { get; set; }

    [Key(7)]
    public global::Sirius.Protocol.Shared.BannerDeleteConditionTypes DeleteConditionType { get; set; } = default!;

    [Key(8)]
    public string DeleteConditionValue { get; set; }

    [Key(9)]
    public string ImagePath { get; set; }

    [Key(10)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(11)]
    public global::System.DateTime EndDate { get; set; } = default!;

}
