// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("BonusLiveMaster")]
[MessagePackObject(false)]
public partial class BonusLiveMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long EventMasterId { get; set; }

    [Key(2)]
    public int FirstClearEventPointQuantity { get; set; }

    [Key(3)]
    public int ClearEventPointQuantity { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.BonusLiveUnlockConditionTypes UnlockConditionType { get; set; } = default!;

    [Key(5)]
    public long? UnlockConditionValue { get; set; }

    [Key(6)]
    public BonusLiveStageMaster[] Stages { get; set; } = default!;

}
