// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("BonusLiveStageMaster")]
[MessagePackObject(false)]
public partial class BonusLiveStageMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long BonusLiveMasterId { get; set; }

    [Key(2)]
    public int Order { get; set; }

    [Key(3)]
    public long MusicMasterId { get; set; }

    [Key(4)]
    public int VocalVersion { get; set; }

    [Key(5)]
    public long SenseNotationMasterId { get; set; }

    [Key(6)]
    public global::Sirius.Protocol.Shared.Companies? RecommendedCompany { get; set; }

    [Key(7)]
    public int RecommendedLevel { get; set; }

    [Key(8)]
    public long ClearScore { get; set; }

    [Key(9)]
    public long? UnlockConditionValue { get; set; }

    [Key(10)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(11)]
    public BonusLiveStageRewardThingMaster[] Rewards { get; set; } = default!;

    [Key(12)]
    public int? ClearStarActCount { get; set; }

}
