// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class BranchMaster
{
    [Key(6)]
    public long Id { get; set; }

    [Key(0)]
    public int Order { get; set; }

    [Key(1)]
    public EffectOrderMaster[] BranchEffects { get; set; } = default!;

    [Key(2)]
    public global::Sirius.Protocol.Shared.BranchJudgeTypes? JudgeType1 { get; set; }

    [Key(3)]
    public long? Parameter1 { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.BranchJudgeTypes? JudgeType2 { get; set; }

    [Key(5)]
    public long? Parameter2 { get; set; }

}
