// <auto-generated />
#nullable enable
using MessagePack;
namespace Sirius.Protocol.Shared.Models.Master;
[MasterMemory.MemoryTable("BuffItemMaster")]
[MessagePackObject(false)]
public partial class BuffItemMaster
{
    [MasterMemory.PrimaryKey, Key(0)] public long Id { get; set; }
    [Key(1)] public long ItemMasterId { get; set; }
    [Key(2)] public int EffectType { get; set; }
    [Key(3)] public int EffectValue { get; set; }
    [Key(4)] public int Duration { get; set; }
    [Key(5)] public string Name { get; set; } = string.Empty;
    [Key(6)] public string Description { get; set; } = string.Empty;
}
