// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CampaignMaster")]
[MessagePackObject(false)]
public partial class CampaignMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Title { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(3)]
    public string IconImagePath { get; set; }

    [Key(4)]
    public int Order { get; set; }

    [Key(5)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(6)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(7)]
    public long? ComebackCampaignMasterId { get; set; }

    [Key(8)]
    public global::Sirius.Protocol.Shared.CampaignEffectTypes CampaignEffectType { get; set; } = default!;

    [Key(9)]
    public int CampaignEffectValue { get; set; }

}
