// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CategoryMaster")]
[MessagePackObject(false)]
public partial class CategoryMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CategoryGroupMasterId { get; set; }

    [Key(2)]
    public int Order { get; set; }

    [Key(3)]
    public string Name { get; set; }

}
