// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CategoryGroupMaster")]
[MessagePackObject(false)]
public partial class CategoryGroupMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Order { get; set; }

    [Key(2)]
    public string Name { get; set; }

    [Key(3)]
    public string ColorCode { get; set; }

}
