// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("ChangeBodyMotionMaster")]
[MessagePackObject(false)]
public partial class ChangeBodyMotionMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string BeforeMotionName { get; set; }

    [Key(2)]
    public string AfterMotionName { get; set; }

    [Key(3)]
    public float Second { get; set; }

}
