// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class CharacterCategoryMaster
{
    [Key(0)]
    public long CategoryMasterId { get; set; }

    [Key(1)]
    public bool IsAwaken { get; set; }

}
