// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterMaster")]
[MessagePackObject(false)]
public partial class CharacterMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [IgnoreMember]
    public CharacterBaseMaster CharacterBaseMaster { get; set; } = default!;

    [Key(2)]
    public string Name { get; set; }

    [Key(3)]
    public string Description { get; set; }

    [Key(4)]
    public string AssetId { get; set; }

    [Key(5)]
    public global::Sirius.Protocol.Shared.CharacterRarities Rarity { get; set; } = default!;

    [Key(6)]
    public global::Sirius.Protocol.Shared.Attributes Attribute { get; set; } = default!;

    [Key(27)]
    public global::Sirius.Protocol.Shared.Attributes? SecondaryAttribute { get; set; }

    [Key(7)]
    public global::Sirius.Protocol.LiveEngine.Models.Status MinLevelStatus { get; set; } = default!;

    [Key(9)]
    public long StarActMasterId { get; set; }

    [Key(10)]
    public long? AwakenStarActMasterId { get; set; }

    [Key(11)]
    public long SenseMasterId { get; set; }

    [Key(12)]
    public bool ForbidGenericItemBloom { get; set; }

    [Key(13)]
    public long BloomBonusGroupMasterId { get; set; }

    [Key(14)]
    public long SenseEnhanceItemGroupMasterId { get; set; }

    [Key(15)]
    public long FirstEpisodeReleaseItemGroupId { get; set; }

    [Key(16)]
    public long SecondEpisodeReleaseItemGroupId { get; set; }

    [Key(17)]
    public long? CharacterAwakeningItemGroupMasterId { get; set; }

    [Key(18)]
    public global::System.DateTime DisplayStartAt { get; set; } = default!;

    [Key(19)]
    public global::System.DateTime DisplayEndAt { get; set; } = default!;

    [Key(20)]
    public string UnlockText { get; set; }

    [Key(21)]
    public CharacterCategoryMaster[] Categories { get; set; } = default!;

    [Key(22)]
    public long? LeaderSenseMasterId { get; set; }

    [Key(23)]
    public int MaxTalentStage { get; set; }

    [Key(24)]
    public global::System.DateTime? MaxTalentStageReleaseDate { get; set; }

    [Key(25)]
    public long? SecondaryCharacterBaseMasterId { get; set; }

    [IgnoreMember]
    public CharacterBaseMaster SecondaryCharacterBaseMaster { get; set; } = default!;

    [Key(26)]
    public long? SecondarySenseMasterId { get; set; }

}
