// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterMissionItemMaster")]
[MessagePackObject(false)]
public partial class CharacterMissionItemMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ItemMasterId { get; set; }

    [Key(2)]
    public long CharacterBaseMasterId { get; set; }

    [Key(3)]
    public long CharacterMissionMasterId { get; set; }

}
