// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterStarRankMaster")]
[MessagePackObject(false)]
public partial class CharacterStarRankMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public int Rank { get; set; }

    [Key(1)]
    public long NextRankPoint { get; set; }

    [Key(2)]
    public long RequiredLessonScore { get; set; }

    [Key(3)]
    public float StatusBonus { get; set; }

}
