// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterBaseBloomGenericItemMaster")]
[MessagePackObject(false)]
public partial class CharacterBaseBloomGenericItemMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ItemMasterId { get; set; }

    [Key(2)]
    public long CharacterBaseMasterId { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.TalentBloomItemTypes TalentBloomItemType { get; set; } = default!;

}
