// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterLessonScoreRewardMaster")]
[MessagePackObject(false)]
public partial class CharacterLessonScoreRewardMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [Key(2)]
    public long RequiredScore { get; set; }

    [Key(3)]
    public long LessonScoreGroupMasterId { get; set; }

}
