// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterBloomDetailMaster")]
[MessagePackObject(false)]
public partial class CharacterBloomDetailMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long CharacterMasterId { get; set; }

    [Key(1)]
    public string Text { get; set; }

    [Key(2)]
    public string VoicePath { get; set; }

}
