// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterPointEventMaster")]
[MessagePackObject(false)]
public partial class CharacterPointEventMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long EventMasterId { get; set; }

    [Key(2)]
    public string Title { get; set; }

    [Key(3)]
    public long ExchangeShopMasterId { get; set; }

    [Key(4)]
    public long EventPointItemMasterId { get; set; }


    [Key(5)]
    public long[] TargetCharacterBaseMasterIds { get; set; } = [];

}
