// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterMissionStageMaster")]
[MessagePackObject(false)]
public partial class CharacterMissionStageMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterMissionCategoryLevelMasterId { get; set; }

    [Key(2)]
    public long CharacterMissionMasterId { get; set; }

    [Key(3)]
    public bool ExclusionNoSenseCharacter { get; set; }

    [Key(4)]
    public int Order { get; set; }

    [Key(5)]
    public int StageOrder { get; set; }

    [Key(6)]
    public long GoalCount { get; set; }

}
