// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterMissionMaster")]
[MessagePackObject(false)]
public partial class CharacterMissionMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Title { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.JumpTypes? JumpType { get; set; }

    [Key(3)]
    public long? JumpValue { get; set; }

    [Key(4)]
    public CharacterMissionStageMaster[] Stages { get; set; } = default!;

}
