// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterEpisodeMaster")]
[MessagePackObject(false)]
public partial class CharacterEpisodeMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterMasterId { get; set; }

    [Key(2)]
    public long EpisodeMasterId { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.CharacterEpisodeOrder EpisodeOrder { get; set; } = default!;

    [Key(4)]
    public int RequiredCharacterLevel { get; set; }

}
