// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterPointEventCharacterRankingRewardMaster")]
[MessagePackObject(false)]
public partial class CharacterPointEventCharacterRankingRewardMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterPointEventMasterId { get; set; }

    [Key(2)]
    public long CharacterBaseMasterId { get; set; }

    [Key(3)]
    public int TargetMinRank { get; set; }

    [Key(4)]
    public int TargetMaxRank { get; set; }

    [Key(5)]
    public long CharacterPointEventCharacterRankingRewardItemPackageMasterId { get; set; }

}
