// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterMissionCategoryLevelMaster")]
[MessagePackObject(false)]
public partial class CharacterMissionCategoryLevelMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.CharacterMissionCategoryTypes CategoryType { get; set; } = default!;

    [Key(2)]
    public int Level { get; set; }

    [Key(3)]
    public int GiveStarPoint { get; set; }

    [Key(4)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(5)]
    public global::System.DateTime EndDate { get; set; } = default!;

}
