// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class CharacterBloomBonusMaster
{
    [Key(1)]
    public global::Sirius.Protocol.Shared.BloomBonusTypes BloomBonusType { get; set; } = default!;

    [Key(2)]
    public string Description { get; set; }

    [Key(3)]
    public int Phase { get; set; }

    [Key(5)]
    public long EffectMasterId { get; set; }

    [Key(6)]
    public string IconPath { get; set; }

}
