// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterStarRankRewardGroupMaster")]
[MessagePackObject(false)]
public partial class CharacterStarRankRewardGroupMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public CharacterStarRankRewardMaster[] Rewards { get; set; } = default!;

}
