// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterKeyMissionMaster")]
[MessagePackObject(false)]
public partial class CharacterKeyMissionMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Level { get; set; }

    [Key(2)]
    public string Color { get; set; }

    [Key(3)]
    public int GiveStarPoint { get; set; }

    [Key(4)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(5)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(6)]
    public int RequiredCategoryCount { get; set; }

}
