// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterEpisodeReleaseItemGroupMaster")]
[MessagePackObject(false)]
public partial class CharacterEpisodeReleaseItemGroupMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public CharacterEpisodeReleaseItemMaster[] Items { get; set; } = default!;

}
