// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterBloomItemMaster")]
[MessagePackObject(false)]
public partial class CharacterBloomItemMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey(keyOrder: 0)]
    [Key(0)]
    public global::Sirius.Protocol.Shared.CharacterRarities Rarity { get; set; } = default!;

    [MasterMemory.PrimaryKey(keyOrder: 1)]
    [Key(1)]
    public int CurrentStage { get; set; }

    [Key(2)]
    public int RequiredPieceAmount { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.TalentBloomItemTypes TalentBloomItemType { get; set; } = default!;

    [Key(4)]
    public long? GenericBloomItemMasterId { get; set; }

    [Key(5)]
    public long? RequiredItemMasterId { get; set; }

    [Key(6)]
    public int? RequiredItemAmount { get; set; }

}
