// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterBaseMaster")]
[MessagePackObject(false)]
public partial class CharacterBaseMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(3)]
    public string School { get; set; }

    [Key(4)]
    public int? Grade { get; set; }

    [Key(5)]
    public int? BirthMonth { get; set; }

    [Key(6)]
    public int? BirthDay { get; set; }

    [Key(7)]
    public int Height { get; set; }

    [Key(8)]
    public string Hobby { get; set; }

    [Key(9)]
    public long CompanyMasterId { get; set; }

    [Key(10)]
    public string NameRomanization { get; set; }

    [Key(11)]
    public string SenseName { get; set; }

    [Key(12)]
    public string SenseEffect { get; set; }

    [Key(13)]
    public string CharacterVoice { get; set; }

    [Key(14)]
    public string ProfileImageAssetId { get; set; }

    [Key(15)]
    public int? Age { get; set; }

    [Key(16)]
    public string FamilyNameRomanization { get; set; }

    [Key(17)]
    public string FirstNameRomanization { get; set; }

    [Key(18)]
    public string PronounceFamilyName { get; set; }

    [Key(19)]
    public string PronounceFirstName { get; set; }

    [Key(20)]
    public string FamilyName { get; set; }

    [Key(21)]
    public string FirstName { get; set; }

    [Key(22)]
    public string EvoSenseName { get; set; }

    [Key(23)]
    public string EvoSenseEffect { get; set; }

    [Key(24)]
    public long DefaultCostumeMasterId { get; set; }

    [Key(25)]
    public global::Sirius.Protocol.Shared.CharacterBaseTypes CharacterBaseType { get; set; } = default!;

}
