// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterBloomBonusGroupMaster")]
[MessagePackObject(false)]
public partial class CharacterBloomBonusGroupMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public CharacterBloomBonusMaster[] BloomBonuses { get; set; } = default!;

    [Key(2)]
    public CharacterBloomRewardMaster[] BloomRewards { get; set; } = default!;

}
