// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterPointEventCharacterRankingRewardItemPackageMaster")]
[MessagePackObject(false)]
public partial class CharacterPointEventCharacterRankingRewardItemPackageMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public CharacterPointEventCharacterRankingRewardItemMaster[] Rewards { get; set; } = default!;

}
