// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterProfileRestrictionMaster")]
[MessagePackObject(false)]
public partial class CharacterProfileRestrictionMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [IgnoreMember]
    public CharacterBaseMaster CharacterBaseMaster { get; set; } = default!;

    [Key(2)]
    public global::Sirius.Protocol.Shared.CharacterProfileRestrictionItem ProfileRestrictionItem { get; set; } = default!;

    [Key(3)]
    public long UnlockConditionMasterId { get; set; }

    [Key(4)]
    public long ProfileUnlockValue { get; set; }

}
