// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterAwakeningItemMaster")]
[MessagePackObject(false)]
public partial class CharacterAwakeningItemMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(3)]
    public int AwakeningPhase { get; set; }

    [Key(4)]
    public long ItemMasterId { get; set; }

    [Key(5)]
    public int RequiredQuantity { get; set; }

}
