// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterPieceMaster")]
[MessagePackObject(false)]
public partial class CharacterPieceMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long ItemMasterId { get; set; }

    [Key(1)]
    public long CharacterMasterId { get; set; }

    [Key(2)]
    public int DugongRequiredAmount { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.TalentBloomItemTypes TalentBloomItemType { get; set; } = default!;

}
