// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CharacterLevelMaster")]
[MessagePackObject(false)]
public partial class CharacterLevelMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public int Level { get; set; }

    [Key(1)]
    public long ExperienceToLevelUp { get; set; }

    [Key(2)]
    public int CharacterStatusLevel { get; set; }

    [Key(3)]
    public global::System.DateTime StartDate { get; set; } = default!;

}
