// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CircleEventCircleRankingRewardItemPackageMaster")]
[MessagePackObject(false)]
public partial class CircleEventCircleRankingRewardItemPackageMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public CircleEventCircleRankingRewardItem[] Rewards { get; set; } = default!;

}
