// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CircleEventMissionRefreshSettingGroupMaster")]
[MessagePackObject(false)]
public partial class CircleEventMissionRefreshSettingGroupMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public CircleEventMissionRefreshSetting[] Settings { get; set; } = default!;

}
