// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CircleTheaterLevelMaster")]
[MessagePackObject(false)]
public partial class CircleTheaterLevelMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Level { get; set; }

    [Key(2)]
    public int StaminaBaseValue { get; set; }

    [Key(3)]
    public string Description { get; set; }

}
