// <auto-generated />
#nullable enable
using MessagePack;
namespace Sirius.Protocol.Shared.Models.Master;
[MasterMemory.MemoryTable("CircleSupportCompanyLevelLimitMaster")]
[MessagePackObject(false)]
public partial class CircleSupportCompanyLevelLimitMaster
{
    [MasterMemory.PrimaryKey, Key(0)] public long Id { get; set; }
    [Key(1)] public int Level { get; set; }
    [Key(2)] public long RequiredCoinQuantity { get; set; }
    [Key(3)] public global::System.DateTime StartDate { get; set; }
    [Key(4)] public CircleSupportCompanyLevelLimitDetailMaster[] Details { get; set; } = [];
}

[MessagePackObject(false)]
public partial class CircleSupportCompanyLevelLimitDetailMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)] public int Order { get; set; }
    [Key(1)] public long ItemMasterId { get; set; }
    [Key(2)] public long RequiredQuantity { get; set; }
}
