// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CircleEventCircleRankingRewardMaster")]
[MessagePackObject(false)]
public partial class CircleEventCircleRankingRewardMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CircleEventMasterId { get; set; }

    [Key(2)]
    public long CircleEventCircleRankingRewardItemPackageMasterId { get; set; }

    [Key(3)]
    public int TargetMinRank { get; set; }

    [Key(4)]
    public int TargetMaxRank { get; set; }

}
