// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class CircleEventMissionRefreshSetting
{
    [Key(0)]
    public int MinRefreshCount { get; set; }

    [Key(1)]
    public int MaxRefreshCount { get; set; }

    [Key(2)]
    public int RequiredCoin { get; set; }

}
