// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CircleEventMissionMaster")]
[MessagePackObject(false)]
public partial class CircleEventMissionMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CircleEventMasterId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.CircleEventMissionTypes MissionCategory { get; set; } = default!;

    [Key(3)]
    public string Title { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.JumpTypes JumpType { get; set; } = default!;

    [Key(5)]
    public long? JumpTargetId { get; set; }

    [Key(6)]
    public long GoalCount { get; set; }

    [Key(7)]
    public int GivePointAtGoal { get; set; }

    [Key(8)]
    public long CircleGoalCount { get; set; }

    [Key(9)]
    public int CircleGivePointAtGoal { get; set; }

    [Key(10)]
    public bool IsDefault { get; set; }

}
