// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class ComboRewardMaster
{
    [Key(0)]
    public global::Sirius.Protocol.Shared.ThingTypes ThingType { get; set; } = default!;

    [Key(1)]
    public long ThingId { get; set; }

    [Key(2)]
    public int ThingQuantity { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.MusicDifficulties Difficulty { get; set; } = default!;

    [Key(4)]
    public int ComboCountPercent { get; set; }

}
