// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("ComebackCampaignMaster")]
[MessagePackObject(false)]
public partial class ComebackCampaignMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int MissionActiveDays { get; set; }

    [Key(2)]
    public int JewelShopItemActiveDays { get; set; }

    [Key(3)]
    public int LoginBonusActiveDays { get; set; }

    [Key(4)]
    public int BuffCampaignActiveDays { get; set; }

}
