// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class ComicEpisodeMaster
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Order { get; set; }

    [Key(2)]
    public string Title { get; set; }

    [Key(3)]
    public string Body { get; set; }

    [Key(4)]
    public global::System.DateTime StartDate { get; set; } = default!;

}
