// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("ComicMaster")]
[MessagePackObject(false)]
public partial class ComicMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string GroupName { get; set; }

    [Key(2)]
    public ComicEpisodeMaster[] Episodes { get; set; } = default!;

}
