// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CompanyMaster")]
[MessagePackObject(false)]
public partial class CompanyMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.Companies Companies { get; set; } = default!;

    [Key(3)]
    public string Description { get; set; }

    [Key(4)]
    public bool IsOther { get; set; }

}
