// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("ConcertStageMaster")]
[MessagePackObject(false)]
public partial class ConcertStageMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ConcertMasterId { get; set; }

    [Key(2)]
    public long MusicMasterId { get; set; }

    [Key(3)]
    public int VocalVersion { get; set; }

    [Key(4)]
    public long SenseNotationMasterId { get; set; }

    [Key(5)]
    public global::Sirius.Protocol.Shared.Companies? RecommendedCompany { get; set; }

    [Key(6)]
    public int RecommendedLevel { get; set; }

    [Key(7)]
    public long ClearScore { get; set; }

    [Key(8)]
    public ConcertRewardMaster[] Rewards { get; set; } = default!;

}
