// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("ConcertMaster")]
[MessagePackObject(false)]
public partial class ConcertMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(2)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(3)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(4)]
    public string Name { get; set; }

    [Key(5)]
    public long EventMasterId { get; set; }

}
