// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("ConcoursPointRewardMaster")]
[MessagePackObject(false)]
public partial class ConcoursPointRewardMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ConcoursMasterId { get; set; }

    [Key(2)]
    public int RequiredPoint { get; set; }

    [Key(3)]
    public ConcoursPointRewardThingMaster[] Things { get; set; } = default!;

}
