// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class ConcoursPointMaster
{
    [Key(0)]
    public int TargetHighestRank { get; set; }

    [Key(1)]
    public int TargetLowestRank { get; set; }

    [Key(2)]
    public int Point { get; set; }

}
