// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CostumeMaster")]
[MessagePackObject(false)]
public partial class CostumeMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public int Order { get; set; }

    [Key(3)]
    public bool IsDefault { get; set; }

    [Key(4)]
    public long CostumeGroupMasterId { get; set; }

    [Key(5)]
    public string Description { get; set; }

}
