// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CostumeGroupMaster")]
[MessagePackObject(false)]
public partial class CostumeGroupMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(3)]
    public int Order { get; set; }

    [Key(4)]
    public long[] CostumeMasterIds { get; set; } = default!;

    [Key(5)]
    public long? CostumeWearableCharacterGroupMasterId { get; set; }

    [Key(6)]
    public int? PerformanceGroupId { get; set; }

    [Key(7)]
    public bool IsHairChange { get; set; }

    [Key(8)]
    public global::System.DateTime DisplayStartAt { get; set; } = default!;

    [Key(9)]
    public global::System.DateTime DisplayEndAt { get; set; } = default!;

}
