// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("CourseRankingRewardMaster")]
[MessagePackObject(false)]
public partial class CourseRankingRewardMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MusicCourseMasterId { get; set; }

    [Key(2)]
    public int TargetHighestRank { get; set; }

    [Key(3)]
    public int TargetLowestRank { get; set; }

    [Key(4)]
    public CourseRankingRewardThingMaster[] Rewards { get; set; } = default!;

}
