// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("DecorationMaster")]
[MessagePackObject(false)]
public partial class DecorationMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Order { get; set; }

    [Key(2)]
    public bool IsDefault { get; set; }

    [Key(3)]
    public string Name { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.DecorationCategories Category { get; set; } = default!;

    [Key(5)]
    public int WidhtPx { get; set; }

    [Key(6)]
    public int HeightPx { get; set; }

    [Key(7)]
    public int MinWidthPx { get; set; }

    [Key(8)]
    public int MaxWidthPx { get; set; }

}
