// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("DugongRunRewardMaster")]
[MessagePackObject(false)]
public partial class DugongRunRewardMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int RequiredClearCourseCount { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.ThingTypes ThingType { get; set; } = default!;

    [Key(3)]
    public long ThingId { get; set; }

    [Key(4)]
    public int ThingQuantity { get; set; }

    [Key(5)]
    public long DugongRunCourseGroupId { get; set; }

}
