// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("DugongRunCourseMaster")]
[MessagePackObject(false)]
public partial class DugongRunCourseMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long? EventMasterId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.DugongRunDifficultyTypes Difficulty { get; set; } = default!;

    [Key(3)]
    public long MusicMasterId { get; set; }

    [Key(4)]
    public string NotationPath { get; set; }

    [Key(5)]
    public int ScrollSpeed { get; set; }

    [Key(6)]
    public long DugongRunCourseGroupId { get; set; }

}
