// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class EffectTriggerMaster
{
    [Key(0)]
    public global::Sirius.Protocol.Shared.TriggerType Trigger { get; set; } = default!;

    [Key(1)]
    public long? Value { get; set; }

}
