// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class EffectDetailMaster
{
    [Key(0)]
    public int Level { get; set; }

    [Key(1)]
    public float Value { get; set; }

}
