// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("EffectMaster")]
[MessagePackObject(false)]
public partial class EffectMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.LiveEngine.EffectTypes Type { get; set; } = default!;

    [Key(2)]
    public global::Sirius.Protocol.Shared.EffectTargetRanges Range { get; set; } = default!;

    [Key(3)]
    public global::Sirius.Protocol.Shared.CalculationTypes CalculationType { get; set; } = default!;

    [Key(4)]
    public EffectDetailMaster[] Details { get; set; } = default!;

    [Key(5)]
    public EffectConditionMaster[] Conditions { get; set; } = default!;

    [Key(6)]
    public int DurationSecond { get; set; }

    [Key(7)]
    public EffectTriggerMaster[] Triggers { get; set; } = default!;

    [Key(8)]
    public global::Sirius.Protocol.Shared.FireTimingTypes FireTimingType { get; set; } = default!;

}
