// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class EffectOrderMaster
{
    [Key(0)]
    public int Order { get; set; }

    [Key(1)]
    public long EffectMasterId { get; set; }

}
