// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class EffectConditionMaster
{
    [Key(0)]
    public global::Sirius.Protocol.Shared.EffectConditions Condition { get; set; } = default!;

    [Key(1)]
    public long? Value { get; set; }

}
