// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("EffectTriggerCharacterBaseGroupMaster")]
[MessagePackObject(false)]
public partial class EffectTriggerCharacterBaseGroupMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long[] CharacterBaseMasterIds { get; set; } = default!;

}
