// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class EpisodeReleaseCondition
{
    [Key(0)]
    public global::Sirius.Protocol.Shared.EpisodeReleaseConditionTypes ConditionType { get; set; } = default!;

    [Key(1)]
    public long? Value1 { get; set; }

    [Key(2)]
    public long? Value2 { get; set; }

    [Key(3)]
    public long? Value3 { get; set; }

}
