// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("EpisodeMaster")]
[MessagePackObject(false)]
public partial class EpisodeMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryMasterId { get; set; }

    [IgnoreMember]
    public StoryMaster StoryMaster { get; set; } = default!;

    [Key(2)]
    public string Title { get; set; }

    [Key(3)]
    public int Order { get; set; }

    [Key(4)]
    public long EpisodeRewardPackageMasterId { get; set; }

    [Key(5)]
    public EpisodeReleaseCondition[] Conditions { get; set; } = default!;

    [Key(6)]
    public long? PreEpisodeMasterId { get; set; }

    [Key(7)]
    public global::System.DateTime? DisplayStartDate { get; set; }

    [Key(8)]
    public global::System.DateTime? DisplayEndDate { get; set; }

}
