// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class EventRankingRewardMaster
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int TargetHighestRank { get; set; }

    [Key(2)]
    public int TargetLowestRank { get; set; }

    [Key(3)]
    public EventRankingRewardThingMaster[] Rewards { get; set; } = default!;

}
