// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class EventBonusMaster
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.StoryEventBonusTypes BonusTargetType { get; set; } = default!;

    [Key(2)]
    public long BonusTargetId { get; set; }

}
