// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("EventBoxGachaBoxMaster")]
[MessagePackObject(false)]
public partial class EventBoxGachaBoxMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long EventBoxGachaMasterId { get; set; }

    [Key(2)]
    public int Order { get; set; }

    [Key(3)]
    public EventBoxGachaBoxThingMaster[] BoxThings { get; set; } = default!;

}
