// <auto-generated />
#nullable enable
using MessagePack;
namespace Sirius.Protocol.Shared.Models.Master;
[MasterMemory.MemoryTable("EventCampSupportPointRewardMaster")]
[MessagePackObject(false)]
public partial class EventCampSupportPointRewardMaster
{
    [MasterMemory.PrimaryKey, Key(0)] public long Id { get; set; }
    [Key(1)] public long EventMasterId { get; set; }
    [Key(2)] public long RequiredSupportPoint { get; set; }
    [Key(3)] public int Order { get; set; }
    [Key(4)] public long Camp1RewardId { get; set; }
    [Key(5)] public long Camp2RewardId { get; set; }
}
