// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("EventBoxGachaTextTemplateMaster")]
[MessagePackObject(false)]
public partial class EventBoxGachaTextTemplateMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Description { get; set; }

}
