// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("EventMaster")]
[MessagePackObject(false)]
public partial class EventMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.EventTypes EventType { get; set; } = default!;

    [Key(2)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(3)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(4)]
    public global::System.DateTime ForceEndDate { get; set; } = default!;

    [Key(5)]
    public string Name { get; set; }

    [Key(6)]
    public bool IsAsideLiveButton { get; set; }

    [Key(7)]
    public long? EventPointItemMasterId { get; set; }

    [Key(8)]
    public global::Sirius.Protocol.Shared.Attributes? BonusAttribute { get; set; }

    [Key(9)]
    public long? BonusCategoryMasterId10 { get; set; }

    [Key(10)]
    public long? BonusCategoryMasterId20 { get; set; }

    [Key(11)]
    public EventBonusMaster[] Bonuses { get; set; } = default!;

    [Key(12)]
    public EventPointRewardMaster[] PointRewards { get; set; } = default!;

    [Key(13)]
    public EventRankingRewardMaster[] RankingRewards { get; set; } = default!;

    [Key(14)]
    public long? ExchangeShopMasterId { get; set; }

    [Key(15)]
    public global::Sirius.Protocol.Shared.AsideLiveButtonTypes AsideLiveButtonType { get; set; } = default!;


    [Key(16)]
    public int? EventCampType { get; set; }

}
