// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class EventBoxGachaDetailMaster
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Order { get; set; }

    [Key(2)]
    public int PrizeCount { get; set; }

}
