// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("EventBoxGachaMaster")]
[MessagePackObject(false)]
public partial class EventBoxGachaMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public long EventMasterId { get; set; }

    [Key(3)]
    public long RequiredItemMasterId { get; set; }

    [Key(4)]
    public int RequiredQuantity { get; set; }

    [Key(5)]
    public EventBoxGachaDetailMaster[] Details { get; set; } = default!;

    [Key(6)]
    public long EventBoxGachaTextTemplateMasterId { get; set; }

}
