// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("ExchangeShopMaster")]
[MessagePackObject(false)]
public partial class ExchangeShopMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public bool IsDisplayRequiredHavingItem { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.ShopCategories Category { get; set; } = default!;

    [Key(3)]
    public string Name { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.ThingTypes DisplayThingType { get; set; } = default!;

    [Key(5)]
    public long? DisplayItemMasterId { get; set; }

    [IgnoreMember]
    public ItemMaster DisplayItemMaster { get; set; } = default!;

    [Key(6)]
    public string BannerPath { get; set; }

    [Key(7)]
    public global::System.DateTime? StartDate { get; set; }

    [Key(8)]
    public global::System.DateTime? EndDate { get; set; }

    [Key(9)]
    public global::System.DateTime LastRefreshedAt { get; set; } = default!;

    [Key(10)]
    public ExchangeShopThing[] Lineup { get; set; } = default!;


    [Key(11)]
    public int DisplayOrder { get; set; }

}
