// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class ExchangeShopThing
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ThingId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.ThingTypes ThingType { get; set; } = default!;

    [Key(3)]
    public int ThingQuantity { get; set; }

    [Key(4)]
    public int? ExchangeLimit { get; set; }

    [Key(5)]
    public int Order { get; set; }

    [Key(6)]
    public global::Sirius.Protocol.Shared.ShopReplaceTypes? ReplaceType { get; set; }

    [Key(7)]
    public bool IsDisplayLocked { get; set; }

    [Key(8)]
    public global::Sirius.Protocol.Shared.ShopUnlockTypes? UnlockType { get; set; }

    [Key(9)]
    public long? UnlockValue { get; set; }

    [Key(10)]
    public global::System.DateTime? StartDate { get; set; }

    [Key(11)]
    public global::System.DateTime? EndDate { get; set; }

    [Key(12)]
    public long RequiredItemMasterId { get; set; }

    [Key(13)]
    public int RequiredQuantity { get; set; }

}
