// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("FacialExpressionMaster")]
[MessagePackObject(false)]
public partial class FacialExpressionMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string EyeBrow { get; set; }

    [Key(2)]
    public string Eye { get; set; }

    [Key(3)]
    public string EyeBlink { get; set; }

    [Key(4)]
    public string Cheek { get; set; }

    [Key(5)]
    public string Mouth { get; set; }

}
