// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("FilmItemMaster")]
[MessagePackObject(false)]
public partial class FilmItemMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ItemMasterId { get; set; }

    [Key(2)]
    public long? TargetCharacterBaseMasterId { get; set; }

}
