// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class FriendInvitationMissionStageMaster
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int GoalCount { get; set; }

    [Key(2)]
    public int MissionStageOrder { get; set; }

    [Key(3)]
    public FriendInvitationMissionRewardMaster[] Rewards { get; set; } = default!;

}
