// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("FriendInvitationMissionMaster")]
[MessagePackObject(false)]
public partial class FriendInvitationMissionMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Description { get; set; }

    [Key(2)]
    public int Order { get; set; }

    [Key(3)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(4)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(5)]
    public global::Sirius.Protocol.Shared.JumpTypes JumpType { get; set; } = default!;

    [Key(6)]
    public long? JumpTargetId { get; set; }

    [Key(7)]
    public FriendInvitationMissionStageMaster[] Stages { get; set; } = default!;

}
