// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class GachaDetailMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long? RequiredTicketMItemId { get; set; }

    [Key(2)]
    public int? RequiredTicketQuantity { get; set; }

    [Key(3)]
    public int? FreeJewelAmount { get; set; }

    [Key(4)]
    public int? PaidJewelAmount { get; set; }

    [Key(5)]
    public bool IsFree { get; set; }

    [Key(6)]
    public int? DailyRollLimit { get; set; }

    [Key(7)]
    public int? OverallRollLimit { get; set; }

    [Key(8)]
    public int PrizeCount { get; set; }

    [Key(9)]
    public int FixedPrizeCount { get; set; }

    [Key(10)]
    public global::Sirius.Protocol.Shared.GachaButtonTypes ButtonType { get; set; } = default!;

    [Key(11)]
    public GachaDetailBonusThing[] DetailBonusThings { get; set; } = default!;

}
