// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("GachaMaster")]
[MessagePackObject(false)]
public partial class GachaMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.GachaCardTypes CardType { get; set; } = default!;

    [Key(3)]
    public global::Sirius.Protocol.Shared.GachaTypes GachaType { get; set; } = default!;

    [Key(4)]
    public long GachaTextTemplateMasterId { get; set; }

    [Key(5)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(6)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(7)]
    public GachaBonusThing[] BonusThings { get; set; } = default!;

    [Key(8)]
    public GachaDetailMaster[] GachaDetails { get; set; } = default!;

    [Key(9)]
    public GachaThing[] Things { get; set; } = default!;

    [Key(10)]
    public bool HasMovie { get; set; }

    [Key(11)]
    public long? StoryEventMasterId { get; set; }

    [Key(12)]
    public long AttentionGachaTextTemplateMasterId { get; set; }

    [Key(13)]
    public bool IsForceDisplay { get; set; }

    [Key(14)]
    public bool IsHideEndDate { get; set; }

    [Key(15)]
    public global::Sirius.Protocol.Shared.GachaUnlockTypes UnlockType { get; set; } = default!;

    [Key(16)]
    public long? UnlockValue { get; set; }

    [Key(17)]
    public string ExchangeShopBannerPath { get; set; }

    [Key(18)]
    public long Order { get; set; }

    [Key(19)]
    public global::Sirius.Protocol.Shared.GachaDisplayFooterConditions? DisplayFooterCondition { get; set; }

    [Key(20)]
    public global::Sirius.Protocol.Shared.GachaGroupTypes GroupType { get; set; } = default!;

    [Key(21)]
    public GachaRollBonus[] RollBonuses { get; set; } = default!;

    [Key(22)]
    public int? ReRollLimit { get; set; }


    [Key(23)]
    public string ExternalId { get; set; } = string.Empty;

}
