// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("GameHintMaster")]
[MessagePackObject(false)]
public partial class GameHintMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.PageCategories PageCategory { get; set; } = default!;

    [Key(2)]
    public int PageCount { get; set; }

}
