// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("GhostLiveMaster")]
[MessagePackObject(false)]
public partial class GhostLiveMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MusicMasterId { get; set; }

    [Key(2)]
    public int VocalVersion { get; set; }

    [Key(3)]
    public long SenseNotationMasterId { get; set; }

    [Key(4)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(5)]
    public global::System.DateTime EndDate { get; set; } = default!;

}
