// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class GradualMissionMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Days { get; set; }

    [Key(2)]
    public long[] MissionMasterIds { get; set; } = default!;

}
