// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("HomeBGMDetailMaster")]
[MessagePackObject(false)]
public partial class HomeBGMDetailMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long HomeBGMMasterId { get; set; }

    [Key(2)]
    public string BGMName { get; set; }

    [Key(3)]
    public string BGMPath { get; set; }

    [Key(4)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(5)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(6)]
    public long MusicMasterId { get; set; }

}
