// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("HomeCharacterVoicePeriodMaster")]
[MessagePackObject(false)]
public partial class HomeCharacterVoicePeriodMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int StartMonth { get; set; }

    [Key(2)]
    public int StartDay { get; set; }

    [Key(3)]
    public global::System.TimeSpan StartTime { get; set; } = default!;

    [Key(4)]
    public int EndMonth { get; set; }

    [Key(5)]
    public int EndDay { get; set; }

    [Key(6)]
    public global::System.TimeSpan EndTime { get; set; } = default!;

}
