// <auto-generated />
#nullable enable
using MessagePack;
namespace Sirius.Protocol.Shared.Models.Master;
[MasterMemory.MemoryTable("HomeSkinMaster")]
[MessagePackObject(false)]
public partial class HomeSkinMaster
{
    [MasterMemory.PrimaryKey, Key(0)] public long Id { get; set; }
    [Key(1)] public string Name { get; set; } = string.Empty;
    [Key(2)] public long CharacterBaseMasterId { get; set; }
    [Key(3)] public long? Reserved3 { get; set; }
    [Key(4)] public bool IsCharacterSkin { get; set; }
    [Key(5)] public bool IsDefault { get; set; }
    [Key(6)] public global::System.DateTime? StartDate { get; set; }
}
