// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("HomeBGMMaster")]
[MessagePackObject(false)]
public partial class HomeBGMMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.HomeBGMPriorityTypes Priority { get; set; } = default!;

    [Key(2)]
    public global::Sirius.Protocol.Shared.HomeBGMSelectionTypes SelectionType { get; set; } = default!;

    [Key(3)]
    public string DefaultBGMName { get; set; }

    [Key(4)]
    public string DefaultBGMPath { get; set; }

    [Key(5)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(6)]
    public global::System.DateTime EndDate { get; set; } = default!;

}
