// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("HomeCharacterVoiceMaster")]
[MessagePackObject(false)]
public partial class HomeCharacterVoiceMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [Key(2)]
    public string Text { get; set; }

    [Key(3)]
    public int Weight { get; set; }

    [Key(5)]
    public long? CharacterVoicePeriodMasterId { get; set; }

    [Key(7)]
    public bool IsPlayerBirthDateVoice { get; set; }

    [Key(8)]
    public string VoiceFileName1 { get; set; }

    [Key(9)]
    public string VoiceFileName2 { get; set; }

    [Key(10)]
    public string VoiceFileName3 { get; set; }

    [Key(11)]
    public string VoiceFileName4 { get; set; }

    [Key(13)]
    public float VoiceInterval1 { get; set; }

    [Key(14)]
    public float VoiceInterval2 { get; set; }

    [Key(15)]
    public float VoiceInterval3 { get; set; }

    [Key(16)]
    public string MouthMotionId1 { get; set; }

    [Key(17)]
    public string MouthMotionId2 { get; set; }

    [Key(18)]
    public string MouthMotionId3 { get; set; }

    [Key(19)]
    public string MouthMotionId4 { get; set; }

    [Key(20)]
    public string BodyMotionId1 { get; set; }

    [Key(21)]
    public string BodyMotionId2 { get; set; }

    [Key(22)]
    public string BodyMotionId3 { get; set; }

    [Key(23)]
    public string BodyMotionId4 { get; set; }

}
