// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("HomeBackgroundMaster")]
[MessagePackObject(false)]
public partial class HomeBackgroundMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public global::System.DateTime? StartDate { get; set; }

    [Key(3)]
    public global::System.DateTime? EndDate { get; set; }

}
