// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("HomePosterMaster")]
[MessagePackObject(false)]
public partial class HomePosterMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long PosterMasterId { get; set; }

    [Key(2)]
    public long? GachaMasterId { get; set; }

    [Key(3)]
    public global::System.DateTime DisplayStartDate { get; set; } = default!;

    [Key(4)]
    public global::System.DateTime DisplayEndDate { get; set; } = default!;

}
