// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("IconFrameMaster")]
[MessagePackObject(false)]
public partial class IconFrameMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public int Order { get; set; }

    [Key(3)]
    public string UnlockConditionText { get; set; }

    [Key(4)]
    public bool Hidden { get; set; }

    [Key(5)]
    public bool IsDefault { get; set; }

}
