// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("JewelShopItemMaster")]
[MessagePackObject(false)]
public partial class JewelShopItemMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Order { get; set; }

    [Key(2)]
    public string AppStoreProductId { get; set; }

    [Key(3)]
    public string GooglePlayProductId { get; set; }

    [Key(4)]
    public string Name { get; set; }

    [Key(5)]
    public string PackText { get; set; }

    [Key(6)]
    public long MJewelShopCategoryId { get; set; }

    [IgnoreMember]
    public JewelShopCategoryMaster MJewelShopCategoryMaster { get; set; } = default!;

    [Key(7)]
    public int DialogType { get; set; }

    [Key(8)]
    public global::Sirius.Protocol.Shared.ShopPurchaseTypes PurchaseType { get; set; } = default!;

    [Key(9)]
    public int? PurchaseValue { get; set; }

    [Key(10)]
    public bool SubscriptionFlag { get; set; }

    [Key(11)]
    public int? GivePaidJewel { get; set; }

    [Key(12)]
    public global::Sirius.Protocol.Shared.ShopReplaceTypes? ReplaceTypes { get; set; }

    [Key(13)]
    public int? ReplaceValue { get; set; }

    [Key(14)]
    public int? PurchaseLimit { get; set; }

    [Key(15)]
    public int? ExpiredDay { get; set; }

    [Key(16)]
    public string CanPurchaseDayOfWeek { get; set; }

    [Key(17)]
    public bool IsBuyNotDisplay { get; set; }

    [Key(18)]
    public global::Sirius.Protocol.Shared.SaleTypes? SaleType { get; set; }

    [Key(19)]
    public int? SaleValue { get; set; }

    [Key(20)]
    public bool IsDisplayLocking { get; set; }

    [Key(21)]
    public global::Sirius.Protocol.Shared.JewelShopUnlockTypes? UnlockType { get; set; }

    [Key(22)]
    public long? UnlockValue { get; set; }

    [Key(23)]
    public global::System.DateTime? StartDate { get; set; }

    [Key(24)]
    public global::System.DateTime? EndDate { get; set; }

    [Key(25)]
    public JewelShopThing[] Lineup { get; set; } = default!;

    [Key(26)]
    public global::Sirius.Protocol.Shared.ShopItemTypes ShopItemType { get; set; } = default!;

    [Key(27)]
    public long? ShopItemValue { get; set; }

    [Key(28)]
    public long? ComebackCampaignMasterId { get; set; }

    [Key(29)]
    public string ItemIconBodyImagePath { get; set; }

    [Key(30)]
    public string ItemIconDetailImagePath { get; set; }

    [Key(31)]
    public string ItemIconBadgeImagePath { get; set; }

}
