// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("JewelShopCategoryMaster")]
[MessagePackObject(false)]
public partial class JewelShopCategoryMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public int LayoutType { get; set; }

    [Key(3)]
    public int? IsDisplayLocking { get; set; }

    [Key(4)]
    public string BannerPath { get; set; }

    [Key(5)]
    public int Order { get; set; }

}
