// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class JewelShopThing
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MJewelShopItemId { get; set; }

    [IgnoreMember]
    public JewelShopItemMaster MJewelShopItemMaster { get; set; } = default!;

    [Key(2)]
    public long ThingId { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.ThingTypes ThingType { get; set; } = default!;

    [Key(4)]
    public int ThingQuantity { get; set; }

}
