// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class LeaderSenseDetailConditionMaster
{
    [Key(0)]
    public long? CategoryMasterId1 { get; set; }

    [Key(1)]
    public long? CategoryMasterId2 { get; set; }

    [Key(2)]
    public long? CategoryMasterId3 { get; set; }

    [Key(3)]
    public long? CategoryMasterId4 { get; set; }

    [Key(4)]
    public long? CategoryMasterId5 { get; set; }

}
