// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class LeaderSenseDetailMaster
{
    [Key(0)]
    public long EffectMasterId { get; set; }

    [Key(1)]
    public LeaderSenseDetailConditionMaster[] Conditions { get; set; } = default!;

}
