// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class LeagueClassMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int? UpUserAmount { get; set; }

    [Key(2)]
    public int? KeepUserAmount { get; set; }

    [Key(3)]
    public bool IsForceDownNotPlayingLeague { get; set; }

    [Key(4)]
    public long? UpRewardPackageMasterId { get; set; }

    [Key(5)]
    public long? KeepRewardPackageMasterId { get; set; }

    [Key(6)]
    public long? DownRewardPackageMasterId { get; set; }

    [Key(7)]
    public long? FirstAchieveRewardPackageMasterId { get; set; }

    [Key(8)]
    public long? NameplateMasterId { get; set; }

    [Key(9)]
    public global::Sirius.Protocol.Shared.LeagueClassTypes ClassType { get; set; } = default!;

    [Key(10)]
    public long LeagueClassGroupMasterId { get; set; }

}
