// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class LeagueAllClassGlobalRankingRewardPackageMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long LeagueMasterId { get; set; }

    [Key(2)]
    public LeagueAllClassGlobalRankingRewardThingMaster[] Rewards { get; set; } = default!;

    [Key(3)]
    public int MinRank { get; set; }

    [Key(4)]
    public int MaxRank { get; set; }

    [Key(5)]
    public string RewardTitle { get; set; }

}
