// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("LeagueMaster")]
[MessagePackObject(false)]
public partial class LeagueMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MusicMasterId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.MusicDifficulties MaxDifficulty { get; set; } = default!;

    [Key(3)]
    public global::System.DateTime DisplayStartAt { get; set; } = default!;

    [Key(4)]
    public global::System.DateTime CountingStartAt { get; set; } = default!;

    [Key(5)]
    public global::System.DateTime DisplayEndAt { get; set; } = default!;

    [Key(6)]
    public long LeagueClassGroupMasterId { get; set; }

    [Key(7)]
    public long SenseNotationMasterId { get; set; }

    [Key(8)]
    public int VocalVersion { get; set; }

    [Key(9)]
    public long LeagueSeasonMasterId { get; set; }

}
