// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("LeagueGroupRankingRewardPackageMaster")]
[MessagePackObject(false)]
public partial class LeagueGroupRankingRewardPackageMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public LeagueGroupRankingRewardThingMaster[] Rewards { get; set; } = default!;

    [Key(2)]
    public global::Sirius.Protocol.Shared.LeagueClassTypes ClassType { get; set; } = default!;

    [Key(3)]
    public int MinRank { get; set; }

    [Key(4)]
    public int MaxRank { get; set; }

    [Key(5)]
    public string RewardTitle { get; set; }

}
