// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("LightLoadSplitEffectMaster")]
[MessagePackObject(false)]
public partial class LightLoadSplitEffectMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int BaseEffect { get; set; }

    [Key(2)]
    public int LightLoadEffect { get; set; }

}
