// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("LiveDropFrameGroupMaster")]
[MessagePackObject(false)]
public partial class LiveDropFrameGroupMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public LiveDropFrameMaster[] DropFrames { get; set; } = default!;

}
