// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("LiveMaster")]
[MessagePackObject(false)]
public partial class LiveMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.MusicDifficulties Difficulty { get; set; } = default!;

    [Key(2)]
    public long MusicMasterId { get; set; }

    [Key(3)]
    public int Level { get; set; }

    [Key(4)]
    public int NoteCount { get; set; }

    [Key(5)]
    public global::Sirius.Protocol.Shared.LiveUnlockConditionTypes UnlockCondition { get; set; } = default!;

    [Key(6)]
    public long? UnlockValue { get; set; }

    [Key(7)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(8)]
    public global::System.DateTime EndDate { get; set; } = default!;

}
