// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class LiveDropFrameMaster
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long LiveDropFrameGroupMasterId { get; set; }

    [Key(2)]
    public int Order { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.ProbabilityChangeTypes ChangeType { get; set; } = default!;

    [Key(4)]
    public global::Sirius.Protocol.Shared.FrameLotConditionTypes FrameLotCondition { get; set; } = default!;

    [Key(5)]
    public bool UnaffectedIncreaseEffect { get; set; }

    [Key(6)]
    public LiveDropThingMaster[] Rewards { get; set; } = default!;

    [Key(7)]
    public int? FrameLotConditionValue { get; set; }

    [Key(8)]
    public global::System.DateTime? StartDate { get; set; }

    [Key(9)]
    public global::System.DateTime? EndDate { get; set; }

}
