// <auto-generated />
#nullable enable
using MessagePack;
namespace Sirius.Protocol.Shared.Models.Master;
[MasterMemory.MemoryTable("LoginBonusSpineCostumeMaster")]
[MessagePackObject(false)]
public partial class LoginBonusSpineCostumeMaster
{
    [MasterMemory.PrimaryKey, Key(0)] public long Id { get; set; }
    [Key(1)] public long CostumeMasterId { get; set; }
    [Key(2)] public long CharacterBaseMasterId { get; set; }
    [Key(3)] public long SpineCharacterId { get; set; }
    [Key(4)] public global::System.DateTime StartDate { get; set; }
}
