// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("LoopMotionMaster")]
[MessagePackObject(false)]
public partial class LoopMotionMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string TargetCharacterBaseId { get; set; }

    [Key(2)]
    public float LoopSpeed { get; set; }

    [Key(3)]
    public int Height { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.SpineBodySizeTypes Size { get; set; } = default!;

}
