// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("MarketFrameThingMaster")]
[MessagePackObject(false)]
public partial class MarketFrameThingMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ThingId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.ThingTypes ThingType { get; set; } = default!;

    [Key(3)]
    public int ThingQuantity { get; set; }

    [Key(6)]
    public global::Sirius.Protocol.Shared.ThingTypes RequiredThingType { get; set; } = default!;

    [Key(7)]
    public long RequiredThingId { get; set; }

    [Key(8)]
    public int RequiredThingQuantity { get; set; }

    [Key(9)]
    public global::Sirius.Protocol.Shared.MarketDisplayTypes DisplayType { get; set; } = default!;

}
