// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class MissionStageMaster
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int MissionStageOrder { get; set; }

    [Key(2)]
    public long StageGoalValue { get; set; }

    [Key(3)]
    public global::System.DateTime? StartDate { get; set; }

    [Key(4)]
    public MissionRewardMaster[] Rewards { get; set; } = default!;

}
