// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("MissionMaster")]
[MessagePackObject(false)]
public partial class MissionMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.MissionCategories MissionCategory { get; set; } = default!;

    [Key(2)]
    public int MissionViewOrder { get; set; }

    [Key(3)]
    public string Title { get; set; }

    [Key(4)]
    public string Description { get; set; }

    [Key(14)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(15)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(11)]
    public long? EventMasterId { get; set; }

    [Key(12)]
    public global::Sirius.Protocol.Shared.JumpTypes JumpType { get; set; } = default!;

    [Key(13)]
    public long? JumpTargetId { get; set; }

    [Key(16)]
    public MissionStageMaster[] Stages { get; set; } = default!;

    [Key(17)]
    public long? ComebackCampaignMasterId { get; set; }

}
