// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("MissionPassLoopRewardMaster")]
[MessagePackObject(false)]
public partial class MissionPassLoopRewardMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Phase { get; set; }

    [Key(2)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(3)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(4)]
    public MissionPassLoopRewardThingMaster[] Rewards { get; set; } = default!;

}
