// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("MissionPassLoopRewardThingMaster")]
[MessagePackObject(false)]
public partial class MissionPassLoopRewardThingMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MissionPassLoopRewardMasterId { get; set; }

    [Key(2)]
    public long ThingId { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.ThingTypes ThingType { get; set; } = default!;

    [Key(4)]
    public int ThingQuantity { get; set; }

    [Key(5)]
    public bool IsSp { get; set; }

}
