// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("MissionPassDetailMaster")]
[MessagePackObject(false)]
public partial class MissionPassDetailMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Phase { get; set; }

    [Key(2)]
    public long? MissionPassMasterId { get; set; }

    [Key(3)]
    public int ClearPoint { get; set; }

    [Key(4)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(5)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(6)]
    public MissionPassRewardThing[] Rewards { get; set; } = default!;

}
