// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("MissionPassMaster")]
[MessagePackObject(false)]
public partial class MissionPassMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ItemMasterId { get; set; }

    [Key(2)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(3)]
    public global::System.DateTime EndDate { get; set; } = default!;

}
