// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("MultiLiveScheduleMaster")]
[MessagePackObject(false)]
public partial class MultiLiveScheduleMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(2)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(3)]
    public long LiveSettingMasterId1 { get; set; }

    [Key(4)]
    public long LiveSettingMasterId2 { get; set; }

    [Key(5)]
    public global::System.DateTime? AdditionalEndDate { get; set; }

    [Key(6)]
    public global::Sirius.Protocol.Shared.LiveScheduleEndDateDisplayType EndDateDisplayType1 { get; set; } = default!;

    [Key(7)]
    public global::Sirius.Protocol.Shared.LiveScheduleEndDateDisplayType EndDateDisplayType2 { get; set; } = default!;

}
