// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("MusicMaster")]
[MessagePackObject(false)]
public partial class MusicMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(4)]
    public long RewardRuleMasterId { get; set; }

    [Key(5)]
    public string PronounceName { get; set; }

    [Key(6)]
    public string LyricWriter { get; set; }

    [Key(7)]
    public string Composer { get; set; }

    [Key(8)]
    public string Arranger { get; set; }

    [Key(10)]
    public string UnlockText { get; set; }

    [Key(11)]
    public bool IsLongVersion { get; set; }

    [Key(12)]
    public global::System.DateTime? ReleasedAt { get; set; }

    [Key(13)]
    public int StaminaConsumption { get; set; }

    [Key(14)]
    public int MusicTimeSecond { get; set; }

    [Key(15)]
    public bool Invisible { get; set; }

    [Key(17)]
    public float SampleStartSeconds { get; set; }

    [Key(18)]
    public float SampleEndSeconds { get; set; }

    [Key(19)]
    public float DelaySeconds { get; set; }

    [Key(20)]
    public MusicVocalVersionMaster[] VocalVersions { get; set; } = default!;

    [Key(21)]
    public global::Sirius.Protocol.Shared.MusicUnlockConditionTypes UnlockConditionType { get; set; } = default!;

    [Key(22)]
    public long? UnlockConditionValue { get; set; }

    [Key(23)]
    public global::Sirius.Protocol.Shared.MusicVideoTypes MusicVideoType { get; set; } = default!;

    [Key(24)]
    public global::Sirius.Protocol.Shared.MusicCoverTypes MusicCoverType { get; set; } = default!;


    [Key(25)]
    public long? Reserved25 { get; set; }


    [Key(26)]
    public long? Reserved26 { get; set; }


    [Key(27)]
    public long? Reserved27 { get; set; }

}
