// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class MusicVideoDefaultCostumeMaster
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [Key(2)]
    public long CostumeMasterId { get; set; }

}
