// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("MusicCourseRewardGroupMaster")]
[MessagePackObject(false)]
public partial class MusicCourseRewardGroupMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MusicCourseMasterId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.MusicCourseCertificationGrade RequiredCertificationGrade { get; set; } = default!;

    [Key(3)]
    public MusicCourseRewardThing[] Rewards { get; set; } = default!;

}
