// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("MusicVocalVersionMaster")]
[MessagePackObject(false)]
public partial class MusicVocalVersionMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MusicMasterId { get; set; }

    [Key(2)]
    public int VocalVersion { get; set; }

    [Key(3)]
    public string Singer { get; set; }

    [Key(4)]
    public string Name { get; set; }

    [Key(5)]
    public int MusicTimeSecond { get; set; }

    [Key(6)]
    public float SampleStartSeconds { get; set; }

    [Key(7)]
    public float SampleEndSeconds { get; set; }

    [Key(8)]
    public global::Sirius.Protocol.Shared.MusicVideoTypes MusicVideoType { get; set; } = default!;

    [Key(9)]
    public long[] Characters { get; set; } = default!;

}
