// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("MusicVideoMaster")]
[MessagePackObject(false)]
public partial class MusicVideoMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MusicMasterId { get; set; }

    [Key(2)]
    public int MemberAmount { get; set; }

    [Key(3)]
    public global::System.DateTime DisplayStartAt { get; set; } = default!;

    [Key(4)]
    public global::System.DateTime? DisplayEndAt { get; set; }

    [Key(5)]
    public MusicVideoOriginalCharacterMaster[] Characters { get; set; } = default!;

    [Key(6)]
    public float DelaySeconds { get; set; }

    [Key(7)]
    public float MovieDelaySeconds { get; set; }

    [Key(8)]
    public long? MusicVideoDefaultCostumeGroupMasterId { get; set; }

    [Key(9)]
    public bool IsFixedMember { get; set; }

    [Key(10)]
    public int Order { get; set; }

}
