// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class MusicCourseDetailMaster
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int SetListNumber { get; set; }

    [Key(2)]
    public long? LiveMasterId { get; set; }

    [Key(3)]
    public int VocalVersion { get; set; }


    [Key(4)]
    public int? Reserved4 { get; set; }


    [Key(5)]
    public int? Reserved5 { get; set; }


    [Key(6)]
    public int? Reserved6 { get; set; }

}
