// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("MusicVideoDefaultCostumeGroupMaster")]
[MessagePackObject(false)]
public partial class MusicVideoDefaultCostumeGroupMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public MusicVideoDefaultCostumeMaster[] DefaultCostumes { get; set; } = default!;

}
