// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("NameColorMaster")]
[MessagePackObject(false)]
public partial class NameColorMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(3)]
    public int Order { get; set; }

    [Key(4)]
    public bool Hidden { get; set; }

    [Key(5)]
    public bool IsDefault { get; set; }

    [Key(6)]
    public string UnlockText { get; set; }

}
