// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class NameplateDetailMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Obsolete]
    [Key(2)]
    public global::Sirius.Protocol.Shared.LeagueClassTypes ClassType { get; set; } = default!;

    [Key(3)]
    public int EnrollCount { get; set; }

    [Key(4)]
    public long? ChangeValue1 { get; set; }

    [Key(5)]
    public long? ChangeValue2 { get; set; }

    [Key(6)]
    public int Priority { get; set; }

}
