// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("NameplateMaster")]
[MessagePackObject(false)]
public partial class NameplateMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(3)]
    public int Order { get; set; }

    [Key(4)]
    public bool Hidden { get; set; }

    [Key(5)]
    public bool IsDefault { get; set; }

    [Key(6)]
    public NameplateDetailMaster[] Details { get; set; } = default!;

    [Key(7)]
    public string UnlockText { get; set; }

    [Key(8)]
    public global::Sirius.Protocol.Shared.NamePlateChangeTypes ChangeType { get; set; } = default!;

    [Key(9)]
    public long? ChangeValue1 { get; set; }

    [Key(10)]
    public long? ChangeValue2 { get; set; }

}
