// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PermanentMarketThingMaster")]
[MessagePackObject(false)]
public partial class PermanentMarketThingMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ThingId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.ThingTypes ThingType { get; set; } = default!;

    [Key(3)]
    public int ThingQuantity { get; set; }

    [Key(4)]
    public int? ExchangeLimit { get; set; }

    [Key(5)]
    public int Order { get; set; }

    [Key(6)]
    public global::Sirius.Protocol.Shared.ShopUnlockTypes? UnlockType { get; set; }

    [Key(7)]
    public long? UnlockValue { get; set; }

    [Key(8)]
    public global::System.DateTime? StartDate { get; set; }

    [Key(9)]
    public global::System.DateTime? EndDate { get; set; }

    [Key(11)]
    public global::Sirius.Protocol.Shared.ThingTypes RequiredThingType { get; set; } = default!;

    [Key(12)]
    public long RequiredThingId { get; set; }

    [Key(13)]
    public int RequiredThingQuantity { get; set; }

}
