// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PhotoEffectTypeGroupMaster")]
[MessagePackObject(false)]
public partial class PhotoEffectTypeGroupMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int PhotoEffectMaxVariety { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(3)]
    public bool CanUseItem { get; set; }

}
