// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PhotoLevelUpItemGroupMaster")]
[MessagePackObject(false)]
public partial class PhotoLevelUpItemGroupMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.PhotoRarities Rarity { get; set; } = default!;

    [Key(2)]
    public int BaseLevel { get; set; }

    [Key(3)]
    public int RequiredCoin { get; set; }

    [Key(4)]
    public PhotoLevelUpItemMaster[] Items { get; set; } = default!;

}
