// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PhotoEffectMaster")]
[MessagePackObject(false)]
public partial class PhotoEffectMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(3)]
    public long EffectMasterId { get; set; }

    [Key(4)]
    public int? Variety { get; set; }

    [Key(5)]
    public long? PhotoEffectTypeGroupMasterId { get; set; }

    [Key(6)]
    public long PhotoEffectGroupMasterId { get; set; }

}
