// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class PhotoLevelUpItemMaster
{
    [Key(0)]
    public long ItemMasterId { get; set; }

    [Key(1)]
    public int RequiredQuantity { get; set; }

}
