// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PhotoEffectChangeItemMaster")]
[MessagePackObject(false)]
public partial class PhotoEffectChangeItemMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ItemMasterId { get; set; }

    [Key(2)]
    public long PhotoEffectTypeGroupMasterId { get; set; }

    [Key(3)]
    public int RequiredQuantity { get; set; }

}
