// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PhotoEffectVarietyChangeDetailMaster")]
[MessagePackObject(false)]
public partial class PhotoEffectVarietyChangeDetailMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int BeforePhotoEffectMaxVariety { get; set; }

    [Key(2)]
    public int AfterPhotoEffectMaxVariety { get; set; }

    [Key(3)]
    public int BeforeVariety { get; set; }

    [Key(4)]
    public int AfterVariety { get; set; }

}
