// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PickupSelectionGachaMaster")]
[MessagePackObject(false)]
public partial class PickupSelectionGachaMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long GachaMasterId { get; set; }

    [Key(2)]
    public int MinSelectCount { get; set; }

    [Key(3)]
    public int MaxSelectCount { get; set; }

    [Key(4)]
    public bool FixedPrizePickupOnly { get; set; }

}
