// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PickupCharacterMissionDetailGroupMaster")]
[MessagePackObject(false)]
public partial class PickupCharacterMissionDetailGroupMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public PickupCharacterMissionDetailMaster[] Details { get; set; } = default!;

}
