// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PickupCharacterMissionDetailMaster")]
[MessagePackObject(false)]
public partial class PickupCharacterMissionDetailMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Order { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.PickupCharacterMissionCheckCondition CheckCondition { get; set; } = default!;

    [Key(3)]
    public string Description { get; set; }

    [Key(4)]
    public int GoalValue { get; set; }

    [Key(5)]
    public PickupCharacterMissionDetailRewardMaster[] Rewards { get; set; } = default!;

}
