// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PlayerRankMaster")]
[MessagePackObject(false)]
public partial class PlayerRankMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public int Rank { get; set; }

    [Key(1)]
    public int PointToLevelUp { get; set; }

    [Key(2)]
    public int MaxStamina { get; set; }

    [Key(4)]
    public bool IsReleasedRank { get; set; }

    [Key(5)]
    public long? PlayerRankCapMasterId { get; set; }

}
