// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PlayerRankCapMaster")]
[MessagePackObject(false)]
public partial class PlayerRankCapMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Coin { get; set; }

    [Key(2)]
    public PlayerRankCapDetailMaster[] Details { get; set; } = default!;

}
