// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PosterReleaseItemGroupMaster")]
[MessagePackObject(false)]
public partial class PosterReleaseItemGroupMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public PosterReleaseItemMaster[] Items { get; set; } = default!;

    [Key(2)]
    public bool ItemConsumeApplyFlag { get; set; }

}
