// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PosterMaster")]
[MessagePackObject(false)]
public partial class PosterMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public int? OrganizeRestrictGroupId { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.PossessionRarities Rarity { get; set; } = default!;

    [Key(5)]
    public long LevelPatternGroupMasterId { get; set; }

    [Key(6)]
    public float? SubTitlePositionX1 { get; set; }

    [Key(7)]
    public float? SubTitlePositionY1 { get; set; }

    [Key(8)]
    public float? SubTitlePositionX2 { get; set; }

    [Key(9)]
    public float? SubTitlePositionY2 { get; set; }

    [Key(10)]
    public float? SubTitlePositionX3 { get; set; }

    [Key(11)]
    public float? SubTitlePositionY3 { get; set; }

    [Key(12)]
    public long ReleaseItemGroupId { get; set; }

    [Key(15)]
    public string PronounceName { get; set; }

    [Key(16)]
    public PosterCostumeMaster[] Costumes { get; set; } = default!;

    [Key(17)]
    public long[] AppearanceCharacterBaseMasterIds { get; set; } = default!;

    [Key(18)]
    public bool IsRestrictItemBreakThrough { get; set; }

    [Key(19)]
    public global::System.DateTime DisplayStartAt { get; set; } = default!;

    [Key(20)]
    public global::System.DateTime DisplayEndAt { get; set; } = default!;

    [Key(21)]
    public string UnlockText { get; set; }

    [Key(22)]
    public global::Sirius.Protocol.Shared.PosterOrientation Orientation { get; set; } = default!;

    [Key(23)]
    public global::Sirius.Protocol.Shared.PosterSubTitleDisplayConditions SubTitleDisplayCondition { get; set; } = default!;

    [Key(24)]
    public int? SubTitleDisplayConditionValue { get; set; }

    [Key(25)]
    public int? PosterBreakthroughMaxPhase { get; set; }

    [Key(26)]
    public global::System.DateTime? PosterBreakthroughMaxPhaseReleaseDate { get; set; }


    [Key(27)]
    public int? Reserved27 { get; set; }


    [Key(28)]
    public int? Reserved28 { get; set; }


    [Key(29)]
    public float? Reserved29 { get; set; }


    [Key(30)]
    public float? Reserved30 { get; set; }


    [Key(31)]
    public int? Reserved31 { get; set; }


    [Key(32)]
    public int? Reserved32 { get; set; }


    [Key(33)]
    public int? Reserved33 { get; set; }


    [Key(34)]
    public int? Reserved34 { get; set; }


    [Key(35)]
    public int? Reserved35 { get; set; }


    [Key(36)]
    public int? Reserved36 { get; set; }


    [Key(37)]
    public int? Reserved37 { get; set; }

}
