// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PosterStoryMaster")]
[MessagePackObject(false)]
public partial class PosterStoryMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long PosterMasterId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.PosterEpisodeTypes EpisodeType { get; set; } = default!;

    [Key(3)]
    public long? CharacterBaseMasterId { get; set; }

    [Key(4)]
    public string Description { get; set; }

    [Key(5)]
    public int Order { get; set; }

    [Key(6)]
    public long? CharacterIconId { get; set; }

    [Key(7)]
    public string CharacterName { get; set; }

}
