// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class PosterCostumeMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public int Phase { get; set; }

    [Key(1)]
    public long? CostumeMasterId { get; set; }

    [Key(2)]
    public long? ItemMasterId { get; set; }

    [Key(3)]
    public int Quantity { get; set; }


    [Key(4)]
    public long? Reserved4 { get; set; }

}
