// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("PosterAbilityMaster")]
[MessagePackObject(false)]
public partial class PosterAbilityMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(3)]
    public long PosterMasterId { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.PosterEffectTypes Type { get; set; } = default!;

    [Key(6)]
    public int FrameNumber { get; set; }

    [Key(7)]
    public int ReleaseLevelAt { get; set; }

    [Key(8)]
    public bool Hidden { get; set; }

    [Key(9)]
    public BranchMaster[] Branches { get; set; } = default!;

    [Key(10)]
    public global::Sirius.Protocol.Shared.BranchConditionType BranchConditionType1 { get; set; } = default!;

    [Key(11)]
    public long? ConditionValue1 { get; set; }

    [Key(12)]
    public global::Sirius.Protocol.Shared.BranchConditionType BranchConditionType2 { get; set; } = default!;

    [Key(13)]
    public long? ConditionValue2 { get; set; }

}
