// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class PosterLevelPatternMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long LevelPatternGroupId { get; set; }

    [Key(2)]
    public int Level { get; set; }

    [Key(3)]
    public long ItemMasterId { get; set; }

    [Key(4)]
    public int Quantity { get; set; }

}
