// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class PosterCharacterMaster
{
    [Key(2)]
    public global::Sirius.Protocol.Shared.PosterEpisodeTypes EpisodeType { get; set; } = default!;

    [Key(3)]
    public long? CharacterBaseMasterId { get; set; }

    [Key(4)]
    public string Description { get; set; }

}
