// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("ResultVoiceMaster")]
[MessagePackObject(false)]
public partial class ResultVoiceMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [Key(2)]
    public int Order { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.ResultVoiceConditionTypes ConditionType { get; set; } = default!;

    [Key(4)]
    public string VoiceAssetId { get; set; }

    [Key(5)]
    public string Motion { get; set; }

}
