// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("RouletteMaster")]
[MessagePackObject(false)]
public partial class RouletteMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long RouletteEventMasterId { get; set; }

    [Key(2)]
    public int Order { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.RouletteTypes RouletteType { get; set; } = default!;

    [Key(4)]
    public long RouletteTicketItemMasterId { get; set; }

    [Key(5)]
    public int RequiredTicketQuantity { get; set; }

    [Key(6)]
    public string RouletteImagePath { get; set; }

    [Key(7)]
    public RoulettePrizeMaster[] Prizes { get; set; } = default!;

    [Key(8)]
    public RouletteRollRewardMaster[] RollRewards { get; set; } = default!;

    [Key(9)]
    public string Name { get; set; }

}
