// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("RoulettePrizeMaster")]
[MessagePackObject(false)]
public partial class RoulettePrizeMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Slot { get; set; }

    [Key(2)]
    public int? AcquirePointQuantity { get; set; }

    [Key(3)]
    public RoulettePrizeThingMaster AcquirePrizeThing { get; set; } = default!;

}
