// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class RouletteRollRewardMaster
{
    [Key(0)]
    public int RollCount { get; set; }

    [Key(1)]
    public RouletteRollRewardThing[] Rewards { get; set; } = default!;

}
