// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("SceneCameraMaster")]
[MessagePackObject(false)]
public partial class SceneCameraMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int StartPositionX { get; set; }

    [Key(2)]
    public int StartPositionY { get; set; }

    [Key(3)]
    public int StartZoomRatio { get; set; }

    [Key(4)]
    public int EndPositionX { get; set; }

    [Key(5)]
    public int EndPositionY { get; set; }

    [Key(6)]
    public int EndZoomRatio { get; set; }

    [Key(7)]
    public int CameraMoveTurnaroundTimeSeconds { get; set; }

}
