// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class SenseNotationBuffMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.SenseNotationBuffTypes Type { get; set; } = default!;

    [Key(2)]
    public long? TargetValue { get; set; }

    [Key(3)]
    public int BuffValue { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.SenseNotationStatusTypes StatusType { get; set; } = default!;

}
