// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("SenseNotationMaster")]
[MessagePackObject(false)]
public partial class SenseNotationMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public SenseNotationDetailMaster[] Details { get; set; } = default!;

    [Key(2)]
    public SenseNotationBuffMaster[] Buffs { get; set; } = default!;

}
