// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("SensePerformanceMaster")]
[MessagePackObject(false)]
public partial class SensePerformanceMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int LabelType { get; set; }

    [Key(2)]
    public int? PerformanceGroup { get; set; }

    [Key(3)]
    public SensePerformanceCharacterMaster[] Characters { get; set; } = default!;

}
