// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class SensePerformanceCharacterMaster
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [Key(2)]
    public long SensePerformanceMasterId { get; set; }

    [Key(3)]
    public string ExpressId { get; set; }

}
