// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("SpecialEventMaster")]
[MessagePackObject(false)]
public partial class SpecialEventMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public EventMaster EventMaster { get; set; } = default!;

    [Key(2)]
    public string EventName { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.SpecialEventCategoryTypes CategoryType { get; set; } = default!;

    [Key(4)]
    public SpecialEventLayout[] Layouts { get; set; } = default!;

    [Key(5)]
    public int GameHintPageCount { get; set; }

}
