// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("SpecialEpisodeMaster")]
[MessagePackObject(false)]
public partial class SpecialEpisodeMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryMasterId { get; set; }

    [Key(2)]
    public string Title { get; set; }

    [Key(3)]
    public long? RequiredReadEpisodeMasterId { get; set; }

}
