// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("SpecialStoryMaster")]
[MessagePackObject(false)]
public partial class SpecialStoryMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryMasterId { get; set; }

    [Key(2)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(3)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(4)]
    public global::Sirius.Protocol.Shared.EventStoryListFlags EventStoryListFlags { get; set; } = default!;

    [Key(5)]
    public string Title { get; set; }

    [Key(6)]
    public int Order { get; set; }

}
