// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class SpecialEventLayout
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.CustomLayoutUITypes UIType { get; set; } = default!;

    [Key(2)]
    public string UIValue { get; set; }

    [Key(3)]
    public int AnchorXPercent { get; set; }

    [Key(4)]
    public int AnchorYPercent { get; set; }

    [Key(5)]
    public float PositionX { get; set; }

    [Key(6)]
    public float PositionY { get; set; }

    [Key(7)]
    public float SizeX { get; set; }

    [Key(8)]
    public float SizeY { get; set; }

    [Key(9)]
    public float ScaleX { get; set; }

    [Key(10)]
    public float ScaleY { get; set; }

    [Key(11)]
    public int Layer { get; set; }

    [Key(12)]
    public global::Sirius.Protocol.Shared.CustomLayoutActionTypes ActionType { get; set; } = default!;

    [Key(13)]
    public string ActionValue { get; set; }

    [Key(14)]
    public global::Sirius.Protocol.Shared.JumpTypes JumpType { get; set; } = default!;

    [Key(15)]
    public string JumpValue { get; set; }

    [Key(16)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(17)]
    public global::System.DateTime EndDate { get; set; } = default!;

}
