// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("SplashMaster")]
[MessagePackObject(false)]
public partial class SplashMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Order { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.SplashTypes SplashType { get; set; } = default!;

    [Key(3)]
    public string SplashValue { get; set; }

    [Key(4)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(5)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(6)]
    public global::Sirius.Protocol.Shared.SplashAdditionalValueTypes AdditionalSplashValue0 { get; set; } = default!;

    [Key(7)]
    public global::Sirius.Protocol.Shared.SplashAdditionalValueTypes AdditionalSplashValue1 { get; set; } = default!;

    [Key(8)]
    public global::Sirius.Protocol.Shared.SplashUnlockConditionTypes UnlockCondition { get; set; } = default!;

    [Key(9)]
    public long? UnlockConditionValue { get; set; }

}
