// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("SpotConversationMaster")]
[MessagePackObject(false)]
public partial class SpotConversationMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.SpotTypes Spot { get; set; } = default!;

    [Key(2)]
    public long? CharacterId1 { get; set; }

    [Key(3)]
    public long? CharacterId2 { get; set; }

    [Key(4)]
    public long? CharacterId3 { get; set; }

    [Key(5)]
    public long? CharacterId4 { get; set; }

    [Key(8)]
    public long? CharacterId5 { get; set; }

    [Key(9)]
    public long EpisodeMasterId { get; set; }

    [Key(10)]
    public long? CostumeId1 { get; set; }

    [Key(11)]
    public long? CostumeId2 { get; set; }

    [Key(12)]
    public long? CostumeId3 { get; set; }

    [Key(13)]
    public long? CostumeId4 { get; set; }

    [Key(14)]
    public long? CostumeId5 { get; set; }

    [Key(15)]
    public string Title { get; set; }

}
