// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StampMaster")]
[MessagePackObject(false)]
public partial class StampMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int Order { get; set; }

    [Key(2)]
    public bool IsDefault { get; set; }

    [Key(3)]
    [Obsolete("See to Characters")]
    public long CharacterBaseMasterId { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.StampType Type { get; set; } = default!;

    [Key(5)]
    public string AssetId { get; set; }

    [Key(6)]
    public string VoiceAssetId { get; set; }

    [Key(7)]
    public string Name { get; set; }

    [Key(8)]
    public long[] CharacterBaseMasterIds { get; set; } = default!;

}
