// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StaminaRecoveryItemMaster")]
[MessagePackObject(false)]
public partial class StaminaRecoveryItemMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long ItemMasterId { get; set; }

    [Key(1)]
    public int RecoveryAmount { get; set; }

    [Key(2)]
    public global::System.DateTime? ExpiredAt { get; set; }

    [Key(3)]
    public bool IsForceShowList { get; set; }

}
