// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StarRankRewardMaster")]
[MessagePackObject(false)]
public partial class StarRankRewardMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey(keyOrder: 0)]
    [Key(0)]
    public int Rank { get; set; }

    [MasterMemory.PrimaryKey(keyOrder: 1)]
    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [Key(2)]
    public long CharacterStarRankRewardGroupMasterId { get; set; }

}
