// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StarActConditionMaster")]
[MessagePackObject(false)]
public partial class StarActConditionMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public int FreeLight { get; set; }

    [Key(2)]
    public int SupportLight { get; set; }

    [Key(3)]
    public int ControlLight { get; set; }

    [Key(4)]
    public int AmplificationLight { get; set; }

    [Key(5)]
    public int SpecialLight { get; set; }

}
