// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StarActMaster")]
[MessagePackObject(false)]
public partial class StarActMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(4)]
    public long StarActConditionMasterId { get; set; }

    [Key(5)]
    public int AcquirableScorePercent { get; set; }

    [Key(6)]
    public int ScoreUpPerLevel { get; set; }

    [Key(7)]
    public EffectOrderMaster[] PreEffects { get; set; } = default!;

    [Key(8)]
    public BranchMaster[] Branches { get; set; } = default!;

    [Key(9)]
    public global::Sirius.Protocol.Shared.BranchConditionType BranchCondition1 { get; set; } = default!;

    [Key(10)]
    public long? ConditionValue1 { get; set; }

    [Key(11)]
    public global::Sirius.Protocol.Shared.BranchConditionType BranchCondition2 { get; set; } = default!;

    [Key(12)]
    public long? ConditionValue2 { get; set; }

}
