// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class StepupGachaMaster
{
    [Key(0)]
    public long GachaMasterId { get; set; }

    [Key(1)]
    public int Step { get; set; }

}
