// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryEventHighScoreBuffMaster")]
[MessagePackObject(false)]
public partial class StoryEventHighScoreBuffMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryEventHighScoreBuffPatternGroupId { get; set; }

    [Key(2)]
    public long EffectMasterId { get; set; }

    [Key(3)]
    public string EffectName { get; set; }

    [Key(4)]
    public string EffectDescription { get; set; }

    [Key(5)]
    public string IconImagePath { get; set; }

}
