// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryRelationMaster")]
[MessagePackObject(false)]
public partial class StoryRelationMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long StoryMasterId { get; set; }

    [Key(1)]
    public long[] PreviousStoryMasterIds { get; set; } = default!;

    [Key(2)]
    public long[] NextStoryMasterIds { get; set; } = default!;

    [Key(3)]
    public long[] SideStoryCharacterMasterIds { get; set; } = default!;

    [Key(4)]
    public long[] RelatedStoryMasterIds { get; set; } = default!;

}
