// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryEventCircleMaster")]
[MessagePackObject(false)]
public partial class StoryEventCircleMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryEventMasterId { get; set; }

    [Key(2)]
    public long MusicMasterId { get; set; }

}
