// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryEventCircleMissionMaster")]
[MessagePackObject(false)]
public partial class StoryEventCircleMissionMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryEventMasterId { get; set; }

    [Key(2)]
    public string Title { get; set; }

    [Key(3)]
    public string CountUnit { get; set; }

    [Key(4)]
    public long GoalCount { get; set; }

    [Key(5)]
    public int MaxPhase { get; set; }

    [Key(6)]
    public int GivePointAtGoal { get; set; }

}
