// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class StoryEventStoryBgmSchedule
{
    [Key(0)]
    public string AssetName { get; set; }

    [Key(1)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(2)]
    public global::System.DateTime EndDate { get; set; } = default!;

}
