// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryEventHighScoreBuffSettingMaster")]
[MessagePackObject(false)]
public partial class StoryEventHighScoreBuffSettingMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryEventHighScoreMasterId { get; set; }

    [Key(2)]
    public long StoryEventHighScoreBuffMasterId { get; set; }

    [Key(3)]
    public StoryEventHighScoreBuffMaster StoryEventHighScoreBuffMaster { get; set; } = default!;

}
