// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryEventEpisodeMaster")]
[MessagePackObject(false)]
public partial class StoryEventEpisodeMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryMasterId { get; set; }

    [Key(3)]
    public long RequiredTotalAcquiredPoint { get; set; }

    [Key(4)]
    public string Title { get; set; }

    [Key(5)]
    public int Order { get; set; }

    [Key(6)]
    public long? RequiredReadEpisodeMasterId { get; set; }

    [Key(7)]
    public long EpisodeRewardPackageMasterId { get; set; }

}
