// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryEventStoryBgmGroupMaster")]
[MessagePackObject(false)]
public partial class StoryEventStoryBgmGroupMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long StoryEventMasterId { get; set; }

    [Key(1)]
    public StoryEventStoryBgmSchedule[] Schedules { get; set; } = default!;

}
