// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryEventBonusCharacterBaseMaster")]
[MessagePackObject(false)]
public partial class StoryEventBonusCharacterBaseMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryEventMasterId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.StoryEventBonusTypes BonusTargetType { get; set; } = default!;

    [Key(3)]
    public long BonusTargetId { get; set; }

}
