// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryEventMaster")]
[MessagePackObject(false)]
public partial class StoryEventMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.StoryEventCategoryTypes Category { get; set; } = default!;

    [Key(2)]
    public global::Sirius.Protocol.Shared.Attributes? BonusAttribute { get; set; }

    [Key(3)]
    public string Title { get; set; }

    [Key(4)]
    public long ExchangeShopMasterId { get; set; }

    [Key(5)]
    public long EventPointItemMasterId { get; set; }

    [Key(6)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(7)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(8)]
    public global::System.DateTime ForceEndDate { get; set; } = default!;

    [Key(9)]
    public long? BonusCategoryMasterId10 { get; set; }

    [Key(10)]
    public long? BonusCategoryMasterId20 { get; set; }


    [Key(11)]
    public int? Reserved11 { get; set; }

}
