// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryEventHighScoreMaster")]
[MessagePackObject(false)]
public partial class StoryEventHighScoreMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryEventMasterId { get; set; }

    [Key(2)]
    public long MusicMasterId { get; set; }

    [Key(3)]
    public long[] BuffIds { get; set; } = default!;

    [Key(4)]
    public long SenseNotationMasterId { get; set; }

}
