// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryEventRewardMaster")]
[MessagePackObject(false)]
public partial class StoryEventRewardMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryEventMasterId { get; set; }

    [Key(2)]
    public int TargetMinRank { get; set; }

    [Key(3)]
    public int TargetMaxRank { get; set; }

    [Key(4)]
    public long StoryEventRewardItemPackageId { get; set; }

}
