// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class StoryEventHighScoreBuffPatternMaster
{
    [Key(0)]
    public int NextLevel { get; set; }

    [Key(1)]
    public int RequiredPoint { get; set; }

}
