// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryEventStoryMaster")]
[MessagePackObject(false)]
public partial class StoryEventStoryMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long StoryMasterId { get; set; }

    [Key(2)]
    public long StoryEventMasterId { get; set; }

    [Key(3)]
    public global::System.DateTime ListedStartDate { get; set; } = default!;

    [Key(4)]
    public global::Sirius.Protocol.Shared.EventStoryListFlags EventStoryListFlags { get; set; } = default!;

    [Key(5)]
    public bool IsKeyStory { get; set; }

}
