// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("StoryMaster")]
[MessagePackObject(false)]
public partial class StoryMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.StoryTypes Type { get; set; } = default!;

    [Key(2)]
    public long? CompanyMasterId { get; set; }

    [Key(3)]
    public long? EventMasterId { get; set; }

    [Key(4)]
    public int ChapterOrder { get; set; }

    [Key(5)]
    public global::System.DateTime DisplayStartAt { get; set; } = default!;

    [Key(6)]
    public global::System.DateTime DisplayEndAt { get; set; } = default!;

}
