// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("TeamChallengeMaster")]
[MessagePackObject(false)]
public partial class TeamChallengeMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MusicMasterId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.TeamChallengeDifficultyTypes Difficulty { get; set; } = default!;

    [Key(3)]
    public global::Sirius.Protocol.Shared.TeamChallengeGoalTypes GoalType { get; set; } = default!;

    [Key(4)]
    public long GoalMinValue { get; set; }

    [Key(5)]
    public long GoalMaxValue { get; set; }

    [Key(6)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(7)]
    public global::System.DateTime EndDate { get; set; } = default!;

}
