// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("TheaterStoryMaster")]
[MessagePackObject(false)]
public partial class TheaterStoryMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public int Order { get; set; }

    [Key(3)]
    public bool HasSynopsis { get; set; }

    [Key(4)]
    public string Synopsis { get; set; }

    [Key(5)]
    public global::System.DateTime DisplayStartAt { get; set; } = default!;

    [Key(6)]
    public global::System.DateTime DisplayEndAt { get; set; } = default!;

    [Key(7)]
    public TheaterRoleMaster[] Roles { get; set; } = default!;

    [Key(8)]
    public TheaterDetailMaster[] Details { get; set; } = default!;

}
