// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class TheaterDetailMaster
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Speaker { get; set; }

    [Key(2)]
    public string Phrase { get; set; }

    [Key(3)]
    public string VoiceAssetId { get; set; }

}
