// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class TheaterRoleMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public string RoleName { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [Key(2)]
    public long CostumeMasterId { get; set; }

    [Key(3)]
    public int Order { get; set; }

}
