// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("TheaterChapterMaster")]
[MessagePackObject(false)]
public partial class TheaterChapterMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public long CompanyMasterId { get; set; }

    [Key(3)]
    public global::System.DateTime DisplayStartAt { get; set; } = default!;

    [Key(4)]
    public global::System.DateTime DisplayEndAt { get; set; } = default!;

    [Obsolete("Use TheaterStoryMasterIds")]
    [Key(5)]
    public TheaterStoryMaster[] Stories { get; set; } = default!;

    [Obsolete("Use RequiredReadEpisodeMasterId")]
    [Key(6)]
    public long? EpisodeMasterId { get; set; }

    [Key(7)]
    public long RequiredReadEpisodeMasterId { get; set; }

    [Key(8)]
    public long[] TheaterStoryMasterIds { get; set; } = default!;

}
