// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("TimeLimitedControlMaster")]
[MessagePackObject(false)]
public partial class TimeLimitedControlMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::System.DateTime EndDate { get; set; } = default!;

}
