// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class TitleBackgroundDetailMaster
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.TitleBackgroundPathTypes PathType { get; set; } = default!;

    [Key(2)]
    public string PathValue { get; set; }


    [Key(3)]
    public bool Reserved3 { get; set; }


    [Key(4)]
    public bool Reserved4 { get; set; }

}
