// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("TournamentQualifyingMaster")]
[MessagePackObject(false)]
public partial class TournamentQualifyingMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long EventMasterId { get; set; }

    [Key(2)]
    public string EntryPageUrl { get; set; }

    [Key(3)]
    public global::System.DateTime EntryStartDate { get; set; } = default!;

    [Key(4)]
    public global::System.DateTime EntryEndDate { get; set; } = default!;

    [Key(5)]
    public string WebsiteUrl { get; set; }

}
