// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("TrialPartyEventStageMaster")]
[MessagePackObject(false)]
public partial class TrialPartyEventStageMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long TrialPartyEventMasterId { get; set; }

    [Key(2)]
    public long MusicMasterId { get; set; }

    [Key(3)]
    public int VocalVersion { get; set; }

    [Key(4)]
    public long SenseNotationMasterId { get; set; }

    [Key(5)]
    public long ClearScore { get; set; }

    [Key(6)]
    public int ClearSenseCount { get; set; }

    [Key(7)]
    public int ClearStarActCount { get; set; }

    [Key(8)]
    public int ClearPrincipalGaugeValue { get; set; }

    [Key(9)]
    public string Title { get; set; }

    [Key(10)]
    public string Hint { get; set; }

    [Key(11)]
    public string RestrictionInfo { get; set; }

    [Key(12)]
    public TrialPartyEventStageRewardMaster[] Rewards { get; set; } = default!;

    [Key(13)]
    public long TrialPartyMasterId { get; set; }

    [Key(14)]
    public bool UnrecommendedAuto { get; set; }

}
