// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("TrialPartyCharacterMaster")]
[MessagePackObject(false)]
public partial class TrialPartyCharacterMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long TrialPartyMasterId { get; set; }

    [Key(2)]
    public long CharacterMasterId { get; set; }

    [Key(3)]
    public int Level { get; set; }

    [Key(4)]
    public int TalentStage { get; set; }

    [Key(5)]
    public int AwakeningStatus { get; set; }

    [Key(6)]
    public int SenseLevel { get; set; }

    [Key(7)]
    public global::Sirius.Protocol.Shared.CharacterEpisodeOrder ReadEpisodeOrder { get; set; } = default!;

}
