// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("TrialPartyEventMaster")]
[MessagePackObject(false)]
public partial class TrialPartyEventMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MEventId { get; set; }

    [Key(2)]
    public bool IsHideComplate { get; set; }

    [Key(3)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(4)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(5)]
    public string BgmPath { get; set; }

    [Key(6)]
    public string Name { get; set; }

}
