// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MessagePackObject(false)]
public partial class TrialPartySlotMaster
{
    [Key(0)]
    public int Position { get; set; }

    [Key(1)]
    public bool IsPositionLock { get; set; }

    [Key(2)]
    public long TrialPartyCharacterMasterId { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.TrialPartyCharacterLockTypes CharacterLockType { get; set; } = default!;

    [Key(4)]
    public long? TrialPartyPosterMasterId { get; set; }

    [Key(5)]
    public global::Sirius.Protocol.Shared.TrialPartyEquipmentLockTypes PosterLockype { get; set; } = default!;

    [Key(6)]
    public long? TrialPartyAccessoryMasterId { get; set; }

    [Key(7)]
    public global::Sirius.Protocol.Shared.TrialPartyEquipmentLockTypes AccessoryLockType { get; set; } = default!;

}
