// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("TrialPartyAccessoryMaster")]
[MessagePackObject(false)]
public partial class TrialPartyAccessoryMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long TrialPartyMasterId { get; set; }

    [Key(2)]
    public long AccessoryMasterId { get; set; }

    [Key(3)]
    public int Level { get; set; }

    [Key(4)]
    public long[] AccessoryEffects { get; set; } = default!;

}
