// <auto-generated />
#nullable enable
using MessagePack;
namespace Sirius.Protocol.Shared.Models.Master;
[MasterMemory.MemoryTable("TripleCastAllClassGlobalRankingRewardThingMaster")]
[MessagePackObject(false)]
public partial class TripleCastAllClassGlobalRankingRewardThingMaster
{
    [MasterMemory.PrimaryKey, Key(0)] public long Id { get; set; }
    [Key(1)] public long TripleCastMasterId { get; set; }
    [Key(2)] public TripleCastAllClassGlobalRankingRewardRewardItem[] Rewards { get; set; } = [];
    [Key(3)] public int MinRank { get; set; }
    [Key(4)] public int MaxRank { get; set; }
    [Key(5)] public string RewardTitle { get; set; } = string.Empty;
}

[MessagePackObject(false)]
public partial class TripleCastAllClassGlobalRankingRewardRewardItem
{
    [MasterMemory.PrimaryKey]
    [Key(0)] public long ThingId { get; set; }
    [Key(1)] public global::Sirius.Protocol.Shared.ThingTypes ThingType { get; set; }
    [Key(2)] public int ThingQuantity { get; set; }
}
