// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("TripleCastMaster")]
[MessagePackObject(false)]
public partial class TripleCastMaster
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MusicMasterId { get; set; }

    [Key(2)]
    public int VocalVersion { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.MusicDifficulties MaxDifficulty { get; set; } = default!;

    [Key(4)]
    public long SenseNotationMasterId1 { get; set; }

    [Key(5)]
    public long SenseNotationMasterId2 { get; set; }

    [Key(6)]
    public long SenseNotationMasterId3 { get; set; }

    [Key(7)]
    public global::System.DateTime DisplayStartAt { get; set; } = default!;

    [Key(8)]
    public global::System.DateTime CountingStartAt { get; set; } = default!;

    [Key(9)]
    public global::System.DateTime DisplayEndAt { get; set; } = default!;

    [Key(10)]
    public long LeagueClassGroupMasterId { get; set; }

    [Key(11)]
    public long TripleCastSeasonMasterId { get; set; }

    [Obsolete]
    [Key(12)]
    public long VocalEffectMasterId { get; set; }

    [Key(13)]
    [Obsolete]
    public long ExpressionEffectMasterId { get; set; }

    [Obsolete]
    [Key(14)]
    public long ConcentrationEffectMasterId { get; set; }

}
