// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("TrophyMaster")]
[MessagePackObject(false)]
public partial class TrophyMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Description { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.PossessionRarities Rarity { get; set; } = default!;

    [Key(4)]
    public int Order { get; set; }

    [Key(5)]
    public long TrophyGroupMasterId { get; set; }

    [Key(6)]
    public bool Hidden { get; set; }

    [Key(7)]
    public string UnlockText { get; set; }

}
