// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Master;

[MasterMemory.MemoryTable("UnlockConditionMaster")]
[MessagePackObject(false)]
public partial class UnlockConditionMaster : global::Sirius.Protocol.Shared.IDataObject
{
    [MasterMemory.PrimaryKey]
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string ConditionText { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.ConditionUsableTableFilter ConditionUsableTableFilter { get; set; } = default!;

    [Key(3)]
    public global::Sirius.Protocol.Shared.UnlockConditionTypes UnlockConditionType { get; set; } = default!;

}
