// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.Circle;

[MessagePackObject(false)]
public partial class ActivityLogCache
{
    [Key(0)]
    public string UserId { get; set; }

    [Key(1)]
    public string UserName { get; set; }

    [Key(2)]
    public long MainMCharacterId { get; set; }

    [Key(3)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Realtime.Shared.ActivityLogTypes LogType { get; set; } = default!;

    [Key(5)]
    public string LogValue { get; set; }

}
