// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.Circle;

[MessagePackObject(false)]
public partial class ActivityLogNotification
{
    [Key(0)]
    public string CircleId { get; set; }

    [Key(1)]
    public ActivityLogResult ActivityLogResult { get; set; } = default!;

}
