// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.Circle;

[MessagePackObject(false)]
public partial class ActivityLogResult : ActivityLogCache
{
    [Key(6)]
    public long ActivityLogId { get; set; }

    [Key(7)]
    public global::System.DateTime LoggedAt { get; set; } = default!;

}
