// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.Circle;

[MessagePackObject(false)]
public partial class CircleChatResult
{
    [Key(0)]
    public long ChatId { get; set; }

    [Key(1)]
    public string UserId { get; set; }

    [Key(2)]
    public string Message { get; set; }

    [Key(3)]
    public long? StampId { get; set; }

    [Key(4)]
    public global::System.DateTime SendTime { get; set; } = default!;

    [Key(5)]
    public global::Sirius.Protocol.Realtime.Shared.CircleChatTypes ChatType { get; set; } = default!;

    [Key(6)]
    public string UserName { get; set; }

    [Key(7)]
    public long? MainMCharacterId { get; set; }

    [Key(8)]
    public bool? DisplayAwakeningStatus { get; set; }

    [Key(9)]
    public string MentionHashUserId { get; set; }

    [Key(10)]
    public long IconFrameMasterId { get; set; }

}
