// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.Circle;

[MessagePackObject(false)]
public partial class CircleChatPayload
{
    [Key(0)]
    public string Message { get; set; }

    [Key(1)]
    public long? StampId { get; set; }

    [Key(2)]
    public string UserName { get; set; }

    [Key(3)]
    public long MainMCharacterId { get; set; }

    [Key(4)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(5)]
    public string MentionHashUserId { get; set; }

    [Key(6)]
    public long IconFrameMasterId { get; set; }

}
