// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.Circle;

[MessagePackObject(false)]
public partial class CircleReadChat
{
    [Key(0)]
    public long LastReadChatId { get; set; }

    [Key(1)]
    public long LatestChatId { get; set; }

}
