// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.Circle;

[MessagePackObject(false)]
public partial class CircleStatus
{
    [Key(0)]
    public global::Sirius.Protocol.Realtime.Shared.CircleJoinStatus JoinStatus { get; set; } = default!;

}
