// <auto-generated />
#nullable enable
using MessagePack;

namespace Sirius.Protocol;

[MessagePackObject(false)]
public readonly partial struct ApiActionResult<T>
{
    [Key(0)] public int Status { get; }
    [Key(1)] public string? ErrorMessage { get; }
    [Key(2)] public T? Response { get; }

    [IgnoreMember] public bool IsHttpError { get; }
    [IgnoreMember] public bool IsNetworkError { get; }
    [IgnoreMember] public bool IsCancel { get; }
    [IgnoreMember] public bool IsCritical { get; }
    [IgnoreMember] public bool IsOk => Status >= 200 && Status < 300 && !IsHttpError && !IsNetworkError && !IsCancel && !IsCritical;
    [IgnoreMember] public bool IsError => !IsOk;

    [SerializationConstructor]
    public ApiActionResult(int status, string? errorMessage, T? response)
    {
        Status = status; ErrorMessage = errorMessage; Response = response;
        IsHttpError = false; IsNetworkError = false; IsCancel = false; IsCritical = false;
    }

    public ApiActionResult(int status, string? errorMessage, T? response, bool isHttpError, bool isNetworkError, bool isCancel = false, bool isCritical = false)
    {
        Status = status; ErrorMessage = errorMessage; Response = response;
        IsHttpError = isHttpError; IsNetworkError = isNetworkError; IsCancel = isCancel; IsCritical = isCritical;
    }

    public static ApiActionResult<T> Ok(T response) => new(200, null, response);
    public static ApiActionResult<T> Error(int status, string? message = null) => new(status, message, default);
}
