// <auto-generated />
#nullable enable

namespace Sirius.Protocol;

public static class ApiOperationIds
{
    public static class Accessories
    {
        public const int Accessories_LevelUp = 1;
        public const int Accessories_Sell = 2;
        public const int Accessories_SwitchLock = 3;
        public const int Accessories_IncreaseAcquirableAccessoryLimit = 4;
    }

    public static class Account
    {
        public const int Account_Authenticate = 1;
        public const int Account_ConnectAccount = 2;
        public const int Account_DeleteAccount = 3;
        public const int Account_DisconnectAccount = 4;
        public const int Account_GetCurrentUserData = 5;
        public const int Account_GetTakeOverAccount = 6;
        public const int Account_Register = 7;
        public const int Account_RegisterTakeOverPassword = 8;
        public const int Account_TakeOverWithAccountConnect = 9;
        public const int Account_UpdateBirthDate = 10;
        public const int Account_GetConfirmationCode = 11;
        public const int Account_GetPrecedenceTransitionToken = 12;
        public const int Account_GetRoootTransitionToken = 13;
    }

    public static class Auditions
    {
        public const int Auditions_GetAuditionInformation = 1;
        public const int Auditions_CopyAuditionClearParty = 2;
        public const int Auditions_GetAuditionHighScoreParty = 3;
    }

    public static class CharacterMission
    {
        public const int CharacterMission_CheckInitializeCharacterMissions = 1;
        public const int CharacterMission_ReceiveAllMissionRewards = 2;
        public const int CharacterMission_ReceiveKeyMissionRewards = 3;
        public const int CharacterMission_ReceiveAllMissionRewardsAll = 4;
    }

    public static class Characters
    {
        public const int Characters_AddExperience = 1;
        public const int Characters_Awaken = 2;
        public const int Characters_BloomTalent = 3;
        public const int Characters_EnhanceSenseLevel = 4;
        public const int Characters_ReleaseSideStory = 5;
        public const int Characters_SetCostume = 6;
        public const int Characters_SwitchCharacterDisplayAwakeningStatus = 7;
        public const int Characters_BulkLevelUp = 8;
        public const int Characters_SetPortalMCharacter = 9;
        public const int Characters_LinkCharacter = 10;
        public const int Characters_ReceiveLinkCharacterReward = 11;
        public const int Characters_UpdateSelectionType = 12;
    }

    public static class Circles
    {
        public const int Circles_ApproveCircleInvite = 1;
        public const int Circles_ApproveCircleRequest = 2;
        public const int Circles_AuthorityChangeCircle = 3;
        public const int Circles_CancelInviteCircleInvite = 4;
        public const int Circles_CircleMemberInfo = 5;
        public const int Circles_CreateCircle = 6;
        public const int Circles_EditCircle = 7;
        public const int Circles_EditCircleBanner = 8;
        public const int Circles_ExpulsionCircle = 9;
        public const int Circles_GetCircle = 10;
        public const int Circles_GetCircles = 11;
        public const int Circles_GetCirclesConditionSearch = 12;
        public const int Circles_GetCirclesNameSearch = 13;
        public const int Circles_GetInvitedCircles = 14;
        public const int Circles_GetMyCircle = 15;
        public const int Circles_JoinCircle = 16;
        public const int Circles_RecommendInviteUser = 17;
        public const int Circles_RejectInviteCircleInvite = 18;
        public const int Circles_RejectRequestCircleInvite = 19;
        public const int Circles_ReleaseCircle = 20;
        public const int Circles_ResignationCircle = 21;
        public const int Circles_SearchFriend = 22;
        public const int Circles_SearchInviting = 23;
        public const int Circles_SearchRequestCircle = 24;
        public const int Circles_SearchUserIdCircle = 25;
        public const int Circles_SendCircleInvite = 26;
        public const int Circles_SendCirclenRequest = 27;
        public const int Circles_SendCirclePreRequest = 28;
        public const int Circles_SetVisibleActivityLog = 29;
        public const int Circles_GetCircleSupportPointDailyRanking = 30;
        public const int Circles_GetCircleSupportPointMonthlyRanking = 31;
        public const int Circles_GetCircleSupportPointWeeklyRanking = 32;
        public const int Circles_GetSupportAndTheaterLevelInformation = 33;
        public const int Circles_ReceiveCircleTheaterStamina = 34;
        public const int Circles_SetIsPublishRanking = 35;
        public const int Circles_SetSupportCompany = 36;
    }

    public static class Comics
    {
        public const int Comics_Read = 1;
    }

    public static class Data
    {
        public const int Data_GetMasterData = 1;
        public const int Data_GetUserData = 2;
    }

    public static class Debug
    {
        public const int Debug_AddRankPoint = 1;
        public const int Debug_AddStarPoint = 2;
        public const int Debug_AlbumSimpleArranging = 3;
        public const int Debug_AuthenticateOrRegister = 4;
        public const int Debug_CallInboxService = 5;
        public const int Debug_CallInboxServiceMany = 6;
        public const int Debug_CircleUsageTimeReset = 7;
        public const int Debug_ClearAudition = 8;
        public const int Debug_CreateAlbum = 9;
        public const int Debug_CreateCircleDummy = 10;
        public const int Debug_CreateDummyLeagueHistory = 11;
        public const int Debug_CreateDummyUsers = 12;
        public const int Debug_DeleteCircles = 13;
        public const int Debug_DeleteLeagueAllData = 14;
        public const int Debug_DeleteLeagueUserData = 15;
        public const int Debug_DeleteLeagueUsersData = 16;
        public const int Debug_DeleteStoryEventCircleMissionRewards = 17;
        public const int Debug_EditLeagueBasic = 18;
        public const int Debug_EditLeagueHistory = 19;
        public const int Debug_ExecuteLeagueTotalization = 20;
        public const int Debug_GenerateLeagueGroupScore = 21;
        public const int Debug_GenerateLiveRate = 22;
        public const int Debug_GenerateStoryEventHighScoreRanking = 23;
        public const int Debug_GenerateStoryEventPointRanking = 24;
        public const int Debug_GetCacheUpdatedAt = 25;
        public const int Debug_GetCurrentApiToken = 26;
        public const int Debug_GetCurrentLeague = 27;
        public const int Debug_GetEpisode = 28;
        public const int Debug_GetLeagueHistories = 29;
        public const int Debug_GetUsetId = 30;
        public const int Debug_GiveEnhanceItems = 31;
        public const int Debug_GrantAllThing = 32;
        public const int Debug_GrowPostersMax = 33;
        public const int Debug_InitializeLeagueBasicData = 34;
        public const int Debug_InitializePlayerRate = 35;
        public const int Debug_JoinOnCreateLeagueGroupMember = 36;
        public const int Debug_LeaveLeagueGroup = 37;
        public const int Debug_PrepareLeagueGroupUser = 38;
        public const int Debug_PurchaseDaiStarPass = 39;
        public const int Debug_PurchaseStarPass = 40;
        public const int Debug_RefreshMemoryCache = 41;
        public const int Debug_ReleaseAllEpisodes = 42;
        public const int Debug_ReleaseAllMusicDifficulty = 43;
        public const int Debug_ResetAutoPlay = 44;
        public const int Debug_ResetLesson = 45;
        public const int Debug_ResetStoryEventCircleMissionSnapshot = 46;
        public const int Debug_ResetStoryEventHighScoreRanking = 47;
        public const int Debug_ResetStoryEventPointRanking = 48;
        public const int Debug_SendAccessories = 49;
        public const int Debug_SendBomb = 50;
        public const int Debug_SendBombs = 51;
        public const int Debug_SendCharacter = 52;
        public const int Debug_SendCharacters = 53;
        public const int Debug_SendChatworkMessage = 54;
        public const int Debug_SendCoin = 55;
        public const int Debug_SendCostume = 56;
        public const int Debug_SendCostumes = 57;
        public const int Debug_SendDecoration = 58;
        public const int Debug_SendDecorations = 59;
        public const int Debug_SendItem = 60;
        public const int Debug_SendItems = 61;
        public const int Debug_SendJewel = 62;
        public const int Debug_SendMusic = 63;
        public const int Debug_SendMusics = 64;
        public const int Debug_SendNameColor = 65;
        public const int Debug_SendNameColors = 66;
        public const int Debug_SendNameplate = 67;
        public const int Debug_SendNameplates = 68;
        public const int Debug_SendNote = 69;
        public const int Debug_SendNotes = 70;
        public const int Debug_SendNotification = 71;
        public const int Debug_SendPaidJewel = 72;
        public const int Debug_SendPoster = 73;
        public const int Debug_SendPosters = 74;
        public const int Debug_SendStamp = 75;
        public const int Debug_SendStamp2 = 76;
        public const int Debug_SendTrophies = 77;
        public const int Debug_SendTrophy = 78;
        public const int Debug_SetAutoPlayAvailableTimes = 79;
        public const int Debug_SetCharacterMissionCount = 80;
        public const int Debug_SetLeagueScore = 81;
        public const int Debug_SetLoginPassUntil = 82;
        public const int Debug_SetMissionCount = 83;
        public const int Debug_SetPhoto = 84;
        public const int Debug_SetPlayerRank = 85;
        public const int Debug_SetPlayerRankWithPoint = 86;
        public const int Debug_SetPlayerRate = 87;
        public const int Debug_SetReleasableOlivier = 88;
        public const int Debug_SetReleasedStella = 89;
        public const int Debug_SetServerTime = 90;
        public const int Debug_SetSpRate = 91;
        public const int Debug_SetStarRank = 92;
        public const int Debug_SetStoryEventCircleMissionCount = 93;
        public const int Debug_SetStoryEventPoint = 94;
        public const int Debug_SetTimeWarpByDate = 95;
        public const int Debug_SetTimeWarpBySpecifyOffset = 96;
        public const int Debug_SetTournamentDetail = 97;
        public const int Debug_UnlockAllFeatures = 98;
        public const int Debug_UpdateRankingScore = 99;
        public const int Debug_UpdateUserProfileSnapshots = 100;
        public const int Debug_UploadToutchLog = 101;
        public const int Debug_SetUserBanLevel = 102;
        public const int Debug_SetCircleStoryEventHighScore = 103;
        public const int Debug_CreateFriendRequestForMe = 104;
        public const int Debug_DeleteLeagueData = 105;
        public const int Debug_SetStamina = 106;
        public const int Debug_GrowAccessoriesMax = 107;
        public const int Debug_GrowCharactersMax = 108;
        public const int Debug_AddCircleMembers = 109;
        public const int Debug_FinishLive = 110;
        public const int Debug_SetStoryEventHighScoreEnhancementPoint = 111;
        public const int Debug_AddLessonHighScore = 112;
        public const int Debug_SetCharacterEnhanceInfo = 113;
        public const int Debug_SetPosterEnhanceInfo = 114;
        public const int Debug_EasyStartLive = 115;
        public const int Debug_FinishLiveSpecifiedNotes = 116;
        public const int Debug_AddExceededStarPoint = 117;
        public const int Debug_SetSplashLastDisplayedAt = 118;
        public const int Debug_AddPointForTotalPointEvent = 119;
        public const int Debug_ResetTotalPointEvent = 120;
        public const int Debug_RecordActivityLog = 121;
        public const int Debug_GenerateCharacterPointEventPointRanking = 122;
        public const int Debug_GenerateDummyCharacterPointEventPointRanking = 123;
        public const int Debug_ResetCharacterPointEventPointRanking = 124;
        public const int Debug_SetCharacterPointEventPoint = 125;
        public const int Debug_DailyAddedSupportPoint = 126;
        public const int Debug_SetCircleSupportPointInfo = 127;
        public const int Debug_SetStaminaLastReceivedAt = 128;
        public const int Debug_GenerateDummyTotalPointEventPointRanking = 129;
        public const int Debug_SetTotalPointEvent = 130;
        public const int Debug_SendAlbumTheme = 131;
        public const int Debug_SendAlbuThemes = 132;
        public const int Debug_OpenAllFalshSale = 133;
        public const int Debug_SetFlashSaleCount = 134;
        public const int Debug_ReestCircleEventPointAndMission = 135;
        public const int Debug_ReestCircleEventPointAndMission2 = 136;
        public const int Debug_AddCircleEventMissionCount = 137;
        public const int Debug_SetParty = 138;
        public const int Debug_SendLoginBonusAgain = 139;
        public const int Debug_SetMarketFrameThing = 140;
        public const int Debug_GiveEnhanceItemsAndGrowCharactersMax = 141;
        public const int Debug_GiveEnhanceItemsAndGrowPostersMax = 142;
        public const int Debug_GenerateLinkageCodeAndPassword = 143;
        public const int Debug_SendAccessoryWithEffect = 144;
        public const int Debug_AddCircleEventMissionCount2 = 145;
        public const int Debug_GiveEnhanceItemsAndGrowAccessoriesMax = 146;
        public const int Debug_CreateTripleCastHistory = 147;
        public const int Debug_SetTripleCastDaistarEnrollCount = 148;
        public const int Debug_DeleteTripleCastData = 149;
        public const int Debug_SetMusicCourseRanking = 150;
        public const int Debug_DeleteAllCourseRanking = 151;
        public const int Debug_SetCourseRankingResultsDecreasingByPercent = 152;
        public const int Debug_SetTripleCastGroupScore = 153;
        public const int Debug_SetLeagueGroupScore = 154;
        public const int Debug_SetTripleCastScore = 155;
        public const int Debug_SendIconFrame = 156;
        public const int Debug_SendIconFrames = 157;
        public const int Debug_SendNameBaseColor = 158;
        public const int Debug_SendNameBaseColors = 159;
        public const int Debug_BattleGhost = 160;
        public const int Debug_SetGhost = 161;
        public const int Debug_GetLiveScoreHistory = 162;
        public const int Debug_CreateConcoursRandomRankings = 163;
        public const int Debug_ResetPickupGachaSelectedThings = 164;
        public const int Debug_PurchaseExternalPaymentItem = 165;
        public const int Debug_SetSpRatePoint = 166;
        public const int Debug_SetSpRateSegment = 167;
    }

    public static class Environment
    {
        public const int Environment_GetEnvironment = 1;
        public const int Environment_Ping = 2;
    }

    public static class Episodes
    {
        public const int Episodes_CompleteRead = 1;
        public const int Episodes_CompleteReadAll = 2;
        public const int Episodes_GetEpisodeDetail = 3;
    }

    public static class Events
    {
        public const int Events_GetStoryEventBorderRanking = 1;
        public const int Events_GetStoryEventCircleMissionProgresses = 2;
        public const int Events_GetStoryEventHighScoreTopRanking = 3;
        public const int Events_GetStoryEventMyRanking = 4;
        public const int Events_GetStoryEventNearRanking = 5;
        public const int Events_GetStoryEventTopRanking = 6;
        public const int Events_GrowStoryEventHighScoreBuffSetting = 7;
        public const int Events_ReadTips = 8;
        public const int Events_ReceiveStoryEventCircleMissionAllReward = 9;
        public const int Events_ReceiveStoryEventCircleMissionReward = 10;
        public const int Events_GetStoryEventCircleRanking = 11;
        public const int Events_GetStoryEventFriendRanking = 12;
        public const int Events_GetTotalPointEventCircleRanking = 13;
        public const int Events_GetTotalPointEventFriendRanking = 14;
        public const int Events_GetTotalPointEventInformation = 15;
        public const int Events_GetTotalPointEventNearRanking = 16;
        public const int Events_GetTotalPointEventTopRanking = 17;
        public const int Events_ReceiveTotalPointEventReward = 18;
        public const int Events_ResetEventBoxGacha = 19;
        public const int Events_RollEventBoxGacha = 20;
        public const int Events_ReadSpecialEventTips = 21;
        public const int Events_GetCharacterPointCharacterBorderRanking = 22;
        public const int Events_GetCharacterPointCharacterNearRanking = 23;
        public const int Events_GetCharacterPointCharacterTopRanking = 24;
        public const int Events_GetCharacterPointEventInformation = 25;
        public const int Events_GetCharacterPointOverallTopRanking = 26;
        public const int Events_ReadCharacterPointEventTips = 27;
        public const int Events_SetCharacterPointEventCharacter = 28;
        public const int Events_GetCircleEventBorderRanking = 29;
        public const int Events_GetCircleEventCircleRanking = 30;
        public const int Events_GetCircleEventInformation = 31;
        public const int Events_GetCircleEventNearRanking = 32;
        public const int Events_ReceiveCircleEventCirclePointReward = 33;
        public const int Events_ResetCircleEventMissionCount = 34;
        public const int Events_GetEventNearRanking = 35;
        public const int Events_GetEventCircleRanking = 36;
        public const int Events_GetEventTopRanking = 37;
        public const int Events_GetEventBorderRanking = 38;
        public const int Events_GetEventFriendRanking = 39;
        public const int Events_GetEventMyRanking = 40;
        public const int Events_NoneStoryEventsReadTips = 41;
        public const int Events_ResetCircleEventMisionCount = 42;
        public const int Events_GetTournamentQualifyingInformation = 43;
        public const int Events_SaveDugongRunClearStatus = 44;
        public const int Events_EditTrialPartyEventParty = 45;
        public const int Events_GetConcoursInformation = 46;
        public const int Events_GetEventCampMyRanking = 49;
    }

    public static class FlashSale
    {
        public const int FlashSale_ReadFlashSaleStage = 1;
    }

    public static class FriendInvitation
    {
        public const int FriendInvitation_ActivateInvitationCode = 1;
        public const int FriendInvitation_CheckInvitationCodeInfo = 2;
        public const int FriendInvitation_ReceiveInvitationMissionRewards = 3;
        public const int FriendInvitation_UpdateInvitationMission = 4;
    }

    public static class Friends
    {
        public const int Friends_AcceptFriendRequest = 1;
        public const int Friends_CancelFriendRequest = 2;
        public const int Friends_DenyFriendRequest = 3;
        public const int Friends_GetFriends = 4;
        public const int Friends_GetReceivedRequest = 5;
        public const int Friends_GetSendingRequest = 6;
        public const int Friends_RemoveFriend = 7;
        public const int Friends_SearchFriend = 8;
        public const int Friends_SendFriendRequest = 9;
        public const int Friends_RemoveBlockUser = 10;
        public const int Friends_BlockUser = 11;
        public const int Friends_BlockUsers = 12;
    }

    public static class Gachas
    {
        public const int Gachas_GetAvailableGachas = 1;
        public const int Gachas_GetCharacterGachaLineup = 2;
        public const int Gachas_GetGachaHistories = 3;
        public const int Gachas_GetPosterGachaLineup = 4;
        public const int Gachas_GetSelectedThings = 5;
        public const int Gachas_RollGacha = 6;
        public const int Gachas_SetSelectedThings = 7;
        public const int Gachas_ReRollGacha = 8;
        public const int Gachas_GetReRollGachaResults = 9;
        public const int Gachas_DecideReRollGacha = 10;
    }

    public static class Home
    {
        public const int Home_CheckReceiveLoginBonus = 1;
        public const int Home_GetNotificationContent = 2;
        public const int Home_GetNotificationContentAnonymous = 3;
        public const int Home_GetNotifications = 4;
        public const int Home_GetNotificationsAnonymous = 5;
        public const int Home_Index = 6;
        public const int Home_Post = 7;
        public const int Home_UpdateNotificationReadTime = 8;
        public const int Home_GetMultiLiveRestrictionNotification = 9;
        public const int Home_CheckEexternalPayment = 10;
    }

    public static class Inbox
    {
        public const int Inbox_BulkReceive = 1;
        public const int Inbox_CheckPackages = 2;
        public const int Inbox_Receive = 3;
    }

    public static class Items
    {
        public const int Items_UseRecoveryStaminaItems = 1;
        public const int Items_ExchangeCharacterPiece = 2;
    }

    public static class KmsGeneralPayment
    {
        public const int KmsGeneralPayment_ProcessAppStorePayment = 1;
        public const int KmsGeneralPayment_ProcessGooglePlayPayment = 2;
    }

    public static class Leagues
    {
        public const int Leagues_GetGlobalRanking = 1;
        public const int Leagues_GetGroupRanking = 2;
        public const int Leagues_GetTopMenuInformation = 3;
        public const int Leagues_SendThingLeagueRewards = 4;
        public const int Leagues_SendTripleCastThingLeagueRewards = 5;
        public const int Leagues_GetTripleCastGlobalRanking = 6;
        public const int Leagues_GetTripleCastGroupRanking = 7;
        public const int Leagues_GetTripleCastTopMenuInformation = 8;
    }

    public static class Lessons
    {
        public const int Lessons_CreateParty = 1;
        public const int Lessons_Finish = 2;
        public const int Lessons_SetParty = 3;
        public const int Lessons_SetPartyLeader = 4;
        public const int Lessons_Start = 5;
    }

    public static class Lives
    {
        public const int Lives_CalculateLessonTimingEvents = 1;
        public const int Lives_CalculateTimeEvents = 2;
        public const int Lives_Finish = 3;
        public const int Lives_FinishAndValidate = 4;
        public const int Lives_GetMultiLiveInformation = 5;
        public const int Lives_Retire = 6;
        public const int Lives_Start = 7;
        public const int Lives_StartLesson = 8;
        public const int Lives_StartMultiLive = 9;
        public const int Lives_StartMultiLiveSession = 10;
        public const int Lives_StartTournament = 11;
        public const int Lives_UpdateClearLamp = 12;
        public const int Lives_StartConcert = 13;
        public const int Lives_FinishTeamChallengeSession = 14;
        public const int Lives_ReceiveTeamChallengeRewards = 15;
        public const int Lives_StartTeamChallengeSession = 16;
        public const int Lives_EditBookmark = 17;
        public const int Lives_FinishAnotherNotationLive = 18;
        public const int Lives_ReadConcertTips = 19;
        public const int Lives_StartBonusLive = 20;
        public const int Lives_StartMusicCourse = 21;
        public const int Lives_StartTripleCastLive = 22;
        public const int Lives_GetCourseCircleRanking = 23;
        public const int Lives_GetCourseFriendRanking = 24;
        public const int Lives_GetCourseTopRanking = 25;
        public const int Lives_GetCourseNearRanking = 26;
        public const int Lives_StartTrialPartyEventStage = 27;
        public const int Lives_MatchingGhostLive = 28;
        public const int Lives_StartGhostLive = 29;
    }

    public static class Login
    {
        public const int Login_Login = 1;
    }

    public static class Mission
    {
        public const int Mission_ReceiveAllCurrentReward = 1;
        public const int Mission_ReceiveBulkMissionPassRewards = 2;
        public const int Mission_ReceiveCurrentReward = 3;
        public const int Mission_ReceivePiclupCharacterMissionRewards = 4;
        public const int Mission_BulkReceivePiclupCharacterMissionRewards = 5;
        public const int Mission_ExchangeMissionPoint = 6;
    }

    public static class Party
    {
        public const int Party_ChangePartyName = 1;
        public const int Party_CopyParty = 2;
        public const int Party_EditParty = 3;
        public const int Party_EditParty2 = 4;
        public const int Party_EditPartyPosition = 5;
        public const int Party_EditPartyWithRecommended = 6;
        public const int Party_SetMultiParty = 7;
        public const int Party_CalculateSenseTimingAllCombinations = 8;
        public const int Party_EditTripleCastParty = 9;
        public const int Party_EditTripleCastPartySlotPosition = 10;
        public const int Party_ChangeTripleCastPartyName = 11;
        public const int Party_SetTripleCastPartyLeaderPosition = 12;
        public const int Party_EditTripleCastBasic = 13;
    }

    public static class Photo
    {
        public const int Photo_AlbumSimpleArranging = 1;
        public const int Photo_GeneratePhoto = 2;
        public const int Photo_GetAlbumMainPage = 3;
        public const int Photo_PhotoLevelUp = 4;
        public const int Photo_Sell = 5;
        public const int Photo_SwitchLock = 6;
        public const int Photo_WatchMusicVideo = 7;
        public const int Photo_WatchTheaterStory = 8;
        public const int Photo_SetAlbumPublishing = 9;
        public const int Photo_AlbumDetailArranging = 10;
        public const int Photo_FinishGeneratePhoto = 11;
        public const int Photo_RegeneratePhoto = 12;
        public const int Photo_IncreaseAcquirablePhotoLimit = 13;
        public const int Photo_SetCharacterBaseTags = 14;
        public const int Photo_GeneratePhotos = 15;
        public const int Photo_ChangePreset = 16;
        public const int Photo_SetPresetName = 17;
        public const int Photo_AbilityVarietyUp = 18;
        public const int Photo_ChangePhotoAbility = 19;
    }

    public static class Player
    {
        public const int Player_RecoverStaminaByJewel = 1;
        public const int Player_UpdateGameHintRead = 2;
        public const int Player_UpdateHomeDisplayPreference = 3;
        public const int Player_UpdateTutorial = 4;
        public const int Player_UpdateHomeLastTransitionTime = 5;
        public const int Player_SetHomeBGM = 6;
        public const int Player_ReleasePlayerRankCap = 7;
        public const int Player_UpdateCapedPlayerRankAnnounce = 8;
    }

    public static class Possessions
    {
        public const int Possessions_AddFavoriteStamp = 1;
        public const int Possessions_RemoveFavoriteStamp = 2;
    }

    public static class Posters
    {
        public const int Posters_Breakthrough = 1;
        public const int Posters_LevelUp = 2;
        public const int Posters_UpdateReleasedPosterStory = 3;
    }

    public static class Profile
    {
        public const int Profile_Edit = 1;
    }

    public static class Roulette
    {
        public const int Roulette_Roll = 1;
    }

    public static class SerialCodes
    {
        public const int SerialCodes_UseSerialCode = 1;
    }

    public static class Shops
    {
        public const int Shops_ExchangeMarketThing = 0;
        public const int Shops_ExchangeMarketThings = 1;
        public const int Shops_ExchangeMusic = 2;
        public const int Shops_ExchangeMusicScore = 3;
        public const int Shops_ExchangeShopThing = 4;
        public const int Shops_GetOrRefreshMarket = 5;
        public const int Shops_GetTotalPaymentThisMonth = 6;
        public const int Shops_Purchase = 7;
        public const int Shops_UpdateLastViewedAt = 8;
        public const int Shops_UpdateMarketWithJewel = 9;
        public const int Shops_ViewPage = 10;
        public const int Shops_ExchangePermanentMarketThings = 11;
    }

    public static class Spot
    {
        public const int Spot_Read = 1;
    }

}
