// <auto-generated />
#nullable enable
using MessagePack;
using MessagePack.Resolvers;

namespace Sirius.Protocol;

public static class SiriusMessagePack
{
    public static readonly MessagePackSerializerOptions StandardOptions = MessagePackSerializerOptions.Standard
        .WithResolver(CompositeResolver.Create(
            NativeDateTimeResolver.Instance,
            StandardResolver.Instance));

    public static readonly MessagePackSerializerOptions Lz4BlockArrayOptions = StandardOptions
        .WithCompression(MessagePackCompression.Lz4BlockArray);

    public static readonly MessagePackSerializerOptions Lz4BlockOptions = StandardOptions
        .WithCompression(MessagePackCompression.Lz4Block);

    public static byte[] Serialize<T>(T value, bool lz4 = false)
        => MessagePackSerializer.Serialize(value, lz4 ? Lz4BlockArrayOptions : StandardOptions);

    public static T Deserialize<T>(byte[] bytes, bool lz4 = false)
        => MessagePackSerializer.Deserialize<T>(bytes, lz4 ? Lz4BlockArrayOptions : StandardOptions);
}
