// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Constant;

public partial class RedisExpires
{
    public static TimeSpan MultiLiveMembersExpiry { get; set; } = default!;

    public static TimeSpan CircleGroupExpiry { get; set; } = default!;

    public static TimeSpan ChatExpiry { get; set; } = default!;

}
