// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.Payloads;

[MessagePackObject(false)]
public partial class MultiLiveRecruitingRoomTicketsPayload
{
    [Key(0)]
    public global::Sirius.Protocol.Realtime.Shared.Entity.MultiLive.MultiLiveRecruitingRoomTicket[] RoomTickets { get; set; } = default!;

}
