// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.Payloads;

[MessagePackObject(false)]
public partial class MultiLiveMatchMakingRebornPayload
{
    [Key(0)]
    public string[] GroupNames { get; set; } = default!;

}
