// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Accessories;

[MessagePackObject(false)]
public partial class Accessory : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long AccessoryMasterId { get; set; }

    [IgnoreMember]
    public global::Sirius.Protocol.Shared.Models.Master.AccessoryMaster AccessoryMaster { get; set; } = default!;

    [Key(2)]
    public int Level { get; set; }

    [Key(3)]
    public bool Locked { get; set; }

    [Key(4)]
    public long[] AccessoryEffects { get; set; } = default!;

    [Key(5)]
    public int ReferenceCounting { get; set; }

    [Key(6)]
    public bool IsFavorite { get; set; }

}
