// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Common;

[MessagePackObject(false)]
public partial class AlbumDetailEditParameters
{
    [Key(0)]
    public AlbumDetailEditItem[] Items { get; set; } = default!;

}
