// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Common;

[MessagePackObject(false)]
public partial class AlbumDetailEditItem
{
    [Key(0)]
    public long ItemId { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.AlbumItemTypes AlbumItemType { get; set; } = default!;

    [Key(2)]
    public string FileName { get; set; }

    [Key(3)]
    public string SasToken { get; set; }

    [Key(4)]
    public float X { get; set; }

    [Key(5)]
    public float Y { get; set; }

    [Key(6)]
    public float Rotate { get; set; }

    [Key(7)]
    public float Scale { get; set; }

    [Key(8)]
    public int Layer { get; set; }

    [Key(9)]
    public bool Visible { get; set; }

    [Key(10)]
    public bool Lock { get; set; }

    [Key(11)]
    public long? SignMasterId { get; set; }

}
