// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Common;

[MessagePackObject(false)]
public partial class AlbumSimpleEditPhoto
{
    [Key(0)]
    public long PhotoId { get; set; }

    [Key(1)]
    public string FileName { get; set; }

    [Key(2)]
    public string SasToken { get; set; }

    [Key(3)]
    public int Order { get; set; }

    [Key(4)]
    public long? SignMasterId { get; set; }

}
