// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Common;

[MessagePackObject(false)]
public partial class AlbumSimpleEditParameters
{
    [Key(0)]
    public AlbumSimpleEditPhoto[] Photos { get; set; } = default!;

}
