// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Common;

[MessagePackObject(false)]
public partial class HelpCategory
{
    [Key(0)]
    public string CategoryName { get; set; }

    [Key(1)]
    public HelpText[] HelpTexts { get; set; } = default!;

}
