// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Common;

[MessagePackObject(false)]
public partial class HelpDialog
{
    [Key(0)]
    public HelpCategory[] Categories { get; set; } = default!;

}
