// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Common;

[MessagePackObject(false)]
public partial class HelpText
{
    [Key(0)]
    public string Title { get; set; }

    [Key(1)]
    public int Order { get; set; }

    [Key(2)]
    public string Body { get; set; }

}
