// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.Common;

[MessagePackObject(false)]
public partial class MultiLiveInvitation
{
    [Key(0)]
    public string InviteId { get; set; }

    [Key(1)]
    public string UserName { get; set; }

    [Key(2)]
    public long CharacterMasterId { get; set; }

    [Key(3)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(4)]
    public int PlayerRank { get; set; }

    [Key(5)]
    public long? TrophyMasterId1 { get; set; }

    [Key(6)]
    public long? TrophyMasterId2 { get; set; }

    [Key(7)]
    public long? TrophyMasterId3 { get; set; }

    [Key(8)]
    public global::Sirius.Protocol.Realtime.Shared.MultiLiveTypes MultiLiveType { get; set; } = default!;

    [Key(9)]
    public string HallId { get; set; }

    [Key(10)]
    public int MemberCount { get; set; }

    [Key(11)]
    public global::System.DateTime InvitedAt { get; set; } = default!;

    [Key(12)]
    public long IconFrameMasterId { get; set; }

}
