// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Gacha;

[MessagePackObject(false)]
public partial class GachaSelectedThing : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long GachaMasterId { get; set; }

    [Key(1)]
    public long[] GachaThingIds { get; set; } = default!;

}
