// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Shops;

[MessagePackObject(false)]
public partial class ExchangeLimit : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long ExchangeShopThingId { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.ShopReplaceTypes ReplaceType { get; set; } = default!;

    [Key(3)]
    public int? SpecifiedNumberOfDaysLimit { get; set; }

    [Key(4)]
    public int ExchangedCount { get; set; }

    [Key(5)]
    public global::System.DateTime? Until { get; set; }

}
