// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Shops;

[MessagePackObject(false)]
public partial class JewelShop : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long JewelShopItemMasterId { get; set; }

    [Key(2)]
    public int PurchaseCount { get; set; }

    [Key(3)]
    public int TotalPurchaseCount { get; set; }

    [Key(4)]
    public global::System.DateTime? RePurchaseDate { get; set; }

}
