// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Shops;

[MessagePackObject(false)]
public partial class LoginPassStatus : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::System.DateTime ValidUntil { get; set; } = default!;

}
