// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Shops;

[MessagePackObject(false)]
public partial class PermanentMarketThing : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long PermanentMarketThingMasterId { get; set; }

    [Key(1)]
    public int PurchaseCount { get; set; }

}
