// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Shops;

[MessagePackObject(false)]
public partial class ViewedShop : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long? ExchangeShopMasterId { get; set; }

    [Key(2)]
    public global::System.DateTime LastViewedAt { get; set; } = default!;

    [Key(3)]
    public global::Sirius.Protocol.Shared.ViewedShopCategoryTypes ViewedShopCategory { get; set; } = default!;

}
