// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.Notification;

[MessagePackObject(false)]
public partial class MultiLiveRequestForFriendNotification
{
    [Key(0)]
    public string FriendUserId { get; set; }

    [Key(1)]
    public string HallId { get; set; }

    [Key(2)]
    public string UserId { get; set; }

    [Key(3)]
    public string RequestUserName { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Realtime.Shared.MultiLiveTypes MultiLiveType { get; set; } = default!;

}
