// <auto-generated />
#nullable enable
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public sealed class AccessoryAutoSellConvertThing
{
    [Key(0)]
    public long AccessoryMasterId { get; set; }

    [Key(1)]
    public ReceivedThing? ConvertThing { get; set; }
}
