// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class AccessoryFavoritePayload
{
    [Key(0)]
    public long AccessoryId { get; set; }

    [Key(1)]
    public bool SetFavorite { get; set; }

}
