// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class AccountRegistResult
{
    [Key(0)]
    public string Token { get; set; }

    [Key(1)]
    public AccountRegisterErrorTypes ErrorType { get; set; } = default!;

}
