// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class AccountConnectPayload
{
    [Key(0)]
    public AuthenticationProviders Provider { get; set; } = default!;

    [Key(1)]
    public string Token { get; set; }

}
