// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum AccountRegisterErrorTypes
{
    None = 0,
    NgWord = 1,
    TooManyRegistrations = 2,
}
