// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum AchievementRateGrades
{
    None = 0,
    C = 1,
    B = 2,
    A = 3,
    APlus = 4,
    S = 5,
    SPlus = 6,
    SS = 7,
    SSPlus = 8,
    SSS = 9,
}
