// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class AcquirableThingsPayload
{
    [Key(0)]
    public AcquirableThing[] Things { get; set; } = default!;

}
