// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ActorPortalCharacterPayload
{
    [Key(0)]
    public long CharacterBaseId { get; set; }

    [Key(1)]
    public long CharacterId { get; set; }

    [Key(2)]
    public bool IsAwakening { get; set; }

}
