// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class AlbumPageSearchResult
{
    [Key(0)]
    public AlbumPageResult AlbumPageResult { get; set; } = default!;

    [Key(1)]
    public bool IsSuccess { get; set; }

}
