// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class AlbumPageResult
{
    [Key(0)]
    public long AlbumPageId { get; set; }

    [Key(1)]
    public long AlbumId { get; set; }

    [Key(2)]
    public int Level { get; set; }

    [Key(3)]
    public int Page { get; set; }

    [Key(4)]
    public EditTypes EditType { get; set; } = default!;

    [Key(5)]
    public bool Publishing { get; set; }

    [Key(6)]
    public byte[] Items { get; set; } = default!;

    [Key(7)]
    public long? AlbumThemeMasterId { get; set; }

}
