// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class AlbumArrangingPayload
{
    [Key(0)]
    public bool Publishing { get; set; }

    [Key(1)]
    public int Page { get; set; }

    [Key(2)]
    public byte[] Items { get; set; } = default!;

    [Key(3)]
    public long? MAlbumThemeId { get; set; }

}
