// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum AnotherNotationTypes
{
    Shelved = 1,
    Defect = 2,
    Change = 3,
    Mysterious = 4,
    Madness = 5,
    Reproduction = 6,
    Another = 7,
    Easy = 8,
}
