// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum AsideLiveButtonTypes
{
    None = 0,
    TinyDreamFest = 1,
    ConcertStageSelect = 2,
    AnotherNotation = 3,
    Trial = 4,
}
