// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class AuditionClearedInformationParties
{
    [Key(0)]
    public AuditionClearParty[] Parties { get; set; } = default!;

    [Key(1)]
    public byte ClearedPhase { get; set; }

}
