// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class AuditionClearPartySlot
{
    [Key(0)]
    public int Position { get; set; }

    [Key(1)]
    public long CharacterMasterId { get; set; }

    [Key(2)]
    public int CharacterLevel { get; set; }

    [Key(3)]
    public int CharacterTalentStage { get; set; }

    [Key(4)]
    public int CharacterAwakeningPhase { get; set; }

    [Key(5)]
    public long? PosterMasterId { get; set; }

    [Key(6)]
    public int? PosterLevel { get; set; }

    [Key(7)]
    public int? PosterBreakthroughPhase { get; set; }

    [Key(8)]
    public long? AccessoryMasterId { get; set; }

    [Key(9)]
    public int? AccessoryLevel { get; set; }

    [Key(10)]
    public int StarRank { get; set; }

    [Key(11)]
    public int TalentStage { get; set; }

    [Key(12)]
    public long AwakeningPhase { get; set; }

    [Key(13)]
    public Status CurrentStatus { get; set; } = default!;

    [Key(14)]
    public bool CharacterDisplayAwakeningStatus { get; set; }

}
