// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class AuthenticatePayload
{
    [Key(0)]
    public string LoginToken { get; set; }

    [Key(1)]
    public GameVersions GameVersion { get; set; } = default!;

    [Key(2)]
    public string ApkHash { get; set; }

    [Key(3)]
    public string ApkApplicationSignature { get; set; }

    [Key(4)]
    public string ApplicationVersion { get; set; }

}
