// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class AuthenticateResult
{
    [Key(0)]
    public string Token { get; set; }

    [Key(1)]
    public BanLevels BanLevel { get; set; } = default!;

    [Key(2)]
    public global::System.DateTime? WarnedUntil { get; set; }

}
