// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum BanLevels
{
    Normal = 0,
    Warning = 1,
    Suspend = 2,
    Delete = 3,
}
