// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class BannerPayload
{
    [Key(0)]
    public string CircleHashedId { get; set; }

    [Key(1)]
    public long PosterMasterId { get; set; }

    [Key(2)]
    public float X1 { get; set; }

    [Key(3)]
    public float Y1 { get; set; }

    [Key(4)]
    public float X2 { get; set; }

    [Key(5)]
    public float Y2 { get; set; }

    [Key(6)]
    public int RotationAngle { get; set; }

    [Key(7)]
    public bool DisplayPosterString { get; set; }

    [Key(8)]
    public float BannerRatio { get; set; }

}
