// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum BannerDeleteConditionTypes
{
    BuyItem = 1,
    MissionClear = 2,
    TimeLimitedControl = 3,
}
