// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class BlockListResult
{
    [Key(0)]
    public FriendResult[] Results { get; set; } = default!;

}
