// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum BloomBonusTypes
{
    None = 0,
    EffectDuringLive = 1,
    StatusBonus = 2,
    GrantItem = 3,
}
