// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum BranchJudgeTypes
{
    None = 0,
    Equal = 1,
    MoreThan = 2,
    LessThan = 3,
}
