// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class BulkLevelUpPayload
{
    [Key(0)]
    public long CharacterId { get; set; }

    [Key(1)]
    public int Order { get; set; }

}
