// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CalculateTimeEventPayload
{
    [Key(0)]
    public long MusicMasterId { get; set; }

    [Key(1)]
    public long? SenseNotationMasterId { get; set; }

    [Key(2)]
    public long PartyId { get; set; }

    [Key(3)]
    public int VocalVersion { get; set; }

    [Key(4)]
    public bool IsStoryEventChallenge { get; set; }

}
