// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CalculateLessonTimeEventPayload
{
    [Key(0)]
    public long MusicMasterId { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

}
