// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ChangeNamePayload
{
    [Key(0)]
    public string Name { get; set; }

}
