// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ChangePhotoAbilityPayload
{
    [Key(0)]
    public long PhotoId { get; set; }

    [Key(1)]
    public long ItemMasterId { get; set; }

    [Key(2)]
    public long PhotoEffectTypeGroupMasterId { get; set; }

}
