// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ChangeVocalPayload
{
    [Key(0)]
    public long MusicMasterId { get; set; }

    [Key(1)]
    public int VocalVersion { get; set; }

}
