// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CharacterRarities
{
    Rare1 = 1,
    Rare2 = 2,
    Rare3 = 3,
    Rare4 = 4,
}
