// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CharacterAppearanceTypes
{
    FadeIn = 0,
    SlideInFromRight = 1,
    SlideInFromLeft = 2,
    SlideInFromBottom = 3,
}
