// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CharacterRarityProbability
{
    [Key(0)]
    public CharacterRarities Rarity { get; set; } = default!;

    [Key(1)]
    public double Probability { get; set; }

}
