// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CharacterLineupResult
{
    [Key(0)]
    public CharacterRarityProbability[] NormalProbabilities { get; set; } = default!;

    [Key(1)]
    public CharacterRarityProbability[] FixedProbabilities { get; set; } = default!;

    [Key(2)]
    public GachaLineupItemProbability[] NormalLineupItems { get; set; } = default!;

    [Key(3)]
    public GachaLineupItemProbability[] FixedLineupItems { get; set; } = default!;

}
