// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CharacterMissionCategoryTypes
{
    Live = 1,
    Enhancement = 2,
    TalentBloom = 3,
    Poster = 4,
    Other = 5,
}
