// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CharacterPointEventInformationResult
{
    [Key(0)]
    public long CurrentTotalPoint { get; set; }

    [Key(1)]
    public int? OverallRank { get; set; }

    [Key(2)]
    public int? CharacterRank { get; set; }

}
