// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CharacterProfileRestrictionItem
{
    Birthday = 1,
    Height = 2,
    School = 3,
    Grade = 4,
    SenseName = 5,
    SenseEffect = 6,
    EvoSenseName = 7,
    EvoSenseEffect = 8,
    Hobby = 9,
    Background = 10,
    CharacterVoice = 11,
    Description = 12,
}
