// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CharacterMissionTypes
{
    ExecutedLeaderSenseCount = 101,
    EnhancedCharacter = 102,
    GetInGacha = 103,
    TotalLevel = 104,
    CharacterEpisodeCount = 105,
    CharacterAppearedPosterCount = 106,
    ReleasedPosterStoryCount = 107,
}
