// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CharacterBaseStarPointResult
{
    [Key(0)]
    public long CharacterBaseMasterId { get; set; }

    [Key(1)]
    public StarPointResult StarPointResult { get; set; } = default!;

    [Key(2)]
    public ReceivedThing[] LinkCharacterReceivedReward { get; set; } = default!;

}
