// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CharacterSelectionTypes
{
    Primary = 1,
    Secondary = 2,
    Random = 99,
}
