// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CharacterLayerTypes
{
    None = 0,
    Layer1 = 1,
    Layer2 = 2,
    Layer3 = 3,
}
