// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CharacterPointEventRankingResult
{
    [Key(0)]
    public RawRankingWithLongPoint[] RawRanking { get; set; } = default!;

    [Key(1)]
    public UserProfile[] UserProfiles { get; set; } = default!;

}
