// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CharacterPositions
{
    None = 0,
    OuterLeft = 1,
    InnerLeft = 2,
    Center = 3,
    InnerRight = 4,
    OuterRight = 5,
}
