// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ChatworkSendMessagePayload
{
    [Key(0)]
    public string Message { get; set; }

}
