// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleAuthorityChangePayload
{
    [Key(0)]
    public string CircleHashedId { get; set; }

    [Key(1)]
    public string UserId { get; set; }

    [Key(2)]
    public CircleAuthorities Authority { get; set; } = default!;

}
