// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleSearchResult
{
    [Key(0)]
    public CircleMemberParameters[] Parameters { get; set; } = default!;

    [Key(1)]
    public CircleResultStatus ResultStatus { get; set; } = default!;

    [Key(2)]
    public CircleBanner CircleBanner { get; set; } = default!;

}
