// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CircleAuthorityResultStatus
{
    PermissionDenied = 1,
    DeputyLeaderFullJoin = 2,
    ChangeSuccess = 3,
    LeaderChangeSuccess = 4,
    DataNotFound = 5,
}
