// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CircleAuthorities
{
    None = 0,
    Member = 1,
    DeputyLeader = 2,
    Leader = 3,
}
