// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleProfile
{
    [Key(0)]
    public string CircleId { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public int MemberCount { get; set; }

    [Key(3)]
    public long MainCharacterMasterId { get; set; }

    [Key(4)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(5)]
    public long IconFrameMasterId { get; set; }

}
