// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleAuthorityResult
{
    [Key(0)]
    public CircleAuthorityResultStatus ResultStatus { get; set; } = default!;

}
