// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CircleDonateSupportCompanyResult
{
    Success = 0,
    ExceededQuantityReturned = 1,
    Error = 99,
}
