// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleInviteResult
{
    [Key(0)]
    public CircleResultStatus ResultStatus { get; set; } = default!;

    [Key(1)]
    public long? InviteId { get; set; }

}
