// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleInformationResult
{
    [Key(0)]
    public string UCircleHashedId { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Comment { get; set; }

    [Key(3)]
    public PlayTimeTypes PlayTimeStartType { get; set; } = default!;

    [Key(4)]
    public PlayTimeTypes PlayTimeEndType { get; set; } = default!;

    [Key(5)]
    public EntryTypes EntryType { get; set; } = default!;

    [Key(6)]
    public int MemberCount { get; set; }

    [Key(7)]
    public long InviteId { get; set; }

    [Key(9)]
    public CircleResultStatus ResultStatus { get; set; } = default!;

    [Key(10)]
    public CircleBanner CircleBanner { get; set; } = default!;

    [Key(11)]
    public long MainCharacterMasterId { get; set; }

    [Key(12)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(13)]
    public long? CompanyMasterId { get; set; }

    [Key(14)]
    public long? CharacterBaseMasterId { get; set; }

    [Key(15)]
    public long IconFameMasterId { get; set; }

}
