// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleRawRanking
{
    [Key(0)]
    public int Rank { get; set; }

    [Key(1)]
    public int Point { get; set; }

    [Key(2)]
    public string CircleId { get; set; }

}
