// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CircleResultStatus
{
    RequestIllegal = 1,
    LessThanNecessaryRank = 2,
    CanJoinCircle = 3,
    AlreadyJoinAnyCircle = 4,
    AlreadyInvite = 5,
    FreeEntry = 6,
    AlreadyRequest = 7,
    InviteSuccess = 8,
    PreRequestSuccess = 9,
    RequestSuccess = 10,
    ApproveSuccess = 11,
    JoinSuccess = 12,
    EditSuccess = 13,
    CreateSuccess = 14,
    ExpulsionSuccess = 15,
    ResignationSuccess = 16,
    ReleaseSuccess = 17,
    Error = 18,
    DataNotFound = 19,
    SearchSuccess = 20,
    CancelSuccess = 21,
    RejectSuccess = 22,
    NgWord = 23,
    MemberAmountUpperLimit = 24,
    InvalidParameter = 25,
    ReleaseFailureByEvent = 26,
}
