// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleResult
{
    [Key(0)]
    public CircleResultStatus ResultStatus { get; set; } = default!;

}
