// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleEventInformationResult
{
    [Key(0)]
    public long? CirclePoint { get; set; }

    [Key(1)]
    public long UserPoint { get; set; }

    [Key(2)]
    public long LastReceivedCirclePoint { get; set; }

    [Key(3)]
    public int MissionRefreshCount { get; set; }

    [Key(4)]
    public CircleEventCircleMissionProgress[] Progresses { get; set; } = default!;

}
