// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleEventRanking
{
    [Key(0)]
    public CircleRawRanking[] CircleRawRankings { get; set; } = default!;

    [Key(1)]
    public CircleProfile[] CircleProfiles { get; set; } = default!;

}
