// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CirclePayload
{
    [Key(0)]
    public string HashedId { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Comment { get; set; }

    [Key(3)]
    public PlayTimeTypes PlayTimeStartType { get; set; } = default!;

    [Key(4)]
    public PlayTimeTypes PlayTimeEndType { get; set; } = default!;

    [Key(5)]
    public EntryTypes EntryType { get; set; } = default!;

    [Key(6)]
    public SearchCircleMemberConditionTypes MemberType { get; set; } = default!;

    [Key(7)]
    public long? CompanyMasterId { get; set; }

    [Key(8)]
    public long? CharacterBaseMasterId { get; set; }

}
