// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleMemberParameters
{
    [Key(0)]
    public string UserId { get; set; }

    [Key(1)]
    public string UserName { get; set; }

    [Key(2)]
    public int PlayerRank { get; set; }

    [Key(3)]
    public global::System.DateTime LastLoginAt { get; set; } = default!;

    [Key(4)]
    public CircleAuthorities? Authority { get; set; }

    [Key(5)]
    [Obsolete]
    public MainCharacter MainUCharacter { get; set; } = default!;

    [Key(6)]
    public long? InviteId { get; set; }

    [Key(7)]
    public long? RequestId { get; set; }

    [Key(8)]
    public long TrophyMasterId1 { get; set; }

    [Key(9)]
    public long TrophyMasterId2 { get; set; }

    [Key(10)]
    public long TrophyMasterId3 { get; set; }

    [Key(11)]
    public long MainCharacterMasterId { get; set; }

    [Key(12)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(16)]
    public long IconFameMasterId { get; set; }

}
