// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleMemberInfoParameters : CircleMemberParameters
{
    [Key(13)]
    public decimal? PlayerRate { get; set; }

    [Key(14)]
    public bool IsPublicPlayerRate { get; set; }

    [Key(15)]
    public LeagueClassTypes LeagueClass { get; set; } = default!;

}
