// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CircleEventCircleMissionProgress
{
    [Key(0)]
    public long CircleEventMissionMasterId { get; set; }

    [Key(1)]
    public long CurrentCount { get; set; }

}
