// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CircleAuthorityUpdateTypes
{
    None = 0,
    Promotion = 1,
    Demotion = 2,
}
