// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum ClearLamps
{
    None = 0,
    Clear = 1,
    FullCombo = 2,
    FullComboMulti1 = 3,
    FullComboMulti2 = 4,
    FullComboMulti3 = 5,
    AllPerfect = 6,
    AllPerfectMulti1 = 7,
    AllPerfectMulti2 = 8,
    AllPerfectMulti3 = 9,
}
