// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum Companies
{
    None = 0,
    Sirius = 1,
    Eden = 2,
    Gingaza = 3,
    Denki = 4,
    LoveLiveSunshine = 900,
}
