// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ConcoursDetailInformationResult
{
    [Key(0)]
    public long ConcoursDetailMasterId { get; set; }

    [Key(1)]
    public int? Rank { get; set; }

}
