// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ConcoursInfomationResult
{
    [Key(0)]
    public ConcoursDetailInformationResult[] Details { get; set; } = default!;

    [Key(1)]
    public int CurrentPoint { get; set; }

}
