// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum ConditionUsableTableFilter
{
    DisplayRestriction = 1,
    Costume = 2,
    JewelShop = 4,
    ExchangeItem = 8,
    MusicShop = 16,
    Music = 32,
}
