// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ConvertedThingResult
{
    [Key(0)]
    public long ExchangeShopMasterId { get; set; }

    [Key(1)]
    public int OriginalQuantity { get; set; }

    [Key(2)]
    public ReceivedThing ReceivedThing { get; set; } = default!;

}
