// <auto-generated />
#nullable enable
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CostumeFavoritePayload
{
    [Key(0)]
    public long CostumeMasterId { get; set; }

    [Key(1)]
    public long CharacterBaseMasterId { get; set; }

    [Key(2)]
    public bool SetFavorite { get; set; }
}
