// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CourseResult
{
    [Key(0)]
    public decimal TotalAchievementRatePercentRecord { get; set; }

    [Key(1)]
    public int BestRecordChallengeCount { get; set; }

    [Key(2)]
    public global::System.DateTime BestRecordDate { get; set; } = default!;

}
