// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CourseRankingResult
{
    [Key(0)]
    public int Rank { get; set; }

    [Key(1)]
    public long UserId { get; set; }

    [Key(2)]
    public UserProfile UserProfile { get; set; } = default!;

    [Key(3)]
    public CourseResult CourseResult { get; set; } = default!;

    [Key(4)]
    public NoteResult NoteResult { get; set; } = default!;

}
