// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class CreateMultiRoomPayload
{
    [Key(0)] public string RoomName { get; set; } = string.Empty;
    [Key(1)] public string Password { get; set; } = string.Empty;
    [Key(2)] public int CanJoinMaxMember { get; set; }
    [Key(3)] public DateTime StartDate { get; set; }
    [Key(4)] public DateTime EndDate { get; set; }
    [Key(5)] public MultiRoomPlayModes PlayMode { get; set; }
    [Key(6)] public long LiveMasterId1 { get; set; }
    [Key(7)] public long? LiveMasterId2 { get; set; }
    [Key(8)] public long? LiveMasterId3 { get; set; }
}
