// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CustomLayoutUITypes
{
    None = 0,
    Image = 1,
    ImageButton = 2,
    GrayOutImageButton = 3,
    Button = 10,
    RedButton = 11,
    GrayOutButton = 12,
    GrayOutRedButton = 13,
    SpecialEventLogoWithDate = 20,
    ItemCountPanel = 21,
    Bgm = 90,
    TotalPointEvent_ScorePanel = 101,
    TotalPointEvent_RankingButton = 102,
}
