// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum CustomLayoutActionTypes
{
    None = 0,
    JumpType = 1,
    Hint = 2,
    Toast = 3,
}
