// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DebugPrepareLeagueGroupUserPayload
{
    [Key(0)]
    public long LeagueMasterId { get; set; }

    [Key(1)]
    public LeagueClassTypes ClassType { get; set; } = default!;

    [Key(2)]
    public long[] UserIds { get; set; } = default!;

}
