// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public partial class DebugUserIdResult
{
    [Key(0)]
    public string UserId { get; set; }

    [Key(1)]
    public string HashedUserId { get; set; }

}
