// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DebugModifyPosterEnhanceInformationPayload
{
    [Key(0)]
    public long MPosterId { get; set; }

    [Key(1)]
    public int Level { get; set; }

    [Key(2)]
    public int ReleasePhase { get; set; }

}
