// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DebugModifyCharacterEnhanceInformationPayload
{
    [Key(0)]
    public long MCharacterId { get; set; }

    [Key(1)]
    public int ActorLevel { get; set; }

    [Key(2)]
    public bool IsAwaken { get; set; }

    [Key(3)]
    public int SenseLevel { get; set; }

    [Key(4)]
    public int TalentBloomStage { get; set; }

}
