// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DebugEditLeagueBasicPayload
{
    [Key(0)]
    public LeagueClassTypes CurrentClassType { get; set; } = default!;

    [Key(1)]
    public LeagueClassTypes BestClassType { get; set; } = default!;

}
