// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DebugLinkageCodeResult
{
    [Key(0)]
    public string Password { get; set; }

    [Key(1)]
    public TakeOverCodeResult TakeOverCodeResult { get; set; } = default!;

}
