// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum DecorationCategories
{
    Special = 3,
    Seal = 20,
    Sticker = 30,
    SpeachBubble = 40,
    Effect = 50,
    Frame = 60,
    Comedy = 70,
    Text = 90,
    Other = 900,
}
