// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DeletedDataObject
{
    [Key(0)]
    public string TypeName { get; set; }

    [Key(1)]
    public long Id { get; set; }

}
