// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DetailEditItemPayload
{
    [Key(0)]
    public long ItemId { get; set; }

    [Key(1)]
    public AlbumItemTypes AlbumItemType { get; set; } = default!;

    [Key(2)]
    public int X { get; set; }

    [Key(3)]
    public int Y { get; set; }

    [Key(4)]
    public int Rotate { get; set; }

    [Key(5)]
    public float Scale { get; set; }

    [Key(6)]
    public int Layer { get; set; }

    [Key(7)]
    public bool Visible { get; set; }

    [Key(8)]
    public bool Lock { get; set; }

}
