// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DonateSupportCompanyResult
{
    [Key(0)]
    public MyCircleInformationResult MyCircleInformation { get; set; } = default!;

    [Key(1)]
    public CircleDonateSupportCompanyResult ResultStatus { get; set; } = default!;
}
