// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DonateSupportLevelLimitPayload
{
    [Key(0)]
    public Companies Company { get; set; } = default!;

    [Key(1)]
    public int NextLevelLimit { get; set; }

    [Key(2)]
    public int CoinQuantity { get; set; }

    [Key(3)]
    public DonateSupportLevelLimitDetail[] Details { get; set; } = default!;
}
