// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DonateSupportLevelLimitDetail
{
    [Key(0)]
    public int Order { get; set; }

    [Key(1)]
    public int Quantity { get; set; }
}
