// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DummyEditPositionPayloadArray
{
    [Key(0)]
    public EditPositionPayload[] Payloads { get; set; } = default!;

}
