// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DummyResponse
{
    [Key(0)]
    public Fault[] Fault { get; set; } = default!;

    [Key(1)]
    public IDataObject[] Added { get; set; } = default!;

    [Key(2)]
    public IDataObject[] Modified { get; set; } = default!;

    [Key(3)]
    public DeletedDataObject[] Deleted { get; set; } = default!;

    [Key(4)]
    public INotificationObject[] Notifications { get; set; } = default!;

    [Key(5)]
    public GachaInfoResult[] GachaInfoResults { get; set; } = default!;

    [Key(6)]
    public CircleInformationResult[] CircleInformationResults { get; set; } = default!;

    [Key(7)]
    public UseExperienceItemsPayload[] UseExperienceItemsPayloads { get; set; } = default!;

    [Key(8)]
    public LoginBonusResult[] LoginBonusResults { get; set; } = default!;

    [Key(9)]
    public NotificationResult[] NotificationResults { get; set; } = default!;

    [Key(10)]
    public LeaguePartyAndRankingResult[] LeaguePartyAndRankingResults { get; set; } = default!;

    [Key(11)]
    public GachaHistoryResult[] GachaHistoryResults { get; set; } = default!;

    [Key(12)]
    public EpisodeDetailResult[] EpisodeDetailResults { get; set; } = default!;

    [Key(13)]
    public global::Sirius.Protocol.Shared.Models.Common.HelpDialog HelpDialog { get; set; } = default!;

    [Key(14)]
    public BulkLevelUpPayload[] BulkLevelUpPayloads { get; set; } = default!;

    [Key(15)]
    public CharacterBaseStarPointResult[] CharacterBaseStarPointResults { get; set; } = default!;

    [Key(16)]
    public GeneratePhotoResult[] GeneratePhotoResults { get; set; } = default!;

    [Key(17)]
    public TripleCastPartyAndRankingResult[] TripleCastPartyAndRankingResults { get; set; } = default!;

    [Key(18)]
    public CourseRankingResult[] CourseRankingResults { get; set; } = default!;

    [Key(19)]
    public ScoreWithDateResult[] ScoreWithDateResults { get; set; } = default!;

}
