// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class DummyFriendResultArray
{
    [Key(0)]
    public FriendResult[] Payloads { get; set; } = default!;

}
