// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EditTrialPartyEventStagePartyPayloadSlot
{
    [Key(0)]
    public int Position { get; set; }

    [Key(1)]
    public long TrialPartyCharacterMasterId { get; set; }

    [Key(2)]
    public long? TrialPartyPosterMasterId { get; set; }

    [Key(3)]
    public long? TrialPartyAccessoryMasterId { get; set; }

}
