// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EditPartyPayload
{
    [Key(0)]
    public EditPartySlotPayload[] PartySlots { get; set; } = default!;

    [Key(1)]
    public long? SenseNotationMasterId { get; set; }

    [Key(2)]
    public long? MusicMasterId { get; set; }

    [Key(3)]
    public int? VocalVersion { get; set; }

    [Key(4)]
    public bool IsHighScoreChallenge { get; set; }

    [Key(5)]
    public int? LeaderPosition { get; set; }

}
