// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EditBookmarkPayload
{
    [Key(0)]
    public long MusicMasterId { get; set; }

    [Key(1)]
    public MusicBookmarkFlags BookmarkFlag { get; set; } = default!;

}
