// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EditPositionPayload
{
    [Key(0)]
    public EditPositionSlotPayload[] Slots { get; set; } = default!;

}
