// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EditPartySlotPayload
{
    [Key(0)]
    public long UPartySlotId { get; set; }

    [Key(1)]
    public long UCharacterId { get; set; }

    [Key(2)]
    public long? UAccessoryId { get; set; }

    [Key(3)]
    public long? UPosterId { get; set; }

    [Key(4)]
    public BonusAbilityEnableFlags BonusAbilityEnableFlags { get; set; } = default!;

}
