// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EditUserProfilePayload
{
    [Key(0)]
    public string Name { get; set; }

    [Key(1)]
    public string Introduction { get; set; }

    [Key(2)]
    [Obsolete("MainCharacterMasterId")]
    public long MainUCharacterId { get; set; }

    [Key(3)]
    public long? MNameplateId { get; set; }

    [Key(4)]
    public long MNameColorId { get; set; }

    [Key(5)]
    public long? MTrophyId1 { get; set; }

    [Key(6)]
    public long? MTrophyId2 { get; set; }

    [Key(7)]
    public long? MTrophyId3 { get; set; }

    [Key(8)]
    public bool IsPublicPlayerRate { get; set; }

    [Key(9)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(10)]
    public long MainCharacterMasterId { get; set; }

    [Key(11)]
    public long NameBaseColorMasterid { get; set; }

    [Key(12)]
    public long IconFrameMasterId { get; set; }

    [Key(13)]
    public long HomeSkinMasterId { get; set; }

}
