// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EditPositionSlotPayload
{
    [Key(0)]
    public long UPartySlotId { get; set; }

    [Key(1)]
    public int Position { get; set; }

}
