// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EditTrialPartyEventStagePartyPayload
{
    [Key(0)]
    public long TrialPartyEventStageMasterId { get; set; }

    [Key(1)]
    public EditTrialPartyEventStagePartyPayloadSlot[] Slots { get; set; } = default!;

    [Key(2)]
    public int LeaderPosition { get; set; }

}
