// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EexternalPaymentResult
{
    [Key(0)]
    public long[] ReceivedJewelShopItemMasterIds { get; set; } = default!;

}
