// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum EffectConditions
{
    CharacterBase = 1,
    Company = 2,
    Attribute = 3,
    SenseType = 4,
    Character = 5,
    EquippedPoster = 6,
    NeighborPosition = 7,
    CharacterBaseGroup = 8,
}
