// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EnvironmentResult
{
    [Key(0)]
    public string ApplicationVersion { get; set; }

    [Key(1)]
    public string AssetVersion { get; set; }

    [Key(2)]
    public string ApiEndpoint { get; set; }

    [Key(3)]
    public string MaintenanceApiEndpoint { get; set; }

    [Key(4)]
    public string NewsApiEndpoint { get; set; }

    [Key(5)]
    public bool IsMaintenance { get; set; }

    [Key(6)]
    public string MasterDataUrl { get; set; }

    [Key(7)]
    public string StaticContentUrl { get; set; }

    [Key(8)]
    public string AssetUrl { get; set; }

    [Key(9)]
    public bool IsAppReview { get; set; }

    [Key(10)]
    public string PhotoContentUrl { get; set; }

    [Key(11)]
    public string MultiRealTimeServerUrl { get; set; }

    [Key(12)]
    public string ExternalPaymentUrl { get; set; }

}
