// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EpisodeDetailResult
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long EpisodeMasterId { get; set; }

    [Key(2)]
    public int Order { get; set; }

    [Key(3)]
    public int GroupOrder { get; set; }

    [Key(4)]
    public string Effect { get; set; }

    [Key(5)]
    public string SpeakerName { get; set; }

    [Key(6)]
    public FontSizes FontSize { get; set; } = default!;

    [Key(7)]
    public string Phrase { get; set; }

    [Key(8)]
    public string Title { get; set; }

    [Key(9)]
    public string BackgroundImageFileName { get; set; }

    [Key(10)]
    public string BackgroundCharacterImageFileName { get; set; }

    [Key(11)]
    public FadeTypes? BackgroundImageFileFadeType { get; set; }

    [Key(21)]
    public float? FadeValue1 { get; set; }

    [Key(22)]
    public float? FadeValue2 { get; set; }

    [Key(23)]
    public float? FadeValue3 { get; set; }

    [Key(12)]
    public string BgmFileName { get; set; }

    [Key(13)]
    public string SeFileName { get; set; }

    [Key(14)]
    public string StillPhotoFileName { get; set; }

    [Key(15)]
    public string MovieFileName { get; set; }

    [Key(16)]
    public WindowEffects? WindowEffect { get; set; }

    [Key(17)]
    public long? SceneCameraMasterId { get; set; }

    [Key(18)]
    public string VoiceFileName { get; set; }

    [Key(19)]
    public EpisodeDetailCharacterMotionResult[] CharacterMotions { get; set; } = default!;

    [Key(20)]
    public string SpeakerIconId { get; set; }

}
