// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EpisodeResult
{
    [Key(0)]
    public string EpisodeTitle { get; set; }

    [Key(1)]
    public StoryTypes StoryType { get; set; } = default!;

    [Key(2)]
    public int EpisodeOrder { get; set; }

    [Key(3)]
    public string EpisodeDetailAssetSource { get; set; }

}
