// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EpisodeDetailCharacterMotionResult
{
    [Key(0)]
    public int SlotNumber { get; set; }

    [Key(1)]
    public long? FacialExpressionMasterId { get; set; }

    [Key(2)]
    public long? HeadMotionMasterId { get; set; }

    [Key(3)]
    public long? HeadDirectionMasterId { get; set; }

    [Key(4)]
    public long? BodyMotionMasterId { get; set; }

    [Key(5)]
    public long? LipSyncMasterId { get; set; }

    [Key(6)]
    public long SpineId { get; set; }

    [Key(7)]
    public CharacterAppearanceTypes? CharacterAppearanceType { get; set; }

    [Key(8)]
    public CharacterPositions CharacterPosition { get; set; } = default!;

    [Key(9)]
    public CharacterLayerTypes CharacterLayerType { get; set; } = default!;

    [Key(10)]
    public SpineSizes SpineSize { get; set; } = default!;

}
