// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum EpisodeReleaseConditionTypes
{
    TotalRankInCompany = 1,
    CharacterRank = 2,
}
