// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum EventStoryListFlags
{
    Sirius = 1,
    Eden = 2,
    Gingaza = 4,
    Denki = 8,
    LoveLiveSunshine = 512,
    YuruCamp = 1024,
    GirlsUndPanzer = 2048,
}
