// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EventResult
{
    [Key(0)]
    public int? AcquiredEventPoint { get; set; }

    [Key(1)]
    public long? AttachedStoryEventMasterId { get; set; }

    [Key(2)]
    public long? CircleEventHighScore { get; set; }

    [Key(3)]
    public int? CircleEventHighScoreMultiplierPercent { get; set; }

    [Key(4)]
    public long? CircleEventBeforeHighScore { get; set; }

    [Key(5)]
    public long? HighScoreBefore { get; set; }

    [Key(6)]
    public long? HighScoreAfter { get; set; }

    [Key(7)]
    public long BeforeRank { get; set; }

    [Key(8)]
    public long AfterRank { get; set; }

    [Key(9)]
    public long? StoryEventMasterId { get; set; }

    [Key(10)]
    public long? EventMasterId { get; set; }

}
