// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class EventBoxGachaRollResult
{
    [Key(0)]
    public ReceivedThing[] ReceivedThings { get; set; } = default!;

    [Key(1)]
    public bool HasReset { get; set; }

    [Key(2)]
    public long[] DrawnEventBoxGachaBoxThingMasterIds { get; set; } = default!;

}
