// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum EventTypes
{
    StoryEvent = 20,
    SpecialEvent = 21,
    CharacterBasePoint = 22,
    AnotherNotation = 23,
    CircleEvent = 24,
    RouletteEvent = 25,
    Concert = 30,
    CourseMode = 31,
    DugongRun = 32,
    Trial = 33,
    Concours = 34,
}
