// <auto-generated />
#nullable enable
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ExchangeShopThingPayload
{
    [Key(0)]
    public long MExchangeShopThingId { get; set; }

    [Key(1)]
    public int Quantity { get; set; }
}
