// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum FadeTypes
{
    BlackFadeOutFadeIn = 1,
    WhiteFadeOutFadeIn = 2,
    TimeElapsed = 3,
    CrossFade = 4,
}
