// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class Fault
{
    [Key(0)]
    public string ErrorCode { get; set; }

    [Key(1)]
    public string Message { get; set; }

    [Key(2)]
    public string StackTrace { get; set; }

}
