// <auto-generated />
#nullable enable
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class FavoriteStampOrderPayload
{
    [Key(0)]
    public long[] StampMasterIds { get; set; } = System.Array.Empty<long>();
}
