// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum FeatureMaintenanceScopes
{
    Audition = 1,
    League = 2,
    MultiLive = 3,
    Inbox = 4,
    Gacha = 5,
    Shop = 6,
    Friends = 7,
    Circle = 8,
    CommonHub = 9,
    TripleCast = 10,
    WebShop = 11,
}
