// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class FinishLiveResult
{
    [Key(1)]
    public ReceivedThing[] LeagueRewards { get; set; } = default!;

    [Key(2)]
    public RateResult RateResult { get; set; } = default!;

    [Key(3)]
    public PlayerRankPointResult PlayerRankPointResult { get; set; } = default!;

    [Key(5)]
    public ClearLamps ClearLamp { get; set; } = default!;

    [Key(6)]
    public AchievementRateGrades RateGrade { get; set; } = default!;

    [Key(8)]
    public bool IsHighScore { get; set; }

    [Key(9)]
    public byte AuditionBeforePhase { get; set; }

    [Key(10)]
    public byte AuditionAfterPhase { get; set; }

    [Key(11)]
    public ReceivedThing[] AuditionRewards { get; set; } = default!;

    [Key(12)]
    public ReceivedThing[] StoryEventRewards { get; set; } = default!;

    [Key(13)]
    public double AchievementRateAverage { get; set; }

    [Key(14)]
    public long? AuditionMasterId { get; set; }

    [Key(16)]
    public SpRateUpdateResult SpRateUpdateResult { get; set; } = default!;

    [Key(17)]
    public TournamentResult TournamentResult { get; set; } = default!;

    [Key(18)]
    public int? CellingMaxCount { get; set; }

    [Key(19)]
    public int? CellingUserCount { get; set; }

    [Key(20)]
    public ClearLamps BeforeClearLamp { get; set; } = default!;

    [Key(21)]
    public int PosterDropUpPercent { get; set; }

    [Key(22)]
    public EventResult EventResult { get; set; } = default!;

    [Key(23)]
    public LiveDropThing[] LiveDropThings { get; set; } = default!;

    [Key(24)]
    public LessonResult LessonResult { get; set; } = default!;

    [Key(25)]
    public LeagueResult LeagueResult { get; set; } = default!;

    [Key(26)]
    public ConcertResult ConcertResult { get; set; } = default!;

    [Key(27)]
    public BonusLiveResult BonusLiveResult { get; set; } = default!;

    [Key(28)]
    public GhostLiveResult GhostLiveResult { get; set; } = default!;

    [Key(29)]
    public TrialPartyEventResult TrialPartyEventResult { get; set; } = default!;

    [Key(30)]
    public AccessoryAutoSellConvertThing[] AccessoryAutoSellConvertThings { get; set; } = default!;

}
