// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class FinishLessonPayload
{
    [Key(0)]
    public long Score { get; set; }

    [Key(1)]
    public int MaxCombo { get; set; }

    [Key(2)]
    public NoteJudgePayload[] Judges { get; set; } = default!;

}
