// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class FinishTeamChallengeSessionPayload
{
    [Key(0)]
    public string RoomId { get; set; }

}
