// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class FinishAnotherNotationLivePayload
{
    [Key(0)]
    public global::Sirius.Protocol.Shared.Models.Lives.BaseScoreBlock[] BaseScoreBlocks { get; set; } = default!;

    [Key(1)]
    public global::Sirius.Protocol.Shared.Models.Lives.SenseScoreBlock[] SenseScoreBlocks { get; set; } = default!;

    [Key(2)]
    public global::Sirius.Protocol.Shared.Models.Lives.StarActScoreBlock[] StarActScoreBlocks { get; set; } = default!;

    [Key(3)]
    public global::Sirius.Protocol.Shared.Models.Lives.MultiLiveAdditionalScoreBlock[] MultiLiveAdditionalScoreBlocks { get; set; } = default!;

    [Key(4)]
    public long AnotherNotationMasterId { get; set; }

    [Key(5)]
    public bool IsAutoPlay { get; set; }

}
