// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class FinishLivePayload
{
    [Key(0)]
    public long Score { get; set; }

    [Key(1)]
    public int MaxCombo { get; set; }

    [Key(2)]
    public NoteJudgePayload[] Judges { get; set; } = default!;

    [Key(3)]
    public bool IsCleared { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.Models.Lives.BaseScoreBlock[] BaseScoreBlocks { get; set; } = default!;

    [Key(5)]
    public global::Sirius.Protocol.Shared.Models.Lives.SenseScoreBlock[] SenseScoreBlocks { get; set; } = default!;

    [Key(6)]
    public global::Sirius.Protocol.Shared.Models.Lives.StarActScoreBlock[] StarActScoreBlocks { get; set; } = default!;

    [Key(7)]
    public global::Sirius.Protocol.Shared.Models.Lives.MultiLiveAdditionalScoreBlock[] MultiLiveAdditionalScoreBlocks { get; set; } = default!;

    [Key(8)]
    public TripleCastPartyScore[] TripleCastPartyScores { get; set; } = default!;

    [Key(9)]
    public TrialPartyEventStageResult TrialPartyEventStageResult { get; set; } = default!;

}
