// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum FireTimingTypes
{
    StarAct = 1,
    Sense = 2,
    StartLive = 3,
    Passive = 4,
}
