// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class FlashSaleReadStagePayload
{
    [Key(0)]
    public long[] ReadFlashSaleStageIds { get; set; } = default!;

}
