// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum FrameLotConditionTypes
{
    None = 0,
    ConsumeStamina = 1,
    ScoreWithConsumeStamina = 2,
    StarActCountWithConsumeStamina = 3,
    AchievementRateWithConsumeStamina = 4,
}
