// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum FriendRequestResultStatus
{
    RequestSuccess = 1,
    IsFriends = 2,
    IsApplying = 3,
    IsMySelf = 4,
    DataNotFound = 5,
    IsFriendCountLimit = 6,
}
