// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum FriendAcceptResultStatus
{
    AcceptSuccess = 1,
    RequestUserFriendsLimitOver = 2,
    AcceptUserFriendsLimitOver = 3,
    Canceled = 4,
}
