// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum FriendSearchResultStatus
{
    Friend = 1,
    Request = 2,
    None = 3,
    User = 4,
    ReceivedRequest = 5,
}
