// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class FriendResult
{
    [Key(0)]
    public string UserId { get; set; }

    [Key(2)]
    public int PlayerRank { get; set; }

    [Key(3)]
    public long TrophyMasterId1 { get; set; }

    [Key(4)]
    public long TrophyMasterId2 { get; set; }

    [Key(5)]
    public long TrophyMasterId3 { get; set; }

    [Key(6)]
    public string Introduction { get; set; }

    [Key(7)]
    public global::System.DateTime LastLoggedInAt { get; set; } = default!;

    [Key(8)]
    public string Name { get; set; }

    [Key(9)]
    public double? PlayerRate { get; set; }

    [Key(10)]
    public bool IsPublicPlayerRate { get; set; }

    [Key(11)]
    public LeagueClassTypes LeagueClass { get; set; } = default!;

    [Key(12)]
    public CharacterRank[] CharacterRanks { get; set; } = default!;

    [Key(13)]
    public bool IsPublicAlbumMainPage { get; set; }

    [Key(15)]
    public long MainCharacterMasterId { get; set; }

    [Key(16)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(17)]
    public long IconFrameMasterId { get; set; }

    [Key(18)]
    public bool IsFavorite { get; set; }

}
