// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class FriendListResult
{
    [Key(0)]
    public FriendResult[] Results { get; set; } = default!;

    [Key(1)]
    public int CurrentFriendCount { get; set; }

}
