// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class FriendSearchResult
{
    [Key(0)]
    public FriendResult FriendResult { get; set; } = default!;

    [Key(1)]
    public FriendSearchResultStatus ResultStatus { get; set; } = default!;

}
