// <auto-generated />
#nullable enable
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public sealed class FriendFavoritePayload
{
    [Key(0)]
    public string TargetUserId { get; set; } = string.Empty;

    [Key(1)]
    public bool SetFavorite { get; set; }
}
