// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class FriendInvitationUserInfoResult
{
    [Key(0)]
    public string HashedUserId { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public long PlayerRank { get; set; }

    [Key(3)]
    public InvitationCodeResultStatuses ResultStatus { get; set; } = default!;

}
