// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class FriendRequestResult
{
    [Key(0)]
    public FriendRequestResultStatus ResultStatus { get; set; } = default!;

}
