// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum GachaButtonTypes
{
    PaidJewelTenSeries = 1,
    FreeJewelTenSeries = 2,
    PaidJewelSingle = 3,
    FreeJewelSingle = 4,
    SingleTicket = 5,
    SingleTicketTenSeries = 6,
    TenSeriesTicket = 7,
}
