// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GachaRollResult
{
    [Key(0)]
    public long MGachaMasterId { get; set; }

    [Key(1)]
    public GachaThingResult[] ReceivedThings { get; set; } = default!;

    [Key(2)]
    public ReceivedThing[] ReceivedBonusThings { get; set; } = default!;

    [Key(3)]
    public ReceivedThing[] ReceivedDetailBonusThings { get; set; } = default!;

    [Key(4)]
    public ReceivedThing[] ReceivedRollBonusThings { get; set; } = default!;

}
