// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum GachaUnlockTypes
{
    None = 0,
    TimeLimitedControl = 1,
    GachaComplete = 2,
}
