// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum GachaGroupTypes
{
    None = 0,
    Pickup = 1,
    Actor = 2,
    Poster = 3,
}
