// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum GachaTypes
{
    Pickup = 1,
    SpecialTicket = 2,
    Rare4Fixed = 3,
    NotPossessedRare4Fixed = 4,
    Selection = 5,
    Stepup = 6,
    PickupSelection = 7,
    Stationary = 8,
    ReRoll = 9,
}
