// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GachaInfoResult
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public GachaRollLimit[] RollLimits { get; set; } = default!;

    [Key(2)]
    public GachaEmissionFlags NormalEmissionFlags { get; set; } = default!;

    [Key(3)]
    public GachaEmissionFlags FixedEmissionFlags { get; set; } = default!;

}
