// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GachaHistoryResult
{
    [Key(0)]
    public long MasterId { get; set; }

    [Key(1)]
    public global::System.DateTime CreatedAt { get; set; } = default!;

}
