// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GachaRollLimit
{
    [Key(0)]
    public long GachaDetailMasterId { get; set; }

    [Key(1)]
    public int RollLeft { get; set; }

}
