// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GachaLineupItemProbability
{
    [Key(0)]
    public long Id { get; set; }

    [Key(2)]
    public double Probability { get; set; }

}
