// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GeneratePhotoPayload
{
    [Obsolete("Use AppearedCharacters")]
    [Key(0)]
    public long? CharacterBaseMasterId { get; set; }

    [Key(1)]
    public long ItemMasterId { get; set; }

    [Key(2)]
    public byte[] ImageData { get; set; } = default!;

    [Key(3)]
    public byte[] ThumbnailImageData { get; set; } = default!;

    [Key(4)]
    public PhotoAppearedCharacter[] AppearedCharacters { get; set; } = default!;

}
