// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum GenericContentBodyTypes
{
    Introduction = 1,
    MediumHeader = 2,
    SmallHeader = 3,
    BodyTextLeftAligned = 4,
    BodyTextCentering = 5,
    BodyImage = 6,
    LinkText = 7,
}
