// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GeneratePhotoResult
{
    [Key(0)]
    public long PhotoId { get; set; }

    [Key(1)]
    public string FileName { get; set; }

    [Key(2)]
    public string SasToken { get; set; }

    [Key(3)]
    public PhotoRarities Rarity { get; set; } = default!;

    [Key(4)]
    public long? SignMasterId { get; set; }

    [Key(5)]
    public long? PhotoEffectMasterId { get; set; }

}
