// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GeneratePhotosPayload
{
    [Key(0)]
    public GeneratePhotoPayload[] Payloads { get; set; } = default!;

}
