// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GenerateLotteryResultPayload
{
    [Key(0)]
    public int Prize { get; set; }

    [Key(1)]
    public int Amount { get; set; }

}
