// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GetPushNotificationTokenPayload
{
    [Key(0)]
    public string HashUserId { get; set; }

}
