// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GetPushNotificationTokenResult
{
    [Key(0)]
    public string PushNotificationToken { get; set; }

}
