// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GhostLiveInfo
{
    [Key(0)]
    public int LeaderPosition { get; set; }

    [Key(1)]
    public PartySlotDetail[] PartySlot { get; set; } = default!;

}
