// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class GhostLiveResult
{
    [Key(0)]
    public UserProfileDetail GhostUserProfile { get; set; } = default!;

    [Key(1)]
    public long GhostUserScore { get; set; }

    [Key(2)]
    public long TotalBattleWinCount { get; set; }

    [Key(3)]
    public MatchingResult MatchingResult { get; set; } = default!;

    [Key(4)]
    public long DisplayCharacterMasterId { get; set; }

    [Key(5)]
    public bool DisplayCharacterAwakeningStatus { get; set; }

}
