// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class HighScoreBuff
{
    [Key(0)]
    public string UserId { get; set; }

    [Key(1)]
    public HighScoreBuffSetting[] Buffs { get; set; } = default!;

}
