// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum HighScoreTypes
{
    Normal = 0,
    Multi = 1,
    TheaterLeague = 2,
    Audition = 3,
}
