// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class HighScoreBuffSetting
{
    [Key(0)]
    public long StoryEventHighScoreBuffSettingId { get; set; }

    [Key(1)]
    public int CurrentLevel { get; set; }

}
