// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class HighScoreParty
{
    [Key(0)]
    public string UserId { get; set; }

    [Key(1)]
    public string UserName { get; set; }

    [Obsolete]
    [Key(2)]
    public string PartyName { get; set; }

    [Key(3)]
    public HighScorePartySlot[] Slots { get; set; } = default!;

    [Key(4)]
    public MusicDifficulties Difficulty { get; set; } = default!;

    [Key(5)]
    public int LeaderPosition { get; set; }

}
