// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum HomeCharacterMotion
{
    Idle = 0,
    Motion01 = 1,
    Motion02 = 2,
    Motion03 = 3,
    Motion04 = 4,
    Motion05 = 5,
    Motion06 = 6,
    Motion07 = 7,
    Motion08 = 8,
    Motion09 = 9,
    Motion10 = 10,
}
