// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum HomeCharacterVoiceSetTypes
{
    Home = 1,
    Live = 2,
    Story = 3,
    Party = 4,
    Shop = 5,
}
