// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum HomeCharacterVoicePlayPeriod
{
    PlayerBirthDay = 0,
    CharacterBirthDay = 1,
    NewYear = 2,
    ValentineDay = 3,
    GoldenWeek = 4,
    HalloWeen = 5,
    Christmas = 6,
    EndOfYear = 7,
    SeasonWinter = 8,
    SeasonSpring = 9,
    SeasonRainy = 10,
    SeasonSummer = 11,
    SeasonAutumn = 12,
}
