// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class InboxReceiveResult
{
    [Key(0)]
    public ReceivedThing[] ReceivedThings { get; set; } = default!;

    [Key(1)]
    public bool HasNotReceiveThings { get; set; }

}
