// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[Union(0, typeof(global::Sirius.Protocol.Shared.Notifications.MissionCleared))]
[Union(2, typeof(global::Sirius.Protocol.Shared.Notifications.AcceptFriendRequest))]
[Union(3, typeof(global::Sirius.Protocol.Shared.Notifications.MultiLiveRestriction))]
[Union(1, typeof(global::Sirius.Protocol.Shared.Notifications.FriendRequest))]
public partial interface INotificationObject
{
}
