// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum InvitationCodeResultStatuses
{
    Success = 0,
    InvalidInvitationCode = 1,
    OwnInvitationCode = 2,
    InviteUserNotFound = 3,
}
