// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class InviteMultiRoomPayload
{
    [Key(0)] public string[] HashedUserIds { get; set; } = Array.Empty<string>();
}
