// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum ItemCategories
{
    StaminaRecovery = 11,
    CharacterLevel = 12,
    ConsumeItem = 13,
    TalentBloom = 14,
    CharacterMission = 16,
    GachaTicket = 21,
    ExchangeTicket = 22,
    RouletteBall = 31,
    ScratchCoin = 32,
    GachaPoint = 41,
    EventPoint = 42,
    MissionPassPoint = 43,
    Film = 51,
    AlbumSkin = 52,
    PlayerRankAwakening = 61,
    LessonPartyQuantityLimitRelease = 62,
}
