// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum JewelShopUnlockTypes
{
    ReadStory = 2,
    RateReached = 8,
    ClassReached = 9,
    BuyJewelShopItem = 15,
    PlayerRank = 16,
    TimeLimitedControl = 18,
    FlashSale = 19,
}
