// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class JoinMultiRoomPayload
{
    [Key(0)] public string HashedRoomId { get; set; } = string.Empty;
    [Key(1)] public string Password { get; set; } = string.Empty;
}
