// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum JumpTypes
{
    None = 0,
    Information = 1,
    Shop = 2,
    JewelShop = 3,
    Gacha = 4,
    Event = 5,
    Live = 6,
    Member = 7,
    Photo = 8,
    Story = 9,
    WebLink = 10,
    BeginnerMission = 11,
    MusicShop = 12,
    Spot = 13,
    Mission = 14,
    Concert = 15,
    StarRank = 16,
    Episode = 17,
    SpecialEvent = 18,
    TotalPointEventRanking = 19,
    BoxGacha = 20,
    TournamentEventTop = 21,
    Lesson = 22,
    League = 23,
}
