// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum LeagueClassTypes
{
    None = 0,
    Rookie = 1,
    Hope = 2,
    Cast = 3,
    Elite = 4,
    Veteran = 5,
    Star = 6,
    DaiStar = 7,
}
