// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LeaguePartyAndRankingResult
{
    [Key(0)]
    public int? Rank { get; set; }

    [Key(1)]
    public string UserId { get; set; }

    [Key(2)]
    public long BestScore { get; set; }

    [Key(3)]
    public long LeagueMasterId { get; set; }

    [Key(4)]
    public LeagueClassTypes ClassType { get; set; } = default!;

    [Key(5)]
    public string UserName { get; set; }

    [Key(6)]
    public int ActingAbility { get; set; }

    [Key(7)]
    public LeaguePartySlotResult[] Slots { get; set; } = default!;

    [Key(8)]
    public MusicDifficulties Difficulty { get; set; } = default!;

}
