// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LeagueResult
{
    [Key(0)]
    public int? BeforeGroupRanking { get; set; }

    [Key(1)]
    public int AfterGroupRanking { get; set; }

    [Key(2)]
    public long? LowestUpBorderScore { get; set; }

    [Key(3)]
    public long? LowestKeepBorderScore { get; set; }

    [Key(4)]
    public int EnrolledGroupNumber { get; set; }

    [Key(5)]
    public bool IsInCounting { get; set; }

}
