// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LeagueReceiveResults
{
    [Key(0)]
    public ReceivedThing[] ClassRewardReceivedThings { get; set; } = default!;

    [Key(1)]
    public LeagueClassChangeTypes ClassRewardType { get; set; } = default!;

    [Key(2)]
    public ReceivedThing[] FirstAchieveReceivedThings { get; set; } = default!;

    [Key(3)]
    public ReceivedThing[] GroupRankReceivedThings { get; set; } = default!;

    [Key(4)]
    public bool IsFirstTimeEnrolledClass { get; set; }

    [Key(5)]
    public ReceivedThing[] AllClassGlobalRankReceivedThings { get; set; } = default!;

}
