// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum LeagueClassChangeTypes
{
    None = 0,
    Up = 1,
    Keep = 2,
    Down = 3,
}
