// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LeagueTopMenuInformationResult
{
    [Key(0)]
    public global::System.DateTime DisplayStartAt { get; set; } = default!;

    [Key(1)]
    public global::System.DateTime CountingStartAt { get; set; } = default!;

    [Key(2)]
    public global::System.DateTime DisplayEndAt { get; set; } = default!;

    [Key(3)]
    public long MusicMasterId { get; set; }

    [Key(6)]
    public int LeagueGroupRanking { get; set; }

    [Key(8)]
    public long? UpClassBorderScore { get; set; }

    [Key(9)]
    public int? UpClassBorderRanking { get; set; }

    [Key(10)]
    public long? KeepClassBorderScore { get; set; }

    [Key(11)]
    public int? KeepClassBorderRanking { get; set; }

    [Key(12)]
    public int? GroupLowestRank { get; set; }

    [Key(13)]
    public bool IsParticipated { get; set; }

    [Key(14)]
    public int? EnrolledGroupNumber { get; set; }

}
