// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LeaguePartySlotResult
{
    [Key(0)]
    public int SlotPosition { get; set; }

    [Key(1)]
    public long CharacterMasterId { get; set; }

    [Key(2)]
    public Attributes Attribute { get; set; } = default!;

    [Key(4)]
    public CharacterRarities CharacterRarity { get; set; } = default!;

    [Key(6)]
    public int CharacterLevel { get; set; }

    [Key(7)]
    public long? PosterMasterId { get; set; }

    [Key(8)]
    public PossessionRarities? PosterRarity { get; set; }

    [Key(9)]
    public int? PosterLevel { get; set; }

    [Key(10)]
    public int? PosterBreakthroughPhase { get; set; }

    [Key(11)]
    public long? AccessoryMasterId { get; set; }

    [Key(12)]
    public PossessionRarities? AccessoryRarity { get; set; }

    [Key(13)]
    public int? AccessoryLevel { get; set; }

    [Key(14)]
    public Status CurrentStatus { get; set; } = default!;

    [Key(15)]
    public int Position { get; set; }

    [Key(16)]
    public int CharacterTalentStage { get; set; }

    [Key(17)]
    public int CharacterAwakeningPhase { get; set; }

    [Key(18)]
    public bool CharacterDisplayAwakeningStatus { get; set; }

}
