// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LessonResult
{
    [Key(0)]
    public long CharacterBaseMasterId { get; set; }

    [Key(1)]
    public StarPointResult StarPointResult { get; set; } = default!;

    [Key(2)]
    public ReceivedThing[] HighScoreRewards { get; set; } = default!;

    [Key(3)]
    public long HighScoreBefore { get; set; }

    [Key(4)]
    public long HighScoreAfter { get; set; }

}
