// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LevelUpPhotoResult
{
    [Key(0)]
    public long PhotoId { get; set; }

    [Key(1)]
    public int BeforeLevel { get; set; }

    [Key(2)]
    public int AfterLevel { get; set; }

}
