// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum LiveTypes
{
    Normal = 1,
    Multi = 2,
    Lesson = 3,
    Audition = 4,
    League = 5,
    MultiCollectionEvent = 6,
    Concert = 7,
    BonusLive = 8,
    CourseMode = 9,
    TripleCast = 10,
    GhostLive = 11,
    Trial = 12,
}
