// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LiveDropThing
{
    [Key(0)]
    public ReceivedThing ReceivedThing { get; set; } = default!;

    [Key(1)]
    public long Order { get; set; }

    [Key(2)]
    public LiveDropTypes LiveDropType { get; set; } = default!;

    [Key(3)]
    public bool IsFixedDrop { get; set; }

}
