// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum LiveUnlockConditionTypes
{
    None = 0,
    ExtraGoodCount = 13,
    NotationShop = 14,
}
