// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum LiveScheduleEndDateDisplayType
{
    None = 0,
    EndDate = 1,
    AdditionalEndDate = 2,
}
