// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum LoginBonusSpineSelectType
{
    Random = 1,
    HomeCharacterBaseId = 2,
    SelectedSpineCostume = 3,
}
