// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum LoginPassNotificationTypes
{
    None = 0,
    Purchasable = 1,
    Invalided = 2,
}
