// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LoginBonusDetail
{
    [Key(0)]
    public ThingTypes ThingType { get; set; } = default!;

    [Key(1)]
    public long ThingId { get; set; }

    [Key(2)]
    public int ThingQuantity { get; set; }

    [Key(3)]
    public int LoginCount { get; set; }

}
