// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LoginResult
{
    [Key(0)]
    public StarPassTypes[] InvalidedStarPasses { get; set; } = default!;

    [Key(1)]
    public LoginPassNotificationTypes LoginPassNotification { get; set; } = default!;

    [Key(2)]
    public bool IsApproachingLoginPassInvalided { get; set; }

    [Key(3)]
    public long[] InvalidedItemMasterIds { get; set; } = default!;

    [Key(4)]
    public long[] ApproachingItemMasterIds { get; set; } = default!;

    [Key(5)]
    public StoryEventPointExchangeResult[] StoryEventPointExchangeResult { get; set; } = default!;

}
