// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LoginBonusSpineGroup
{
    [Key(0)]
    public LoginBonusSpineSelectType SpineSelectType { get; set; } = default!;

    [Key(1)]
    public LoginBonusSpineDetail[] Details { get; set; } = default!;

}
