// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LoginBonusSpineDetail
{
    [Key(0)]
    public long? TargetValue1 { get; set; }

    [Key(1)]
    public long? TargetValue2 { get; set; }

    [Key(2)]
    public string MessageTemplate { get; set; }

    [Key(3)]
    public string NavigationSpineId { get; set; }

    [Key(4)]
    public string VoiceAssetId { get; set; }

    [Key(5)]
    public long? HeadMotionMasterId { get; set; }

    [Key(6)]
    public long? FacialExpressionMasterId { get; set; }

    [Key(7)]
    public long? HeadDirectionMasterId { get; set; }

    [Key(8)]
    public long? BodyMotionMasterId { get; set; }

    [Key(9)]
    public long? LipSyncMasterId { get; set; }

}
