// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class LoginBonusResult
{
    [Key(0)]
    public long LoginBonusId { get; set; }

    [Key(1)]
    public int CurrentLoginCount { get; set; }

    [Key(2)]
    public ReceivedThing[] ReceivedThings { get; set; } = default!;

    [Key(3)]
    public string Title { get; set; }

    [Key(4)]
    public LoginBonusTypes Type { get; set; } = default!;

    [Key(5)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(6)]
    public global::System.DateTime? EndDate { get; set; }

    [Key(10)]
    public string MessageTemplate { get; set; }

    [Key(11)]
    public string BackgroundImagePath { get; set; }

    [Key(12)]
    public string CardboardImagePath { get; set; }

    [Key(13)]
    public string LogoImagePath { get; set; }

    [Key(14)]
    public int TotalDays { get; set; }

    [Key(15)]
    public bool IsLoop { get; set; }

    [Key(16)]
    public int Order { get; set; }

    [Key(17)]
    public LoginBonusDetail[] Details { get; set; } = default!;

    [Key(18)]
    public string NavigationSpineId { get; set; }

    [Key(19)]
    public string VoiceAssetId { get; set; }

    [Key(20)]
    public long? HeadMotionMasterId { get; set; }

    [Key(21)]
    public long? FacialExpressionMasterId { get; set; }

    [Key(22)]
    public long? HeadDirectionMasterId { get; set; }

    [Key(23)]
    public long? BodyMotionMasterId { get; set; }

    [Key(24)]
    public long? LipSyncMasterId { get; set; }

    [Key(25)]
    public LoginBonusLayoutTypes LayoutType { get; set; } = default!;

    [Key(26)]
    public long? ComebackCampaignMasterId { get; set; }

    [Key(27)]
    public LoginBonusSpineGroup LoginBonusSpineGroup { get; set; } = default!;

}
