// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
[Obsolete]
public partial class MainCharacter
{
    [Key(0)]
    public long CharacterMasterId { get; set; }

    [Key(1)]
    public int AwakeningPhase { get; set; }

    [Key(2)]
    public int TalentStage { get; set; }

    [Key(3)]
    public int Level { get; set; }

    [Key(4)]
    public bool DisplayAwakeningStatus { get; set; }

}
