// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class Market : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public global::System.DateTime LastRefreshedAt { get; set; } = default!;

    [Key(2)]
    public int RefreshTimes { get; set; }

}
