// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MarketResult
{
    [Key(0)]
    public MarketThing[] Things { get; set; } = default!;

    [Key(1)]
    public int? RequiredJewelForRefresh { get; set; }

}
