// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MatchingGhostLiveResult
{
    [Key(0)]
    public long GhostLiveMasterId { get; set; }

    [Key(1)]
    public UserProfileDetail GhostUserProfile { get; set; } = default!;

    [Key(2)]
    public GhostLiveInfo GhostLiveInfo { get; set; } = default!;

}
