// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum MissionCategories
{
    Beginner = 1,
    Normal = 2,
    Limit = 3,
    Daily = 4,
    Weekly = 5,
    SiriusDay = 6,
    TheaterSirius = 11,
    TheaterEden = 12,
    TheaterGingaza = 13,
    TheaterDenki = 14,
}
