// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum MissionPassRewardStatus
{
    NotReceived = 1,
    Received = 2,
    NotPaidSpItem = 3,
    NotReachedPoint = 4,
    ReceiveSuccess = 5,
}
