// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MissionPassRewardsResult
{
    [Key(0)]
    public ReceivedThing[] MissionPassRewards { get; set; } = default!;

    [Key(1)]
    public MissionPassRewardStatus RewardResult { get; set; } = default!;

}
