// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MultiLiveRestrictionResult
{
    [Key(0)]
    public global::System.DateTime? RestrictionFinishedAt { get; set; }

}
