// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MultiRoomJoinnedResult
{
    [Key(0)]
    public int MyRank { get; set; }

    [Key(1)]
    public long? MyScore { get; set; }

    [Key(2)]
    public decimal? MyTotalAchievementRatePercentRecord { get; set; }

    [Key(3)]
    public MultiRoomInformationResult MultiRoomInformationResult { get; set; } = default!;
}
