// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MultiRoomRanking
{
    [Key(0)] public string UserId { get; set; } = string.Empty;
    [Key(1)] public int Rank { get; set; }
    [Key(2)] public bool IsOwner { get; set; }
    [Key(3)] public long? Score { get; set; }
    [Key(4)] public decimal? TotalAchievementRatePercentRecord { get; set; }
    [Key(5)] public int BestRecordChallengeCount { get; set; }
    [Key(6)] public DateTime? BestRecordDate { get; set; }
    [Key(7)] public UserProfile UserProfile { get; set; } = default!;
    [Key(8)] public PartyInfo PartyInfo { get; set; } = default!;
    [Key(9)] public NoteResult NoteResult { get; set; } = default!;
}
