// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MultiRoomDetailResult
{
    [Key(0)] public MultiRoomInformationResult MultiRoomInformationResult { get; set; } = default!;
    [Key(1)] public MultiRoomRanking[] MultiRoomRankings { get; set; } = Array.Empty<MultiRoomRanking>();
    [Key(2)] public bool IsFinished { get; set; }
    [Key(3)] public string? Password { get; set; }
}
