// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MultiRoomInformationResult
{
    [Key(0)]
    public string HashedMultiRoomId { get; set; }

    [Key(1)]
    public string RoomName { get; set; }

    [Key(2)]
    public global::Sirius.Protocol.Shared.MultiRoomPlayModes PlayMode { get; set; } = default!;

    [Key(3)]
    public int JoinedMemberCount { get; set; }

    [Key(4)]
    public int CanJoinMaxMember { get; set; }

    [Key(5)]
    public global::System.DateTime StartDate { get; set; } = default!;

    [Key(6)]
    public global::System.DateTime EndDate { get; set; } = default!;

    [Key(7)]
    public long LiveMasterId1 { get; set; }

    [Key(8)]
    public long? LiveMasterId2 { get; set; }

    [Key(9)]
    public long? LiveMasterId3 { get; set; }

    [Key(10)]
    public bool HasPassword { get; set; }
}
