// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MultiRoomInvitedResult
{
    [Key(0)]
    public string OwnerUserName { get; set; } = string.Empty;

    [Key(1)]
    public MultiRoomInformationResult MultiRoomInformationResult { get; set; } = default!;
}
