// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MultiRoomCreateResult
{
    [Key(0)] public string HashedMultiRoomId { get; set; } = string.Empty;
    [Key(1)] public MultiRoomDetailResult RoomDetail { get; set; } = default!;
}
