// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MusicCourseRandomSelectResultDetail
{
    [Key(0)]
    public int SetListNumber { get; set; }

    [Key(1)]
    public long LiveMasterId { get; set; }
}
