// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum MusicDifficulties
{
    None = 0,
    Normal = 1,
    Hard = 2,
    Extra = 3,
    Stella = 4,
    Olivier = 5,
}
