// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MusicCourseRandomSelectResult
{
    [Key(0)]
    public MusicCourseRandomSelectResultDetail[] Details { get; set; } = default!;
}
