// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum MusicCourseType
{
    DanClass = 1,
    AdvancedDanClass = 2,
    TournamentQualifying = 3,
    Special = 4,
    WeeklyCourseRanking = 5,
}
