// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[Flags]
public enum MusicBookmarkFlags
{
    None = 0,
    Bookmark1 = 1,
    Bookmark2 = 2,
    Bookmark3 = 4,
}
