// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum MusicCourseCertificationGrade
{
    None = 0,
    Failed = 1,
    NormalGaugeCertificate = 2,
    HotGaugeCertificate = 3,
}
