// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum MusicCourseUnlockConditionTypes
{
    None = 0,
    ClearedMMusicCourseId = 1,
    PlayerRank = 2,
}
