// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class MyCircleInformationResult
{
    [Key(0)]
    public string UCircleHashedId { get; set; }

    [Key(1)]
    public string Name { get; set; }

    [Key(2)]
    public string Comment { get; set; }

    [Key(3)]
    public PlayTimeTypes PlayTimeStartType { get; set; } = default!;

    [Key(4)]
    public PlayTimeTypes PlayTimeEndType { get; set; } = default!;

    [Key(5)]
    public EntryTypes EntryType { get; set; } = default!;

    [Key(6)]
    public int MemberCount { get; set; }

    [Key(7)]
    public CircleAuthorities MyAuthority { get; set; } = default!;

    [Key(8)]
    public CircleResultStatus ResultStatus { get; set; } = default!;

    [Key(9)]
    public CircleBanner CircleBanner { get; set; } = default!;

    [Key(10)]
    public long? CompanyMasterId { get; set; }

    [Key(11)]
    public long? CharacterBaseMasterId { get; set; }

    [Key(12)]
    public SupportCompanyInformation SupportCompanyInformation { get; set; } = default!;

    [Key(13)]
    public Companies SupportCompany { get; set; } = default!;

    [Key(14)]
    public int DailyAddedSupportPoint { get; set; }

    [Key(15)]
    public bool IsPublishRanking { get; set; }

    [Key(16)]
    public global::System.DateTime StaminaLastReceivedAt { get; set; } = default!;

    [Key(17)]
    public CircleAuthorityUpdateTypes CircleAuthorityUpdateType { get; set; } = default!;

}
