// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum NamePlateChangeTypes
{
    None = 0,
    DaiStarEnrollCount = 1,
    TripleCastDaiStarEnrollCount = 2,
}
