// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class NoteJudgePayload
{
    [Key(0)]
    public TimingTypes Timing { get; set; } = default!;

    [Key(1)]
    public int Count { get; set; }

}
