// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class NoteResult
{
    [Key(0)]
    public int PerfectStar { get; set; }

    [Key(1)]
    public int Perfect { get; set; }

    [Key(2)]
    public int Great { get; set; }

    [Key(3)]
    public int Good { get; set; }

    [Key(4)]
    public int Bad { get; set; }

    [Key(5)]
    public int Miss { get; set; }

}
