// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum NotificationTabCategory
{
    Important = 1,
    UpdateInformation = 2,
    BugInformation = 3,
}
