// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum NotificationCategory
{
    Notification = 1,
    Update = 2,
    Campaign = 3,
    Event = 4,
    Gacha = 5,
    Bug = 6,
}
