// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class NotificationContentResult
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public string Body { get; set; }

    [Key(7)]
    public string BannerPath { get; set; }

    [Key(2)]
    public string Title { get; set; }

    [Key(3)]
    public global::System.DateTime PostingAt { get; set; } = default!;

    [Key(4)]
    public global::System.DateTime LastUpdatedAt { get; set; } = default!;

    [Key(5)]
    public NotificationTabCategory NotificationTabCategory { get; set; } = default!;

    [Key(6)]
    public NotificationCategory NotificationCategory { get; set; } = default!;

}
