// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum OlivierReleaseStatuses
{
    None = 0,
    Challengeable = 1,
    Purchasable = 2,
    Released = 3,
}
