// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum PageCategories
{
    TutorialIngame = 1,
    Spot = 2,
    Photo = 3,
    Circle = 4,
    Lesson = 5,
    AuditionTop = 6,
    AuditionConfirm = 7,
    League = 8,
    SpecialLive = 9,
    MultiLive = 10,
    LiveResult = 11,
    OlivierLiveResult = 12,
    Party = 13,
    Enhancement = 14,
    Costume = 15,
    StarRank = 16,
    SideStory = 17,
    TrophyAndProfile = 18,
    Shop = 19,
    MedalExchangeShop = 20,
    BeginnerMission = 21,
    StaminaConsumption = 22,
    CompanyIntroMovieSirius = 24,
    CompanyIntroMovieEden = 25,
    CompanyIntroMovieGingaza = 26,
    CompanyIntroMovieDenki = 27,
    SpotStoryArchive = 28,
    PhotoTop = 29,
    TeamChallenge = 30,
    ActorPortal = 31,
    MusicSelection = 32,
    ConcertStageSelect = 33,
    AlbumTop = 34,
    CircleEvent = 35,
    TournamentEventTop = 36,
    CourseModeSelection = 37,
    TripleCastLeague = 38,
    TournamentCourseModeSelection = 39,
    GhostLive = 40,
    TrialPartyEvent = 41,
    StellaConcours = 42,
    MultiRoom = 43,
}
