// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class PartySlotPayload
{
    [Key(0)]
    public int Position { get; set; }

    [Key(1)]
    public PartySlotCharacterPayload PartySlotCharacterPayload { get; set; } = default!;

    [Key(2)]
    public PartySlotPosterPayload PartySlotPosterPayload { get; set; } = default!;

    [Key(3)]
    public PartySlotAccessoryPayload PartySlotAccessoryPayload { get; set; } = default!;

}
