// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class PartySlotPosterPayload
{
    [Key(0)]
    public long MPosterId { get; set; }

    [Key(1)]
    public int Level { get; set; }

    [Key(2)]
    public int Phase { get; set; }

    [Key(3)]
    public PosterEpisodeTypes ReleasedEpisode { get; set; } = default!;

}
