// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class PartySlotCharacterPayload
{
    [Key(0)]
    public long MCharacterId { get; set; }

    [Key(1)]
    public int TalentStage { get; set; }

    [Key(2)]
    public int AwakeningPhase { get; set; }

    [Key(3)]
    public int Level { get; set; }

    [Key(4)]
    public int SenseLevel { get; set; }

    [Key(5)]
    public int CurrentExperience { get; set; }

    [Key(6)]
    public CharacterEpisodeOrder ReleasedEpisodeOrder { get; set; } = default!;

    [Key(7)]
    public CharacterEpisodeOrder ReadEpisodeOrder { get; set; } = default!;

    [Key(8)]
    public bool DisplayAwakeningStatus { get; set; }

}
