// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class PartySlotAccessoryPayload
{
    [Key(0)]
    public long MAccessoryId { get; set; }

    [Key(1)]
    public int Level { get; set; }

    [Key(2)]
    public long? MAccessoryEffectId1 { get; set; }

    [Key(3)]
    public long? MAccessoryEffectId2 { get; set; }

    [Key(4)]
    public long? MAccessoryEffectId3 { get; set; }

}
