// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum PaymentStatus
{
    Started = 1,
    Confirmed = 2,
    Completed = 3,
    ErrorNotFound = 4,
    ErrorWrongStatus = 5,
    ErrorRetryConfirmation = 6,
    Voided = 7,
}
