// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum PhotoRarities
{
    Rare1 = 1,
    Rare2 = 2,
    Rare3 = 3,
    Rare4 = 4,
    Rare5 = 5,
}
