// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum PickupCharacterMissionCheckCondition
{
    Level = 1,
    AwakeningPhase = 2,
    TalentStage = 3,
    SenseLevel = 4,
    EpisodeOrder = 5,
}
