// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class PlayerRankPointResult
{
    [Key(0)]
    public int RankBefore { get; set; }

    [Key(1)]
    public int RankAfter { get; set; }

    [Key(2)]
    public int RankPointBefore { get; set; }

    [Key(3)]
    public int RankPointAfter { get; set; }

    [Key(4)]
    public int RankPointAcquired { get; set; }

    [Key(5)]
    public int StaminaBefore { get; set; }

}
