// <auto-generated />
#nullable enable
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class PosterFavoritePayload
{
    [Key(0)]
    public long PosterId { get; set; }

    [Key(1)]
    public bool SetFavorite { get; set; }
}
