// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class PosterRarityProbability
{
    [Key(0)]
    public PossessionRarities Rarity { get; set; } = default!;

    [Key(1)]
    public double Probability { get; set; }

}
