// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum PosterEpisodeTypes
{
    Information = 0,
    Chapter1 = 1,
    Chapter2 = 2,
    Chapter3 = 3,
    Chapter4 = 4,
    AfterTalk = 5,
    Sirius = 6,
    Eden = 7,
    Gingaza = 8,
    Denki = 9,
}
