// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum ProcessPaymentTransactionResult
{
    Success = 1,
    TemporaryIssuesTryAgain = 2,
    Failed = 3,
    CouldNotConfirm = 4,
    CouldNotAcknowledge = 5,
    Pending = 6,
}
