// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class PurchaseItemPayload
{
    [Key(0)]
    public long MJewelShopItemId { get; set; }

}
