// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class RateUpdateResult
{
    [Key(0)]
    public double BestEver { get; set; }

    [Key(1)]
    public double ThisTime { get; set; }

}
