// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class RateResult
{
    [Key(0)]
    public RateUpdateResult AchievementRateResult { get; set; } = default!;

    [Key(1)]
    public RateUpdateResult LiveRateResult { get; set; } = default!;

    [Key(2)]
    public double TotalRateBefore { get; set; }

    [Key(3)]
    public double TotalRateAfter { get; set; }

}
