// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class RawHighScoreRankingResult
{
    [Key(0)]
    public RawRankingWithLongPoint[] RawRanking { get; set; } = default!;

    [Key(1)]
    public HighScoreParty[] HighScoreParties { get; set; } = default!;

    [Key(2)]
    public HighScoreBuff[] HighScoreBuffs { get; set; } = default!;

    [Key(3)]
    public UserProfile[] UserProfiles { get; set; } = default!;

}
