// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class RawRankingWithLongPoint
{
    [Key(0)]
    public int Rank { get; set; }

    [Key(1)]
    public long Point { get; set; }

    [Key(2)]
    public string UserId { get; set; }

}
