// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class RawRanking
{
    [Key(0)]
    public int Rank { get; set; }

    [Key(1)]
    public int Point { get; set; }

    [Key(2)]
    public string UserId { get; set; } = string.Empty;

    [Key(3)]
    public int GroupValue { get; set; }

}
