// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ReadNotificationPayload
{
    [Key(0)]
    public NotificationTabCategory TabCategory { get; set; } = default!;

    [Key(1)]
    public global::System.DateTime ReadAt { get; set; } = default!;

}
