// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ReceivedThing
{
    [Key(0)]
    public ThingTypes Type { get; set; } = default!;

    [Key(1)]
    public long? Id { get; set; }

    [Key(2)]
    public int Quantity { get; set; }

    [Key(3)]
    public ThingTypes? OriginalType { get; set; }

    [Key(4)]
    public long? OriginalId { get; set; }

    [Key(5)]
    public int? AfterPhase { get; set; }

    [Key(6)]
    public bool SentInbox { get; set; }

}
