// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class RegisterBirthDayPayload
{
    [Key(0)]
    public global::System.DateTime BirthDate { get; set; } = default!;

}
