// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class RegisterTakeOverPasswordPayload
{
    [Key(0)]
    public string Password { get; set; }

}
