// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class RegisterAppStorePaymentPayload
{
    [Key(0)]
    public string ReceiptBase64 { get; set; }

}
