// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class RegisterGooglePlayPaymentPayload
{
    [Key(0)]
    public string Json { get; set; }

}
