// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum ResultVoiceConditionTypes
{
    AllPerfect = 1,
    FullCombo = 2,
    ClearedAndBestAchievementRate = 3,
    Cleared = 4,
    LifeZeroAndBestAchievementRate = 5,
    LifeZero = 6,
}
