// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class RollResult
{
    [Key(0)]
    public int RollOrder { get; set; }

    [Key(1)]
    public int SelectedSlot { get; set; }

    [Key(2)]
    public long RoulettePrizeMasterId { get; set; }

}
