// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class RouletteRollResult
{
    [Key(0)]
    public RollResult[] RollResults { get; set; } = default!;

}
