// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum SearchCircleMemberConditionTypes
{
    None = 0,
    OneToFive = 1,
    SixToNine = 2,
}
