// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class SelectMusicCourseRandomMusicPayload
{
    [Key(0)]
    public long MusicCourseMasterId { get; set; }

    [Key(1)]
    public MusicCourseGaugeType MusicCourseGaugeType { get; set; } = default!;
}
