// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum SenseNotationStatusTypes
{
    Performance = 0,
    Vocal = 1,
    Expression = 2,
    Concentration = 3,
}
