// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum SenseTypes
{
    Support = 1,
    Control = 2,
    Amplification = 3,
    Special = 4,
    None = 9,
    Alternative = 10,
}
