// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum SenseLightTypes
{
    Variable = 0,
    Support = 1,
    Control = 2,
    Amplification = 3,
    Special = 4,
}
