// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum SenseNotationBuffTypes
{
    None = 0,
    Attribute = 1,
    Company = 2,
    CharacterBase = 3,
    Character = 4,
}
