// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class SerialCodeResult
{
    [Key(0)]
    public UseSerialCodeResult Result { get; set; } = default!;

}
