// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class SetAlbumPublishingPayload
{
    [Key(0)]
    public bool Publishing { get; set; }

    [Key(1)]
    public int PublishPageNumber { get; set; }

}
