// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class SetLessonPartyPayload
{
    [Key(0)]
    public SetLessonPartySlotPayload[] Slots { get; set; } = default!;

}
