// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class SetPhotoTagPayload
{
    [Key(0)]
    public long PhotoId { get; set; }

    [Key(1)]
    public long[] CharacterBaseIds { get; set; } = default!;

}
