// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum ShopCategories
{
    None = 0,
    Normal = 1,
    Medal = 2,
    Event = 3,
    Gacha = 4,
    Special = 5,
    Music = 6,
}
