// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum ShopUnlockTypes
{
    ReadStory = 2,
    RateReached = 8,
    ClassReached = 9,
    BuyItem = 10,
    ReadFirstMainStory = 11,
    AuditionReached = 12,
    SelectedPickup = 17,
    NotInPossession = 20,
}
