// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum ShopReplaceTypes
{
    None = 0,
    Daily = 1,
    Weekly = 2,
    Monthly = 3,
    DailyPassExpired = 10,
}
