// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum ShopItemTypes
{
    None = 0,
    LoginPass = 1,
    StarPass = 2,
    DaiStarPass = 3,
    MultiLiveDropBoost = 4,
    MultiLiveDropLimitUp = 5,
}
