// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum ShopPurchaseTypes
{
    Paid = 1,
    Money = 2,
    Free = 3,
    FreeJewel = 4,
}
