// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ShopResult
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long MExchangeShopId { get; set; }

    [Key(2)]
    public long RequiredMItemId { get; set; }

    [Key(3)]
    public int RequiredQuantity { get; set; }

    [Key(4)]
    public int Order { get; set; }

    [Key(5)]
    public int ExchangeLimit { get; set; }

    [Key(6)]
    public int ExchangeTimes { get; set; }

    [Key(7)]
    public int Stock { get; set; }

    [Key(8)]
    public ShopReplaceTypes? ReplaceType { get; set; }

    [Key(9)]
    public int? ReplaceValue { get; set; }

    [Key(10)]
    public bool IsDisplayLocking { get; set; }

    [Key(11)]
    public ShopUnlockTypes? UnlockType { get; set; }

    [Key(12)]
    public long? UnlockValue { get; set; }

    [Key(13)]
    public global::System.DateTime? StartDate { get; set; }

    [Key(14)]
    public global::System.DateTime? EndDate { get; set; }

    [Key(15)]
    public long? MMusicId { get; set; }

}
