// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum SplashAdditionalValueTypes
{
    None = 0,
    HomeCharacterBaseId = 1,
    LotteryHighestPrizeId = 2,
}
