// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum SplashTypes
{
    Video = 1,
    Picture = 2,
    Episode = 3,
    LotteryResult = 4,
}
