// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum SpotPositions
{
    Position1 = 1,
    Position2 = 2,
    Position3 = 3,
    Position4 = 4,
}
