// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum SpotTypes
{
    UtagawaHighSchool = 1,
    HigashiUenoHighSchool = 2,
    Park = 3,
    Cafe = 4,
    ElectricTown = 5,
    ThemePark = 6,
}
