// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class SpRateUpdateResult
{
    [Key(0)]
    public int BestEver { get; set; }

    [Key(1)]
    public int ThisTime { get; set; }

    [Key(2)]
    public int BestEverTotal { get; set; }

    [Key(3)]
    public int ThisTimeTotal { get; set; }

}
