// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StarPointResult
{
    [Key(0)]
    public int RankBefore { get; set; }

    [Key(1)]
    public int RankAfter { get; set; }

    [Key(2)]
    public int StarPointBefore { get; set; }

    [Key(3)]
    public int StarPointAfter { get; set; }

    [Key(4)]
    public int StarPointAcquired { get; set; }

    [Key(5)]
    public ReceivedThing[] ReceivedReward { get; set; } = default!;

}
