// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StartLessonPayload
{
    [Key(0)]
    public int CharacterBaseMasterId { get; set; }

    [Key(1)]
    public long LiveMasterId { get; set; }

}
