// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StartMultiLivePayload
{
    [Key(0)]
    public long LiveMasterId { get; set; }

    [Key(1)]
    public long MultiLiveId { get; set; }

    [Key(2)]
    public bool UseStamina { get; set; }

    [Key(3)]
    public int StaminaConsumptionRatio { get; set; }

    [Key(4)]
    public long? PartyId { get; set; }

}
