// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StartMultiLiveSessionPayload
{
    [Key(0)]
    public long LiveSettingMasterId { get; set; }

    [Key(1)]
    public string RoomId { get; set; }

    [Key(2)]
    public long MusicMasterId { get; set; }

}
