// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StartTeamChallengeSessionResult
{
    [Key(0)]
    public long MultiLiveId { get; set; }

    [Key(1)]
    public TeamChallengeGoalLotResult LottedGoal { get; set; } = default!;

}
