// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StartLivePayload
{
    [Key(0)]
    public long PartyId { get; set; }

    [Key(1)]
    public long LiveMasterId { get; set; }

    [Key(2)]
    public long? AuditionMasterId { get; set; }

    [Key(3)]
    public long? LeagueMasterId { get; set; }

    [Key(4)]
    public bool UseStamina { get; set; }

    [Key(5)]
    public int StaminaConsumptionRatio { get; set; }

    [Key(6)]
    public long LiveSettingMasterId { get; set; }

    [Key(7)]
    public bool IsAutoPlay { get; set; }

    [Key(8)]
    public bool IsStoryEventChallenge { get; set; }

    [Key(9)]
    public long? ConcertStageMasterId { get; set; }

    [Key(10)]
    public long? BonusLiveStageMasterId { get; set; }

    [Key(11)]
    public long? MusicCourseDetailMasterId { get; set; }

    [Key(12)]
    public MusicCourseGaugeType MusicCourseGaugeType { get; set; } = default!;

    [Key(13)]
    public long? GhostLiveMasterId { get; set; }

    [Key(14)]
    public long? TrialPartyEventStageMasterId { get; set; }

}
