// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StartTournamentPayload
{
    [Key(0)]
    public long TournamentDetailMasterId { get; set; }

    [Key(1)]
    public long PartyId { get; set; }

    [Key(2)]
    public int StaminaConsumptionRatio { get; set; }

}
