// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StartTripleCastLivePayload
{
    [Key(0)]
    public long MLiveId { get; set; }

    [Key(1)]
    public long MTripleCastId { get; set; }

}
