// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StartTripleCastLiveResult
{
    [Key(0)]
    public global::Sirius.Protocol.LiveEngine.Models.LiveUnitWithOrder[] LiveUnits { get; set; } = default!;

}
