// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StartTeamChallengeSessionPayload
{
    [Key(0)]
    public TeamChallengeDifficultyTypes Difficulty { get; set; } = default!;

    [Key(1)]
    public string RoomId { get; set; }

}
