// <auto-generated />
#nullable enable
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StartMultiRoomLivePayload
{
    [Key(0)]
    public string HashedMultiRoomId { get; set; } = string.Empty;

    [Key(1)]
    public long LiveMasterId { get; set; }

    [Key(2)]
    public long? PartyId { get; set; }
}
