// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class Status
{
    [Key(0)]
    public int Vocal { get; set; }

    [Key(1)]
    public int Expression { get; set; }

    [Key(2)]
    public int Concentration { get; set; }

}
