// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum StorageSenseLightConditionValue
{
    Support = 1,
    Control = 2,
    Amplification = 3,
    Special = 4,
    All = 5,
}
