// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StoryEventMissionCircleProgressResult
{
    [Key(0)]
    public bool IsSuccess { get; set; }

    [Key(1)]
    public StoryEventMissionCircleProgress[] Progresses { get; set; } = default!;

}
