// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum StoryTypes
{
    None = 0,
    Main = 1,
    Event = 2,
    Side = 3,
    Character = 4,
    Special = 5,
}
