// <auto-generated />
#nullable enable
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public sealed class StoryEventCampInfo
{
    [Key(0)]
    public RawRanking RawRanking { get; set; } = new();

    [Key(1)]
    public long Camp1TotalPoint { get; set; }

    [Key(2)]
    public long Camp2TotalPoint { get; set; }
}
