// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StoryEventPointExchangeResult
{
    [Key(0)]
    public long StoryEventMasterId { get; set; }

    [Key(1)]
    public int BeforeStoryEventPointAmount { get; set; }

    [Key(2)]
    public int AfterCoinAmount { get; set; }

}
