// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class StoryEventMissionCircleProgress
{
    [Key(0)]
    public long StoryEventCircleMissionMasterId { get; set; }

    [Key(1)]
    public int CurrentCount { get; set; }

}
