// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum StoryEventCategoryTypes
{
    Normal = 1,
    Voltage = 2,
    HighScore = 3,
    Circle = 4,
    MainStory = 5,
}
