// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum StoryEventBonusTypes
{
    Company = 1,
    CharacterBase = 2,
    Poster = 3,
}
