// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class SupportCompanyLevelStatus
{
    [Key(0)]
    public int Level { get; set; }

    [Key(1)]
    public int CurrentSupportPoint { get; set; }

    [Key(2)]
    public global::System.DateTime LastLevelUppedAt { get; set; } = default!;

    [Key(3)]
    public int LevelLimit { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.SupportCompanyLevelLimitStatus LevelLimitStatus { get; set; } = new();

}
