// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public sealed class SupportCompanyLevelLimitStatus
{
    [Key(0)]
    public long CurrentCoinQuantity { get; set; }

    [Key(1)]
    public SupportCompanyLevelLimitStatusDetail[] Details { get; set; } = [];
}
