// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class SupportCompanyInformation
{
    [Key(0)]
    public SupportCompanyLevelStatus Sirius { get; set; } = default!;

    [Key(1)]
    public SupportCompanyLevelStatus Eden { get; set; } = default!;

    [Key(2)]
    public SupportCompanyLevelStatus Gingaza { get; set; } = default!;

    [Key(3)]
    public SupportCompanyLevelStatus Denki { get; set; } = default!;

}
