// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum TabCategories
{
    Hidden = 0,
    Normal = 1,
    Raise = 2,
    Ticket = 3,
    Piece = 4,
}
