// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TakeOverAccountPayload
{
    [Key(0)]
    public string LinkageCode { get; set; }

    [Key(1)]
    public string Password { get; set; }

}
