// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TakeOverAccountResult
{
    [Key(0)]
    public bool IsSuccess { get; set; }

    [Key(1)]
    public string UserId { get; set; }

    [Key(2)]
    public string Name { get; set; }

    [Key(3)]
    public int Rank { get; set; }

    [Key(4)]
    public string LoginToken { get; set; }

}
