// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TakeOverCodeResult
{
    [Key(0)]
    public bool IsSuccess { get; set; }

    [Key(1)]
    public string LinkageCode { get; set; }

}
