// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum TeamChallengeGoalTypes
{
    TotalScore = 1,
    TotalCombo = 2,
    TotalStarAct = 3,
}
