// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TeamChallengeGoalLotResult
{
    [Key(0)]
    public long TeamChallengeMasterId { get; set; }

    [Key(2)]
    public long GoalValue { get; set; }

}
