// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TeamChallengeResult
{
    [Key(0)]
    public TeamChallengeGoalLotResult ThisTimeGoal { get; set; } = default!;

    [Key(1)]
    public bool IsCleared { get; set; }

    [Key(2)]
    public long ActualGoalValue { get; set; }

}
