// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum ThingTypes
{
    Item = 1,
    Character = 2,
    Poster = 3,
    Accessory = 4,
    Costume = 5,
    Trophy = 6,
    Stamp = 7,
    Nameplate = 8,
    NameColor = 9,
    Bomb = 10,
    Note = 11,
    Coin = 12,
    Jewel = 13,
    Music = 14,
    Stamina = 15,
    Decoration = 16,
    AlbumTheme = 17,
    NameBaseColor = 18,
    IconFrame = 19,
    HomeSkin = 20,
}
