// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TimedConfirmationCode
{
    [Key(0)]
    public string ConfirmationCode { get; set; }

    [Key(1)]
    public int RemainingSeconds { get; set; }

}
