// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum TimingTypes
{
    None = 0,
    MISS = 1,
    BAD = 2,
    GOOD = 3,
    GREAT = 4,
    PERFECT = 5,
    PERFECT_STAR = 6,
}
