// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum TitleBackgroundPathTypes
{
    Path = 1,
    CharacterMasterId = 2,
    PosterMasterId = 3,
}
