// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TotalPaymentResult
{
    [Key(0)]
    public int TotalPaymentThisMonth { get; set; }

}
