// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TotalPointEventInformationResult
{
    [Key(0)]
    public long CurrentTotalPoint { get; set; }

}
