// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TournamentResult
{
    [Key(0)]
    public long BestEverUniqueScore { get; set; }

    [Key(1)]
    public long ThisTimeUniqueScore { get; set; }

    [Key(2)]
    public long TournamentDetailMasterId { get; set; }

}
