// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TournamentQualifyingInformationResult
{
    [Key(0)]
    public string EntryCode { get; set; }

}
