// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TransitionTokenResult
{
    [Key(0)]
    public string Token { get; set; }

}
