// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum TrialPartyCharacterLockTypes
{
    None = 0,
    CharacterBase = 1,
    Character = 2,
}
