// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum TrialPartyEquipmentLockTypes
{
    None = 0,
    CharacterBase = 1,
    Position = 2,
}
