// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TrialPartyEventResult
{
    [Key(0)]
    public ReceivedThing[] Rewards { get; set; } = default!;

}
