// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TrialPartyEventStageResult
{
    [Key(0)]
    public int PrincipalGaugeValue { get; set; }

}
