// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum TriggerType
{
    OverLife = 1,
    BelowLife = 2,
    CharacterBase = 3,
    Company = 4,
    Attribute = 5,
    SenseType = 6,
    CompanyCount = 7,
    AttributeCount = 8,
    CharacterBaseGroup = 9,
}
