// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TripleCastPartyResult
{
    [Key(0)]
    public int Order { get; set; }

    [Key(1)]
    public long Score { get; set; }

    [Key(2)]
    public LeaguePartySlotResult[] Slots { get; set; } = default!;

}
