// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class TripleCastPartyAndRankingResult
{
    [Key(0)]
    public int? Rank { get; set; }

    [Key(1)]
    public string UserId { get; set; }

    [Key(2)]
    public long BestScore { get; set; }

    [Key(3)]
    public long TripleCastMasterId { get; set; }

    [Key(4)]
    public LeagueClassTypes ClassType { get; set; } = default!;

    [Key(5)]
    public MusicDifficulties Difficulty { get; set; } = default!;

    [Key(6)]
    public string UserName { get; set; }

    [Key(7)]
    public TripleCastPartyResult[] Parties { get; set; } = default!;

}
