// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum TrophyCategories
{
    Character = 1,
    Achievement = 2,
    Event = 3,
    Other = 4,
}
