// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum TutorialStatus
{
    Start = 0,
    TutorialDownLoad = 1,
    MainScenario = 2,
    TheaterMovie = 3,
    Home = 4,
    InGame = 5,
    MiniTalk = 6,
    Finish = 99,
}
