// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum UnlockConditionTypes
{
    CharacterStarRank = 1,
    Story = 2,
    GetPoster = 3,
    ReleasePoster1 = 4,
    ReleasePoster2 = 5,
    ReleasePoster3 = 6,
    ReleasePoster4 = 7,
    PlayerRate = 8,
    LeagueClass = 9,
    BuyItem = 10,
    AnyMainStoryChapter = 11,
    AuditionClear = 12,
    ExtraGoodCount = 13,
    NotationShop = 14,
    BuyJewelShopItem = 15,
    PlayerRank = 16,
    SelectedPickup = 17,
    TimeLimitedControl = 18,
    FlashSale = 19,
    NotInPossession = 20,
}
