// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class UpdateHomeDisplayPreferencePayload
{
    [Key(0)]
    public long? HomeCharacterBaseMasterId { get; set; }

    [Key(2)]
    public long? MemberCharacterBaseMasterId { get; set; }

    [Key(3)]
    public long? StoryCharacterBaseMasterId { get; set; }

    [Key(4)]
    public long? ShopCharacterBaseMasterId { get; set; }

    [Key(5)]
    public long? HomeCostumeMasterId { get; set; }

    [Key(7)]
    public long? MemberCostumeMasterId { get; set; }

    [Key(8)]
    public long? StoryCostumeMasterId { get; set; }

    [Key(9)]
    public long? ShopCostumeMasterId { get; set; }

    [Key(10)]
    public long IllustCharacterMasterId { get; set; }

    [Key(11)]
    public bool DisplayAwakeningStatus { get; set; }

    [Key(12)]
    public HomeCharacterDisplayTypes HomeCharacterDisplayType { get; set; } = default!;

    [Key(13)]
    public long? LoginBonusCharacterBaseMasterId { get; set; }

    [Key(14)]
    public long? LoginBonusSpineCostumeMasterId { get; set; }

}
