// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class UpdateLastViewedAtPayload
{
    [Key(0)]
    public ViewedShopCategoryTypes ViewedShopCategoryTypes { get; set; } = default!;

    [Key(1)]
    public long? ExchangeShopMasterId { get; set; }

}
