// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class UpdateClearLampResult
{
    [Key(0)]
    public ClearLamps ClearLamp { get; set; } = default!;

}
