// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class UpdateGameHintPayload
{
    [Key(0)]
    public PageCategories[] Categories { get; set; } = default!;

}
