// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class UrlResult
{
    [Key(0)]
    public string Url { get; set; }

}
