// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum UseDecoPageFlag
{
    None = 0,
    Page1 = 1,
    Page2 = 2,
    Page3 = 4,
    Page4 = 8,
    Page5 = 16,
    Page6 = 32,
    Page7 = 64,
    Page8 = 128,
    Page9 = 256,
    Page10 = 512,
}
