// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class UserResult
{
    [Key(0)]
    public global::Sirius.Protocol.Shared.Models.Player.User User { get; set; } = default!;

}
