// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class UserProfileDetail : UserProfile
{
    [Key(9)]
    public long NameColorMasterId { get; set; }

    [Key(10)]
    public long NameBaseColorMasterId { get; set; }

    [Key(11)]
    public long? NameplateMasterId { get; set; }

    [Key(12)]
    public long? NameplateDetailMasterId { get; set; }

}
