// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class UserProfile
{
    [Key(0)]
    public string UserId { get; set; }

    [Key(1)]
    public string UserName { get; set; }

    [Key(2)]
    public long? TrophyMasterId1 { get; set; }

    [Key(3)]
    public long? TrophyMasterId2 { get; set; }

    [Key(4)]
    public long? TrophyMasterId3 { get; set; }

    [Key(5)]
    public long MainMCharacterId { get; set; }

    [Key(6)]
    public int MainCharacterLevel { get; set; }

    [Key(7)]
    public bool CharacterDisplayAwakeningStatus { get; set; }

    [Key(8)]
    public long IconFrameMasterId { get; set; }

}
