// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class UseStaminaRecoveryItem
{
    [Key(0)]
    public long ItemMasterId { get; set; }

    [Key(1)]
    public int Quantity { get; set; }

}
