// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class UseSerialCodePayload
{
    [Key(0)]
    public string UserHashId { get; set; }

    [Key(1)]
    public string ConfirmationCode { get; set; }

    [Key(2)]
    public string SerialCode { get; set; }

}
