// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class UseStaminaRecoveryItemsPayload
{
    [Key(0)]
    public UseStaminaRecoveryItem[] Items { get; set; } = default!;

}
