// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum UseSerialCodeResult
{
    SentToInbox = 1,
    InvalidUserIdOrConfirmationCode = 2,
    InvalidSerialCode = 3,
    AlreadyUsed = 4,
    AlreadyUsedAnotherCodeInGroup = 5,
}
