// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

public enum ViewedShopCategoryTypes
{
    ExchangeShop = 0,
    Music = 1,
    Live = 2,
    Gacha = 3,
    Market = 4,
}
