// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared;

[MessagePackObject(false)]
public partial class ViewShopResult
{
    [Key(0)]
    public ConvertedThingResult[] ConvertedThings { get; set; } = default!;

}
