// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Leagues;

[MessagePackObject(false)]
public partial class LeagueGroupMember : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long LeagueGroupId { get; set; }

    [Key(1)]
    public long LeagueMasterId { get; set; }

    [Key(2)]
    public long? BestScore { get; set; }

}
