// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Leagues;

[MessagePackObject(false)]
public partial class LeagueHighScoreParty : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long LeagueMasterId { get; set; }

    [Key(2)]
    public long HighScore { get; set; }

    [Key(3)]
    [Obsolete]
    public global::Sirius.Protocol.Shared.LeagueClassTypes ClassType { get; set; } = default!;

    [Obsolete]
    [Key(4)]
    public global::Sirius.Protocol.Shared.MusicDifficulties Difficulty { get; set; } = default!;

    [Obsolete]
    [Key(5)]
    public long MusicMasterId { get; set; }

    [Obsolete]
    [Key(6)]
    public long LeagueGroupId { get; set; }

    [Key(7)]
    public LeagueHighScorePartySlot[] Slots { get; set; } = default!;

    [Key(8)]
    public string UserName { get; set; }

    [Key(9)]
    public int ActingAbility { get; set; }

    [Key(10)]
    public int LeaderPosition { get; set; }

}
