// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Leagues;

[MessagePackObject(false)]
public partial class LeagueBasic : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long MyProperty { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.LeagueClassTypes BestClassType { get; set; } = default!;

    [Key(1)]
    public int StarEnrollCount { get; set; }

    [Key(2)]
    public int DaiStarEnrollCount { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.LeagueClassTypes CurrentClassType { get; set; } = default!;

    [Key(5)]
    public long? LastJoinedLeagueSeasonMasterId { get; set; }

}
