// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Leagues;

[MessagePackObject(false)]
public partial class TripleCastGroupMember : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long TripleCastGroupId { get; set; }

    [Key(1)]
    public long TripleCastMasterId { get; set; }

    [Key(2)]
    public long? BestScore { get; set; }

}
