// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Leagues;

[MessagePackObject(false)]
public partial class TripleCastBasic : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Shared.LeagueClassTypes BestClassType { get; set; } = default!;

    [Key(1)]
    public int StarEnrollCount { get; set; }

    [Key(2)]
    public int DaiStarEnrollCount { get; set; }

    [Key(3)]
    public global::Sirius.Protocol.Shared.LeagueClassTypes CurrentClassType { get; set; } = default!;

    [Key(5)]
    public long? LastJoinedTripleCastSeasonMasterId { get; set; }

    [Key(6)]
    public int? PartyOrder1 { get; set; }

    [Key(7)]
    public int? PartyOrder2 { get; set; }

    [Key(8)]
    public int? PartyOrder3 { get; set; }

}
