// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Leagues;

[MessagePackObject(false)]
public partial class TripleCastSeasonResult : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long TripleCastSeasonMasterId { get; set; }

    [Key(1)]
    public int DaiStarMaxEnrollCount { get; set; }

}
