// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Leagues;

[MessagePackObject(false)]
public partial class TripleCastHighScoreParty : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long TripleCastMasterId { get; set; }

    [Key(2)]
    public int Order { get; set; }

    [Key(3)]
    public long HighScore { get; set; }

    [Key(4)]
    public TripleCastHighScorePartySlot[] Slots { get; set; } = default!;

    [Key(5)]
    public int ActingAbility { get; set; }

    [Key(6)]
    public int LeaderPosition { get; set; }

    [Key(7)]
    public global::Sirius.Protocol.Shared.MusicDifficulties Difficulty { get; set; } = default!;

}
