// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Leagues;

[MessagePackObject(false)]
public partial class TripleCastHighScorePartySlot : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long Id { get; set; }

    [Key(1)]
    public long TripleCastHighScorePartyId { get; set; }

    [IgnoreMember]
    public TripleCastHighScoreParty TripleCastHighScoreParty { get; set; } = default!;

    [Key(2)]
    public int Position { get; set; }

    [Key(3)]
    public long CharacterMasterId { get; set; }

    [Key(4)]
    public int CharacterLevel { get; set; }

    [Key(7)]
    public long? PosterMasterId { get; set; }

    [Key(8)]
    public int? PosterLevel { get; set; }

    [Key(9)]
    public int? PosterBreakthroughPhase { get; set; }

    [Key(10)]
    public long? AccessoryMasterId { get; set; }

    [Key(11)]
    public int? AccessoryLevel { get; set; }

    [Key(12)]
    public global::Sirius.Protocol.LiveEngine.Models.Status CurrentStatus { get; set; } = default!;

    [Key(13)]
    public int CharacterTalentStage { get; set; }

    [Key(14)]
    public int CharacterAwakeningPhase { get; set; }

    [Key(15)]
    public bool CharacterDisplayAwakeningStatus { get; set; }

}
