// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Shared.Models.Leagues;

[MessagePackObject(false)]
public partial class TripleCastGroup : global::Sirius.Protocol.Shared.IDataObject
{
    [Key(0)]
    public long TripleCastMasterId { get; set; }

    [Key(1)]
    public global::Sirius.Protocol.Shared.LeagueClassTypes ClassType { get; set; } = default!;

    [Key(2)]
    public int ClassOrder { get; set; }

}
