// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.MultiLive;

[MessagePackObject(false)]
public partial class MultiLiveMatchingAssignment
{
    [Key(0)]
    public long LiveSettingMasterId { get; set; }

    [Key(1)]
    public string GroupName { get; set; }

    [Key(2)]
    public string UserId { get; set; }

}
