// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.MultiLive;

[MessagePackObject(false)]
public partial class MultiLiveUser
{
    [Key(0)]
    public int MemberId { get; set; }

    [Key(1)]
    public string UserName { get; set; }

    [Key(2)]
    public bool IsRandomMusic { get; set; }

    [Key(3)]
    public long SelectedMusicId { get; set; }

    [Key(4)]
    public global::Sirius.Protocol.Realtime.Shared.MultiLiveUserStatus Status { get; set; } = default!;

    [Key(5)]
    public MultiLiveCharacter LeaderCharacter { get; set; } = default!;

    [Key(6)]
    public long UserNamePlateColorId { get; set; }

    [Key(7)]
    public global::Sirius.Protocol.Shared.MusicDifficulties Difficulty { get; set; } = default!;

    [Key(8)]
    public global::Sirius.Protocol.Shared.ClearLamps ClearLamp { get; set; } = default!;

    [Key(9)]
    public long Score { get; set; }

    [Key(10)]
    public string HashUserId { get; set; }

    [Key(11)]
    public bool IsExitGame { get; set; }

    [IgnoreMember]
    public bool IsSelectedMusic { get; set; }

    [Key(12)]
    public bool IsAFK { get; set; }

    [Key(13)]
    public bool IsReadyDecideMember { get; set; }

}
