// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.MultiLive;

[MessagePackObject(false)]
public partial struct MultiLiveHallMember
{
    [Key(0)]
    public string UserId { get; set; }

    [Key(1)]
    public long Timestamp { get; set; }

}
