// <auto-generated />
#nullable enable
using System;
using MessagePack;

namespace Sirius.Protocol.Realtime.Shared.Entity.MultiLive;

[MessagePackObject(false)]
public partial class TeamChallengeSelectDifficulyAndParty
{
    [Key(0)]
    public MultiLiveCharacter MultiLiveCharacter { get; set; } = default!;

    [Key(1)]
    public global::Sirius.Protocol.Shared.MusicDifficulties Difficulty { get; set; } = default!;

}
